### ISSUE TITLE
Missing method "Client::builder" on the latest release 0.9.0-rc.2 

### ISSUE THREAD

**Issue by asuradev99** [serenity-rs/serenity#1017]
I tried to compile the basic ping-bot program in the examples, but I seem to be missing the serenity::Client::builder method :
```rust
error[E0599]: no function or associated item named `builder` found for struct `serenity::Client` in the current scope
  --> src/main.rs:50:30
   |
50 |     let mut client = Client::builder(&token)
   |                              ^^^^^^^ function or associated item not found in `serenity::Client`
```
However, my cargo.toml file has the latest version of the crate: 
```rust
[dependencies]
serenity = "0.9.0-rc.2"
```

**Comment by vicky5124** [comment]
`builder` will be added in the next version of serenity, for now you can replace it with `ClientBuilder::new()` if you want something that will work in the future, or `Client::new()` and switch to `builder` later.
