### ISSUE TITLE
TODO: Update tokio to 1.0

### ISSUE THREAD

**Issue by kingbri1** [serenity-rs/serenity#1021]
Opening an issue here as a reminder to update tokio to the latest version and fix any breaking changes.

NOTE: this is now v1.0

**Comment by kingbri1** [comment]
Bumping this issue. Can someone list what dependencies need to be updated before we can update the lib?

**Comment by kingbri1** [comment]
Reqwest: seanmonstar/reqwest#1076

**Comment by bahlo** [comment]
[async-tungstenite](https://crates.io/crates/async-tungstenite) needs to be updated to `0.10.0`

**Comment by evieluvsrainbows** [comment]
@bahlo serenity's deps can't be updated to anything using `tokio` v0.3.x until reqwest gets updated and then all crates can be updated at once.

**Comment by bahlo** [comment]
@KamranMackey I'm aware – I was listing other dependencies that need to be updated as well as reqwest for Tokio `0.3`. Didn't know you wanted to update all of them 👍

**Comment by kingbri1** [comment]
Hyper needs to be updated to support v0.3 before reqwest can be updated, so it's going to be a while until this is completed.

**Comment by CalliEve** [comment]
Hyper seems to be waiting on tokio to go stable and release its 1.0 version (which is expected to happen in the next weeks), before it then very soon after releases its v0.14.
[v0.14 Release Checklist](https://github.com/hyperium/hyper/issues/2352)

**Comment by kingbri1** [comment]
Once 1.0 releases, this issue will be updated to use that version instead of 0.3

**Comment by circumspect** [comment]
tokio 1.0 is out: https://tokio.rs/blog/2020-12-tokio-1-0

**Comment by kingbri1** [comment]
Hyper has been upgraded to v0.14 according to the article.

**Comment by bryanhitc** [comment]
Reqwest has merged the update: seanmonstar/reqwest#1076. Waiting on release

**Comment by bryanhitc** [comment]
Reqwest v0.11 (which includes bytes v1.0, tokio v1.0, and hyper v0.14) has been released: seanmonstar/reqwest#1133. This issue should be unblocked now. See #1161

**Comment by kingbri1** [comment]
Resolved by a27d7bb43977da0f4d10f3405b12e07d56cf9a74
