### ISSUE TITLE
PartialGuild deserialization fails on GUILD_DELETE

### ISSUE THREAD

**Issue by Headline** [serenity-rs/serenity#1023]
Hello all - I'm currently running into what I suspect is a bug inside of some of the calling logic for `guild_delete`.

The solution that was posted in the serenity discord was to implement [this](https://docs.rs/serenity/0.9.0-rc.0/serenity/prelude/trait.EventHandler.html#method.guild_member_removal) handler, but that requires the GUILD_MEMBERS intent.

I'm running version rc2, rustc 1.46.

**Comment by Headline** [comment]
I did some digging, I do not believe we have a GuildDeleteEvent at the point linked below

https://github.com/serenity-rs/serenity/blob/current/src/client/bridge/gateway/shard_runner.rs#L163

**Comment by Headline** [comment]
```
handle_event; event=Ok(Dispatch(10, Unknown(UnknownEvent { kind: "INTEGRATION_DELETE", value: Object({"application_id": String("528207522482356224"), "guild_id": String("195252651879825409"), "id": String("767165458977259561")}), _nonexhaustive: () })))
handle_gateway_dispatch; seq=10 event=Unknown(UnknownEvent { kind: "INTEGRATION_DELETE", value: Object({"application_id": String("528207522482356224"), "guild_id": String("195252651879825409"), "id": String("767165458977259561")}), _nonexhaustive: () })
handle_event; runner_tx=UnboundedSender(Some(UnboundedSenderInner { inner: UnboundedInner { state: 9223372036854775808, message_queue: Queue { head: 0x28694e0d9b0, tail: UnsafeCell }, num_senders: 3, recv_task: AtomicWaker } })) shard_id=0
handle_event; event=Ok(Dispatch(11, GuildMemberRemove(GuildMemberRemoveEvent { guild_id: GuildId(195252651879825409), user: User { id: UserId(528207522482356224), avatar: Some("bb1d99a6393e47bae563c1924a49c398"), bot: true, discriminator: 5553, name: "DiscordCompiler BETA", _nonexhaustive: () }, _nonexhaustive: () })))
handle_gateway_dispatch; seq=11 event=GuildMemberRemove(GuildMemberRemoveEvent { guild_id: GuildId(195252651879825409), user: User { id: UserId(528207522482356224), avatar: Some("bb1d99a6393e47bae563c1924a49c398"), bot: true, discriminator: 5553, name: "DiscordCompiler BETA", _nonexhaustive: () }, _nonexhaustive: () })
handle_event; runner_tx=UnboundedSender(Some(UnboundedSenderInner { inner: UnboundedInner { state: 9223372036854775808, message_queue: Queue { head: 0x28694e0d9b0, tail: UnsafeCell }, num_senders: 2, recv_task: AtomicWaker } })) shard_id=0
handle_event; event=Err(Json(Error("expected guild afk_timeout", line: 0, column: 0)))
```

**Comment by lapin-b** [comment]
Same issue on the `current` branch, commit a1b3c8ddbfde9fdcd6484d99a6f4ad6bc25a742c (commit from 15th October 2020)

The internal handler of the library gets called, but because of a deserialization error, the user's handler is never called.

```
INFO [serenity::gateway::shard] handle_event; event=Ok(Dispatch(24, GuildMemberRemove(GuildMemberRemoveEvent { guild_id: GuildId(572913620132954122), user: User { id: UserId(341956841556934657), avatar: Some("a9865fe4bd0a53fb0ffc6cd62d25e17d"), bot: true, discriminator: 2, name: "l4p1n-test-3", _nonexhaustive: () }, _nonexhaustive: () })))
INFO [serenity::gateway::shard] handle_gateway_dispatch; seq=24 event=GuildMemberRemove(GuildMemberRemoveEvent { guild_id: GuildId(572913620132954122), user: User { id: UserId(341956841556934657), avatar: Some("a9865fe4bd0a53fb0ffc6cd62d25e17d"), bot: true, discriminator: 2, name: "l4p1n-test-3", _nonexhaustive: () }, _nonexhaustive: () })
INFO [serenity::client::dispatch] handle_event; runner_tx=UnboundedSender(Some(UnboundedSenderInner { inner: UnboundedInner { state: 9223372036854775808, message_queue: Queue { head: 0x560a8e4ae9f0, tail: UnsafeCell }, num_senders: 2, recv_task: AtomicWaker } })) shard_id=0
INFO [serenity::gateway::shard] handle_event; event=Err(Json(Error("expected guild afk_timeout", line: 0, column: 0)))
```

**Comment by TheElec** [comment]
@lapin-b Can you put `debug!("Raw JSON: {:?}", value);` after line 508 in `serenity/src/client/bridge/gateway/shard_runner.rs`?
According to the Discord API `afk_timeout` should always be present, so getting a look at the raw json is going to be helpful.

We should probably add a feature or tracing based solution to print incoming raw json without editing serenity.

**Comment by arqunis** [comment]
@TheElec That is correct, it should be always present. *For guild and partial guild objects.* The `GUILD_DELETE` event, however, sends an *unavailable guild* object, which only contains two fields: 
- `id` - The id of the guild
- `unavailable` - Whether the guild is in an unavailable state

https://discord.com/developers/docs/topics/gateway#guild-delete

That is the problem here. We expect to receive a `PartialGuild` upon deletion of a guild, but we get an unavailable guild object instead.

**Comment by lapin-b** [comment]
> @lapin-b Can you put `debug!("Raw JSON: {:?}", value);` after line 508 in `serenity/src/client/bridge/gateway/shard_runner.rs`?
> According to the Discord API `afk_timeout` should always be present, so getting a look at the raw json is going to be helpful.

Just below, the raw JSON of the `GUILD_DELETE` event after I removed my test bot from the testing server:

```
DEBUG [serenity::client::bridge::gateway::shard_runner] Raw JSON: Object({"d": Object({"id": String("572913620132954122")}), "op": Number(0), "s": Number(17), "t": String("GUILD_DELETE")}) 
```
