### ISSUE TITLE
Stricter validate_token checks

### ISSUE THREAD

**Issue by leumasme** [serenity-rs/serenity#1032]
The validate_token check can be made more strict, as the parts of the token actually have a meaning.
Split by ".", the token consists of 3 base64-encoded parts:
The UserID as a string, encoded in base64;
A Timestamp of Discords Custom Token Epoch, timestamp of the token creation. (Add +1293840000 => UNIX Timestamp);
A cryptographic base64 HMAC used for the actual authorization.

We notice that just with this info we can already do some extra checks:
Do all of the dot-separated parts only contain valid base64 characters?
Is the first part a Numeric String when base64decoded?
Is the Timestamp in a realistic time range?

The UserID then has further meaning:
Converting the UserID String into a Number and then to Binary:
From Right to Left, Bits 0-12; 13-17; 17-22 are rather uninteresting.
Bits 23 to end converted to decimal are another timestamp of the Discord ID Epoch, which indicates the accounts creation date. (Add +1420070400000 => UNIX Timestamp).
This could also be checked to be in a realistic time range.

These extra checks could more easily catch accidentally adding another character in the middle of ones' token.

**Comment by kangalio** [comment]
> A Timestamp of Discords Custom Token Epoch, timestamp of the token creation. (Add +1293840000 => UNIX Timestamp);

It seems that this is not true anymore; the timestamp now uses the normal UNIX epoch.

While implementing this I noticed that the code yielded the year 2061 for my bot. After removing the Discord epoch correction and using the timestamp as a UNIX timestamp directly, the datetime matched.

**Comment by Flat** [comment]
> 
> 
> > A Timestamp of Discords Custom Token Epoch, timestamp of the token creation. (Add +1293840000 => UNIX Timestamp);
> 
> It seems that this is not true anymore; the timestamp now uses the normal UNIX epoch.
> 
> While implementing this I noticed that the code yielded the year 2061 for my bot. After removing the Discord epoch correction and using the timestamp as a UNIX timestamp directly, the datetime matched.

This will still be true for older tokens. For example mine still needs that constant added, so a check will need to be done. Should be as simple as `if < 1293840000 : add 1293840000`
