### ISSUE TITLE
Sending a bad webhook without error reporting causes the result to fail to deserialize.

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#1038]
Test code:
```rust
let embed = Embed::fake(|e| {
    e.field("test", "", false);
});

if let Err(why) = hook.execute(&ctx.http, false, |m| {
    m.embeds(vec![embed])
}).await {
    eprintln!("Error Sending Hook: {}", why)
}
```
This results in
```json
{"embeds": ["0"]}
```
which fails to deserialize and Err() is returned.
`Error Sending Hook: [Serenity] Could not decode json when receiving error response from discord!`

**Comment by Lakelezz** [comment]
I assume #1310 fixes this. If it does not, I will open this issue again.

**Comment by vicky5124** [comment]
> I assume #1310 fixes this. If it does not, I will open this issue again.

The issue is confirmed to persist:
```rust
        let hook = ChannelId(702161938012045383).webhooks(&ctx).await.unwrap()[0].clone();

        let embed = Embed::fake(|e| {
            e.field("test", "", false);
            e
        });
        
        if let Err(why) = hook.execute(&ctx.http, false, |m| {
            m.embeds(vec![embed])
        }).await {
            eprintln!("Error Sending Hook: {}", why)
        }
```
`Error Sending Hook: Invalid Form Body`

**Comment by Zaitara** [comment]
![image](https://user-images.githubusercontent.com/23212967/117205082-6baaa080-adf1-11eb-9af7-12e71a76b215.png)
I do not see the issue here, you just need to provide a `value` to the embed field

**Comment by vicky5124** [comment]
Yeah my bad, should have used the Debug formatter rather than Display
