### ISSUE TITLE
guild_member_removal/addition do not fire

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [serenity-rs/serenity#1044]
Hi, I would like to report a possible bug: 

The `guild_member_removal` and `guild_member_addition` functions of an event handler are never called (I have tested it on multiple servers using leave / kick / ban on multiple accounts).
Furthermore the `guild_member_update` function is only called for the bot own account (when adding/removing roles, changing nickname or leaving a guild).

My event handler is working normally appart from that, I have tested it with the following functions : `message`, `guild_ban_addition`, `guild_ban_removal` and it worked perfectly.

I'm using Serenity 0.9.0-rc4 on Windows 10 with Rust stable 1.47 and the following features enabled : `builder`, `cache`, `collector`, `client`, `framework`, `gateway`, `http`, `model`, `utils`, `voice`, `rustls_backend` (everything except the default framework).

**Comment by vicky5124** [comment]
@SadiinsoSnowfall since the 27th, you need to enable the guild members privileged intent to get this events, along with specifying it on the intents of the Client

**Comment by SadiinsoSnowfall** [comment]
Oh, ok, I didn't know that.
I have activated the "server member intent" option on the discord dev portal and it solved the problem, thank you.

Would it be possible to add this to the documentation of the functions in question ?

**Comment by vicky5124** [comment]
@SadiinsoSnowfall #1045
