### ISSUE TITLE
example voice rs has issues with songbird

### ISSUE THREAD

**Issue by TheK0tYaRa** [serenity-rs/serenity#1051]
`no method named 'register_songbird' found for struct 'serenity::client::ClientBuilder<'_>' in the current scope`
![image](https://user-images.githubusercontent.com/27967034/97787171-365e9500-1bb9-11eb-95cc-8df83f3c10b5.png)

**Comment by vicky5124** [comment]
It is not broken, you need to add `use songbird::SerenityInit;`

**Comment by TheK0tYaRa** [comment]
It is there. I copied the file contents.

**Comment by TheK0tYaRa** [comment]
Correction: i've resorted `use`s to be alphabetical, that may have been an issue.

**Comment by TheK0tYaRa** [comment]
Nope, no change.

**Comment by arqunis** [comment]
I've compiled the example in stable and nightly, both work fine. Are you sure you copied the code correctly? Could you show us what you have?

**Comment by TheK0tYaRa** [comment]
I had to add songbird from this git cloned repo because it's apparently not a crate.
```
[dependencies.songbird]
path = "/home/thek0tyara/Downloads/git/serenity/songbird"
```

**Comment by arqunis** [comment]
> because it's apparently not a crate.

Songbird hasn't been released onto https://crates.io yet. It's planned for the 0.10 release of Serenity, but for now it is just a part of the repository.

**Comment by TheK0tYaRa** [comment]
i've put it on [github](https://github.com/TheK0tYaRa/DiscordMultiBot) for you to see that it's barely changed

**Comment by FelixMcFelix** [comment]
You can see an example of how to do this without local cloned repos here: https://github.com/FelixMcFelix/felyne-bot/blob/350408c444379b83949bf3b55748a35dff73fbd2/Cargo.toml#L27

Cargo recursively scans a given repo to find the crate it is looking for. I use a specific revision here in case of unexpected change; this is not needed in general.

-- Kyle

**Comment by TheK0tYaRa** [comment]
well...
```
Caused by:
					  failed to load source for dependency `serenity`
					
					Caused by:
					  Unable to update https://github.com/serenity-rs/serenity.git?rev=0b46b476cc84deae38bbfacb8c7d3d8070f93ccf
```

**Comment by TheK0tYaRa** [comment]
Welp, with branch set it works fine.

**Comment by ZerothLaw** [comment]
This should not be closed - it should remain open as a reminder to finish the process of setting songbird up.
