### ISSUE TITLE
Change `dynamic_prefix` to accept `FnMut`

### ISSUE THREAD

**Issue by Plecra** [serenity-rs/serenity#1062]
https://github.com/serenity-rs/serenity/blob/49be2abe91036a48b93bc1a8ac7e3add78723417/src/framework/standard/configuration.rs#L7

This looks like a mistake. With this users cannot configure prefixes based on, well, dynamic data.

The API should really be

```rust
fn dynamic_prefix<F>(&mut self, dynamic_prefix: F) -> &mut Self
where
    F: for<'fut> FnMut(&'fut Context, &'fut Message) -> BoxFuture<'fut, Option<String>>;
```

**Comment by Lakelezz** [comment]
Hello, thank you for your issue!
Can you please elaborate why this is not possible and how your suggestion fixes this?

**Comment by Plecra** [comment]
As it is now, any data that needs to persist between calls needs to be kept in the `Context`. Closures are the idiomatic way to write stateful functions in Rust - for example, it'd allow user configuration to be provided like so (I've probably made some small mistake 😄:

```rust

let prefix: HashMap<ChannelId, Box<str>> = serde_json::from_reader(std::fs::File::open("prefixes.json")?)?;
let framework = StandardFramework::new()
    .configure(move |c| c.dynamic_prefix(move |_, msg| Box::pin(future::ready(prefix.get(msg.channel_id).as_deref().unwrap_or("!").to_string()));

**Comment by Lakelezz** [comment]
`FnMut` is a trait which requires boxing and dynamic dispatch, thus leading to multiple indirections as opposed to just `fn`.
Additionally, the trait would require restructuring of internal code that I do not really find reasoned. Using `Context` is the intended approach for this. 
If there is a problem using `Context`, please tell me! : )

**Comment by Plecra** [comment]
[If your goal is saving a single instruction](https://godbolt.org/z/MYG3fo), then it's true that function pointers have the edge, but that's the only cost to this change: Any closures that could be coerced to a `fn` previously will be ZSTs and boxing them won't allocate (it's effectively free).

Whether the refactor is worth the maintenance burden is entirely up to you, though I expect the changes would be minimal. If you don't see value in the ergonomics improvement, I couldn't convince you otherwise 😜

**Comment by Lakelezz** [comment]
The critical issue is that `Fn` *would be fine*, but once you need mutability to call on `FnMut`, things will become very painful.
You will need to gain mutability to call the function, requiring mutability over the framework dispatch.

By the way, there is no guarantee your box will be free at all, try using one in your example and you will encounter a very different instruction result.
