### ISSUE TITLE
reacting to external events

### ISSUE THREAD

**Issue by yazgoo** [serenity-rs/serenity#1070]
Is it possible to react to external events, out of discord, where the program runs, like input in terminal ...
if so, how to do so ?

Thanks

**Comment by arqunis** [comment]
That is outside of the scope of the library, it only deals with events originating from Discord. You will have to reach out to the standard library or external libraries for awaiting events from the terminal or somewhere else.

For example, to get input from the terminal, you can [read from standard input](https://doc.rust-lang.org/stable/std/io/fn.stdin.html) and perform actions based on the input:
```rust
use std::io::{BufRead, stdin};
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let mut buffer = String::new();
    let stdin = stdin();
    loop {
        buffer.clear();
        if stdin.read_line(&mut buffer)? == 0 {
            // Reached the end.
            break;
        }
        
        // Do whatever you want with the line stored in `buffer`. 
        // Here, we just print back the input.
        println!("I have read the line \"{}\"", buffer);
    }

    Ok(())
}
```

If you want to await, for instance, keypresses in the terminal, you will have to use a library like [termion](https://docs.rs/termion/1.5.5/termion/).

**Comment by peppizza** [comment]
It should also be noted that to run any tasks alongside the bot, as `Client::start()` is a blocking call, you should call `tokio::spawn()` before calling `Client::start()`

ex:
```rust
use std::io::{BufRead, stdin};
use std::error::Error;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    // client initialization code


    tokio::spawn(async move {
        let mut buffer = String::new();
        let stdin = stdin();
        loop {
            buffer.clear();
            if stdin.read_line(&mut buffer)? == 0 {
                // Reached the end.
                break;
            }
        
            // Do whatever you want with the line stored in `buffer`. 
            // Here, we just print back the input.
            println!("I have read the line \"{}\"", buffer);
        }
    })

    client.start()?;

    Ok(())
}
```

**Comment by yazgoo** [comment]
> It should also be noted that to run any tasks alongside the bot, as `Client::start()` is a blocking call, you should call `tokio::spawn()` before calling `Client::start()`

Thanks for your answers.

What If I want to access the client from my task ?
(For example, I would like to move a user in a different chan based on user input)
Should I instantiate another client ?

**Comment by peppizza** [comment]
afaik there's no good way to copy/clone the client object as it does not derive either trait, and its \*probably* not a good idea to initiate another client (but i don't really know), what i would recommend doing is cloning the CacheAndHttp field from the client, as it provides most functions that the client provides.

ex:
```rust
let cache_and_http = client.cache_and_http.clone();

tokio::spawn(async move {
    // do something with cache_and_http
});
```

**Comment by yazgoo** [comment]
Thanks, in the end I used the example from
https://github.com/serenity-rs/serenity/pull/997
with success
