### ISSUE TITLE
Audio doesn't work for unclear reason

### ISSUE THREAD

**Issue by DoumanAsh** [serenity-rs/serenity#1083]
Version: 0.9.1

Weirdly enough it happens on my Linux VPS.

Bot joins voice channel and it supposed to play youtube video, but for some reason it does nothing once joined.

On my windows laptop where it works I see some timers for audio, which is not happening on Linux:

```
Nov 22 23:46:48.589  INFO runner:cycle{audio_timer=Timer { due: Instant { t: 34339.5947579s }, duration: 20ms } bitrate=BitsPerSecond(128000) muted=false}:set_speaking{speaking=true}: serenity::voice::connection: [Voice] Speaking update: true
Nov 22 23:46:48.590  INFO runner:cycle{audio_timer=Timer { due: Instant { t: 34339.5947579s }, duration: 20ms } bitrate=BitsPerSecond(128000) muted=false}:set_speaking{speaking=true}: serenity::voice::connection: [Voice] Speaking update confirmed.
```

I'm not sure what can be a reason hence issue.

**Comment by peppizza** [comment]
It could be an issue with cross-compilation as I develop on linux and it works fine on my linux vps

**Comment by DoumanAsh** [comment]
For linux I originally didn't cross compile, but built with ubuntu's image.
I also tried to build statically with musl using opus's cmake, and it made no difference unfortunately.
I'm not really sure it is related to opus itself, as I do not seem to notice audio related timers in logs

**Comment by arqunis** [comment]
Closing this for insufficient information to work on a fix.
