### ISSUE TITLE
Expose option<guildId> in message_delete event handler

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [serenity-rs/serenity#1088]
The current handler for the MESSAGE_DELETE event is the following : 
`message_delete(&self, ctx: Context, channel_id: ChannelId, deleted_message_id: MessageId)`

But the discord API does send a `Option<GuildId>` in this event payload: (https://discord.com/developers/docs/topics/gateway#message-delete)

Furthermore this field is already parsed and stored in the event definition (see [Events.rs/MessageDeleteEvent](https://github.com/serenity-rs/serenity/blob/current/src/model/event.rs#L931)).

I think this field should be exposed in the event handler (by modifying [event_handler.rs](https://github.com/serenity-rs/serenity/blob/current/src/client/event_handler.rs#L239) and [dispatch.rs](https://github.com/serenity-rs/serenity/blob/current/src/client/dispatch.rs#L614) accordingly).

There is also a similar design issue with the MESSAGE_DELETE_BULK event handler.

Issue found on Serenity 0.9.1

**Comment by SadiinsoSnowfall** [comment]
I can open a pull request if needed. The problem is that this would be a breaking change for all users implementing the message_delete and message_delete_bulk functions of the EventHandler trait (though somewhat easy to fix).

**Comment by arqunis** [comment]
You are free to open a pull request. Make sure you target the `current` branch, `v0.9.x` cannot accept breaking changes.
