### ISSUE TITLE
Invalid Documentation About `MessageTooLong`

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [serenity-rs/serenity#1092]
The documentation for the MessageTooLong  states the following : 
>Indicates that a [`Message`]s content was too long and will not successfully send, as the length is over 2000 codepoints, or 4000 bytes. 
The number of bytes larger than the limit is provided.

But this is not what is computed/returned by the [Message::overflow_length](https://github.com/serenity-rs/serenity/blob/current/src/model/channel/message.rs#L466) function (the function whose return value is used to create said error).

The function is in fact checking that the message length __in characters__ is not greater than 2000, but isn't checking the length in bytes in any way. Furthermore, the return value represent the overflow in characters, not bytes (as it is explained in the function documentation).

Also, I think the `overflow_length` function can be refactored to return an `usize` or an `Option<usize>` instead of an `Option<u64>` and the `MESSAGE_CODE_LIMIT` constant type can be changed to usize. This is because the size of a String is usually measured in usize and the said constant is always casted to an i64 or an u64 when used.

The part of the documentation about the 4000 bytes limit should be either removed, or this limit need to be enforced in the  `overflow_length` function (note that a character is not always 2 bytes long, see [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d1cfebc533cb8e93562bacece669a6e1)).

**Comment by SadiinsoSnowfall** [comment]
I have just tested it and there is no 4000 bytes limit when sending a message (only a 2000 characters limit).
A bot based on serenity can send a messages made of 2000 emojis (8000 bytes) without any problem. The part of the documentation about the 4000 bytes can therefore be safely removed.

**Comment by Lakelezz** [comment]
Yes, I think this is correct. Thank you for informing us about this incorrect documentation.
If you want, you may fix it, if not, that's fine, just want to offer you the chance since you found it :)

**Comment by SadiinsoSnowfall** [comment]
I can open a PR to fix the documentation.
What about my proposition of refactoring the code to use `usize` instead of `u64` to represent the overflow ?

**Comment by arqunis** [comment]
You should open a pull request to 0.8 for the documentation change, I'll port it over to 0.9 and the `current` and `next` branches. The `u64` -> `usize` change should be targeted to the `current` branch in a separate pull request, as it is a breaking change.

**Comment by Flat** [comment]
This issue should be addressed with #1099 and #1100
