### ISSUE TITLE
Remove Collected Message/Reaction From Collectors?

### ISSUE THREAD

**Issue by JIceberg** [serenity-rs/serenity#1096]
I've been perusing through the docs and source code, and am wondering if there is currently a good way to do this in a single process. Is there a way to remove a reaction/message from a collector?

For example, if, on a message that is being processed for a reaction collector, a reaction that was collected is later removed but the collector is still processing, how could I best remove that reaction from the collector?

From what I can see so far though, I don't really see a way to do this (this meaning remove what has already been collected). Let me know if that isn't the case.

**Comment by Lakelezz** [comment]
Do you have example code?

A collector will work like a stream and hand you the collected items. When the collector gets `drop`'ed or you call `stop` on it, it will discontinue receiving items. 
It just forwards events to you, the events still happened and are not being erased.
If you collect added and removed emotes, you add emote A and remove emote A, you have two actions that occurred and they will be collected.

If you could provide your specific situation in code, I may be able to provide further help!

**Comment by JIceberg** [comment]
I see, that makes sense! So, if I understand correctly, it collects a stream of the emitted websocket events for when the reaction/message is added or deleted/removed?

**Comment by Lakelezz** [comment]
You can have a look here for version 0.9: https://github.com/serenity-rs/serenity/blob/v0.9.x/examples/e12_collectors/src/main.rs#L151

This uses the stream extension trait `futures::stream::StreamExt` and elaborates a bit.
Your understanding is correct, a collector is collecting dispatched Discord websocket events based on your filter criteria!
