### ISSUE TITLE
Discord link expired?

### ISSUE THREAD

**Issue by bbigras** [serenity-rs/serenity#1115]
https://discord.gg/9x7vcus doesn't seem to work.

**Comment by arqunis** [comment]
It is https://discord.com/invite/9X7vCus. The casing of the X and C characters matters.

**Comment by arqunis** [comment]
It appears Github lowercases the characters for the website link when displayed, that's how you got that invalid link.

**Comment by bbigras** [comment]
Oh yeah I copy pasted the text instead of the link. Thanks.
