### ISSUE TITLE
Rate Limit buckets rework

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/serenity#1117]
Not having them be guild specific will lead to commands being blocked in one server, because it was run in another

**Comment by Lakelezz** [comment]
I do want buckets reworked at one point and this is surely a feature we would add!

**Comment by peppizza** [comment]
I would suggest a very similar api to that of discord.py

https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=buckettype#discord.discord.ext.commands.BucketType

**Comment by Lakelezz** [comment]
Looks very nice. Another part I wanted to add was cancelling of buckets or rather refilling during dispatch or later.

Imagine you have a command performing an expensive operation but only on one code flow.
That means, if this potentially expensive command does not reach this branch, it will be on a long cooldown, despite the error actually being an input error.
Checks can mitigate this but they are limited in their ability nor can they propagate calculations.
As a result, it may be good to return an error inside the command that will lead to the framework reverting the bucket.

**Comment by peppizza** [comment]
This would be a breaking change, but I would also propose renaming buckets to a cooldown, as calling it buckets could be confusing with the new intents buckets

**Comment by Lakelezz** [comment]
I am working on this!

**Comment by Lakelezz** [comment]
I implemented your feature request, feel free to test this pull request: #1123 
It covers your example with the exception of buckets per roles, not sure how that would work. Does it just collect a bucket for every role on a user? That's the only way I could imagine it.

Thank you for this nice suggestion :)

**Comment by peppizza** [comment]
yeah sorry I was in school but I will definitely test this as it looks really good

**Comment by Lakelezz** [comment]
No worries and no stress :)
