### ISSUE TITLE
Rate Limits are not entirely followed.

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#1120]
The "10,000 requests per 10 minutes" http rate limit doesn't seem to be followed.

`thread 'main' panicked at 'Could not access application info: Http(UnsuccessfulRequest(ErrorResponse { status_code: 429, url: Url { scheme: "https", host: Some(Domain("discord.com")), port: None, path: "/api/v8/oauth2/applications/@me", query: None, fragment: None }, error: "You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward." }))', src/main.rs:975:21`

My ip just got temporarily banned from using the HTTP api because of this. Though i actually have no idea what in my bot can even cause such rate limits
This appears to be an issue with reconnecting, as this temporal ban happened as the dns server i use died, and when it came back, it was unable to connect.

(btw i can read general chat, but i can't type on it :P)

**Comment by kangalio** [comment]
https://github.com/serenity-rs/serenity/blob/339994bf4752a645d8ec9031ff68762820d7fe7b/src/http/routing.rs#L2575-L2576

Maybe get_current_application_info() shouldn't have ratelimits disabled :thinking: 

(Route is a misnomer and means RatelimitBucket, so Route::None means this route doesn't have any ratelimit bucket)

**Comment by kangalio** [comment]
Is this still an issue on the `next` branch? If so, how to reproduce?

**Comment by vicky5124** [comment]
What has been commented shouldn't be an issue anymore, as the x-ratelimit-* headers are now followed on webhooks, when they didn't used to (as they weren't present in the past either). https://github.com/serenity-rs/serenity/pull/1408 also helped fix this issue.

But there's another issue at hand still present afaik. The Web Socket does not have rate limiting. The gateway listens to the rate of 120 messages a minute, but setting Activity/Presence/Status or requesting for guild member chunks can easily make the requests go over the Web Sockets rate limit of 120/min, and if the request does not go through (if the DNS dies, lost network connection, system lag, etc...) when the connection revives, it all goes through at once and causes this.
Back then this could also be caused by "bot blow-up" guilds, that had 500+ bots and used them all at once, but right now there's an integration limit that limits the amount of bots a guild can have, so this is not an issue anymore.

**Comment by kangalio** [comment]
What rate limit of 120/min are you talking about? That 120 messages a minute figure is just how often a ShardRunner interrupts listening to websocket messages in order to process incoming ShardRunnerMessage's. Nothing of that logic reaches Discord's servers.

**Comment by vicky5124** [comment]
nvm, checked he discord api docs, and there's no mention of a web socket poll rate limit. This can be closed.
