### ISSUE TITLE
Webhooks don't follow rate limit

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#1121]
The cause of the issue that happened on #1120 has been determinated to be webhooks not following the rate limits.
Both issues should still be fixed though.

**Comment by kangalio** [comment]
Maybe this is related to all of the following requests sharing the same ratelimit bucket (`Route` enum variant)?
- GetWebhook(WithToken)
- CreateFollowupMessage
- DeleteWebhook(WithToken)
- EditWebhook(WithToken)
- ExecuteWebhook

**Comment by kangalio** [comment]
Is this still an issue on the `next` branch? If so, how to reproduce?

**Comment by vicky5124** [comment]
This shouldn't be an issue anymore, as the x-ratelimit-* headers are now followed on webhooks, when they didn't used to. More details in #1120
