### ISSUE TITLE
Support slash commands

### ISSUE THREAD

**Issue by CalliEve** [serenity-rs/serenity#1126]
Hi!

With discord releasing slash commands to bots just now, it would be nice if serenity supported them too.

https://discord.com/developers/docs/interactions/slash-commands

This would mean supporting the following api endpoints:
- [Get Global Application Commands](https://discord.com/developers/docs/interactions/slash-commands#get-global-application-commands)
- [Create Global Application Commands](https://discord.com/developers/docs/interactions/slash-commands#create-global-application-command)
- [Edit Global Application Commands](https://discord.com/developers/docs/interactions/slash-commands#edit-global-application-command)
- [Delete Global Application Commands](https://discord.com/developers/docs/interactions/slash-commands#delete-global-application-command)
- [Get Guild Application Commands](https://discord.com/developers/docs/interactions/slash-commands#get-guild-application-commands)
- [Create Guild Application Commands](https://discord.com/developers/docs/interactions/slash-commands#create-guild-application-commands)
- [Edit Guild Application Commands](https://discord.com/developers/docs/interactions/slash-commands#edit-guild-application-command)
- [Delete Guild Application Commands](https://discord.com/developers/docs/interactions/slash-commands#delete-guild-application-command)
- [Create Interaction Response](https://discord.com/developers/docs/interactions/slash-commands#create-interaction-response)
- [Edit Original Interaction Response](https://discord.com/developers/docs/interactions/slash-commands#edit-original-interaction-response)
- [Delete Original Interaction Response](https://discord.com/developers/docs/interactions/slash-commands#delete-original-interaction-response)
- [Create Followup Message](https://discord.com/developers/docs/interactions/slash-commands#create-followup-message)
- [Edit Followup Message](https://discord.com/developers/docs/interactions/slash-commands#edit-followup-message)
- [Delete Followup Message](https://discord.com/developers/docs/interactions/slash-commands#delete-followup-message)

Supporting the following gateway event:
- [INTERACTION_CREATE](https://discord.com/developers/docs/topics/gateway#interaction-create)

And/or supporting [webhooks](https://discord.com/developers/docs/interactions/slash-commands#receiving-an-interaction) instead of the gateway event.

**Comment by CalliEve** [comment]
I think that it would be good to start off with adding support for the models, api calls and gateway event added by this discord update, with later on building on that to add support for slash commands in the command framework. In addition I think discussion can be had on if/how to support webhooks for this later on too.

For now though, unless someone else has already started working on it of course, I would like to work on adding these models, api methods and gateway event to the crate the coming days.

**Comment by overlisted** [comment]
It would be epic if this was one of the first libraries to add slash commads

**Comment by lukasdiegelmann** [comment]
Hey, that is really nice, but I have no idea of how to use it. There is no useful documentation about it, and, since it is a unstable feature - at least I think that's the reason - there is no documentation on docs.rs either. It would be really nice to see some methods more documented.

As an example: The description of `ApplicationCommand::create_global_application_command`, which actually has good doc, tells me to use `ApplicationCommand::create_guild_application_command`. And while it is completely reasonable to do so in the testing phase I do not think it is implemented yet. Well either that or I simply can't find it.

The example on this repository regarding slash commands is also very slim. It does not even tell you how to create an ApplicationCommand (found that out by luck).

**Comment by Zaitara** [comment]
Hey, thank you for you feedback.
I understand that the current implementation might be difficult to understand, this is why I'm currently working on adding a better example and clarifying some parts of the documentation in #1356, which will makes many improvements to the documentation (and the example). 
Feel free to submit a more specific feedback there, but please do not comment here about that (or create a new issue).
