### ISSUE TITLE
Improve permission checking

### ISSUE THREAD

**Issue by ThatsNoMoon** [serenity-rs/serenity#1134]
I think serenity's permission checking could be made more robust and flexible. As an example, [`GuildChannel::permissions_for_user`](https://docs.rs/serenity/0.9.2/serenity/model/channel/struct.GuildChannel.html#method.permissions_for_user) is both asynchronous and fallible, but it neither fetches uncached members nor fails if they are uncached, because it relies only on [`Guild::user_permissions_in`](https://docs.rs/serenity/0.9.2/serenity/model/guild/struct.Guild.html#method.user_permissions_in) which is neither asynchronous nor fallible.

The design I would like to see is changing `Guild::user_permissions_in` to use arguments of `&GuildChannel` and `&Member`. There are failure cases in this function that are almost entirely covered by an invalid `ChannelId` or `UserId` being passed, and changing the types in this way means these failures are ruled out by construction. With this change, functions like `GuildChannel::permissions_for_user` can try to get the `Member` object from the `Guild`'s cache themselves, and if it is nonexistent, can either fetch the `Member` or return an error, as appropriate.

The less appealing alternative to me is simply making `Guild::user_permissions_in` fallible. There are two different failure cases, so an `Option` can't practically be used to encode the result, which means `Result<Permission>` is the next best option. This forces users to match on the error they get to see if it was a missing channel or missing member, and `Error` has a lot more surface area than is necessary to encode the actual result of this function. Once they've determined what caused the error, there is no clear way to recover from the error, since there is no method that doesn't require already having a cached `Member` and `GuildChannel`. One could be added, but then this method becomes somewhat redundant and, in my opinion, a strictly less robust method than the first solution I suggested.

I think this is almost a necessary change. Bots very frequently rely on discord permissions to determine what actions are appropriate for the bot to carry out on behalf of a user. With incorrect permission checking, bots based on serenity can have disastrous bugs, like leaking private messages from channels that users cannot read themselves but that the bot incorrectly calculated they could.

I'm open to implementing these changes myself, but I would like to see what direction should be taken to get my changes approved.

**Comment by ThatsNoMoon** [comment]
I'm working on [a branch for this](https://github.com/ThatsNoMoon/serenity/tree/permission-checking) with the smallest changes that I think solve the problem acceptably, but after implementing it, I think there could be a better way, like moving the core implementation out of `Guild` entirely. I'd appreciate it if someone could look over my changes to discuss the direction I'm going in.

**Comment by Lakelezz** [comment]
> I'm working on [a branch for this](https://github.com/ThatsNoMoon/serenity/tree/permission-checking) with the smallest changes that I think solve the problem acceptably, but after implementing it, I think there could be a better way, like moving the core implementation out of `Guild` entirely. I'd appreciate it if someone could look over my changes to discuss the direction I'm going in.

Feel free to open a pull request, we will take a look then!
