### ISSUE TITLE
Edit/Delete Webhook Message endpoints

### ISSUE THREAD

**Issue by CalliEve** [serenity-rs/serenity#1137]
Recently the api endpoints [Edit Webhook Message](https://discord.com/developers/docs/resources/webhook#edit-webhook-message) and [Delete Webhook Message](https://discord.com/developers/docs/resources/webhook#delete-webhook-message) have been added to the discord api, but these are not yet supported by serenity. It would be nice if support for these endpoints could be added.

**Comment by radiohertz** [comment]
can i take this up?

**Comment by Zaitara** [comment]
It was added in #1267
