### ISSUE TITLE
Improve errors from Emoji::delete() (plus more?)

### ISSUE THREAD

**Issue by skairunner** [serenity-rs/serenity#1138]
`Emoji::delete()` returns `Error::Model(ModelError::ItemMissing)` in two cases: 

(a) there is no cache, or
(b) there is no guild in the cache.

This is slightly confusing because the error message suggests that it's the guild that's missing. It may be nice to return a different error, such as CacheMissing, when there is no cache. Mostly this happens when you pass `ctx.http` instead of `ctx`.

This probably applies to other methods as well, not just `Emoji::delete`.

**Comment by Lakelezz** [comment]
In my opinion, the better approach is tightening the signature here to allow the cache _with_ HTTP only.
We will have to figure out a potential approach for this.

My idea is changing the type to implement `AsRef<Cache> + AsRef<Http>`. 
Without the cache, the function would never work anyway.
