### ISSUE TITLE
Support slash commands in standard framework

### ISSUE THREAD

**Issue by peppizza** [serenity-rs/serenity#1145]
Now that slash commands are in the library, they should be supported inside of the standard framework

**Comment by Absolucy** [comment]
has there been any progress on this? I'd offer to help with it myself... but the inner code is a bit too complex for me to work with, sorry.

**Comment by arqunis** [comment]
There has been none thus far. This is because I have decided to wait until Discord stabilises the slash commands API to try to add them to the [framework rewrite](https://github.com/serenity-rs/framework) or create a new framework specialised for slash commands.

**Comment by Lakelezz** [comment]
> 
> 
> guys, anyone got slash command work?
> 
> ```
> error[E0599]: no function or associated item named `get_global_application_commands` found for struct `serenity::model::interactions::ApplicationCommand` in the current scope
> ```
> 
> ```
> error[E0599]: no method named `application_id` found for struct `serenity::client::ClientBuilder<'_>` in the current scope
> ```
> 
> what version of serenity ClientBuilder include this application_id method and get_global_application_commands for ApplicationCommand? I'm using serenity 0.10 and 0.10.5, both don't have those methods.

Hello, I'm sorry but this question should be asked in its own new issue.

**Comment by BuyMyMojo** [comment]
Slash commands will become basically mandatory for most bots in more then 75 servers in about a month.

This being added to the standard library should take place by that time

**Comment by kangalio** [comment]
Related: #1462, #804

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
