### ISSUE TITLE
Bot only finds self when checking list of guild members

### ISSUE THREAD

**Issue by circumspect** [serenity-rs/serenity#1150]
I can't seem to get my bot to find other users in the server, even after enabling and adding the Server Members gateway intent. The code I'm using to try to list them looks like the following:

```rust
#[command]
pub async fn list(ctx: &Context, msg: &Message) -> CommandResult {
    let guild_members = ctx.cache.guild_field(msg.guild_id.unwrap(), |guild| guild.members.to_owned()).await.unwrap();
    for (id, member) in guild_members {
        println!("User: {}, ID: {}", member.display_name(), id);
    }

    Ok(())
}
```

The command runs without errors, but only prints out the bot's username/ID. Does this have something to do with the cache?

**Comment by Tuetuopay** [comment]
I do see the same odd behaviour, and I've been banging my head for a few weeks on why my cache is empty.

I though it was related to the Intents change applied to API v6, but I cannot get it to work, despite enabling the "Server Members Intent" in my developer portal and enabling the ` GUILDS` and ` GUILD_MEMBERS` intents client-side. I do get the ` guild_create` event shortly after startup, but the `members`  field of the provided guild only contains the bot itself, and none of the other members. This should be why you only have your bot in the cache, as it is the only event reaching you.

For reference, here is my client setup:
```rust
let mut client = Client::builder(&config.auth.token)
    .event_handler(Bot)
    .framework(framework)
    .add_intent(GatewayIntents::GUILDS)
    .add_intent(GatewayIntents::GUILD_MEMBERS)
    .add_intent(GatewayIntents::GUILD_MESSAGES)
    .await
    .expect("Failed to create discord client");
```

**Comment by circumspect** [comment]
I tested it with the roles in the server and it pulls all of them successfully, so I think this issue is specific to the members gateway intent. For example, the following code works as expected:

```rust
#[command]
pub async fn list_roles(ctx: &Context, msg: &Message) -> CommandResult {
    let guild_roles = ctx.cache.guild_roles(msg.guild_id.unwrap()).await.unwrap();
    for (id, role) in guild_roles {
        println!("Role: {}, ID: {}", role.name, id);
    }

    Ok(())
}
```

**Comment by circumspect** [comment]
Listing all channels also works:

```rust
#[command]
pub async fn list_channels(ctx: &Context, msg: &Message) -> CommandResult {
    let guild_channels = ctx.cache.guild_channels(msg.guild_id.unwrap()).await.unwrap();
    for (id, channel) in guild_channels {
        println!("Channel: {}, ID: {}", channel.name, id);
    }

    Ok(())
}
```

**Comment by Tuetuopay** [comment]
Yeah I just tested getting a single channel from the cache and it definitely works. The guild members log shows only the bot, and trying to fetch a user ID from the cache other than my bot id yelds None

```rust
#[serenity::async_trait]
impl EventHandler for Bot {
    async fn guild_create(&self, ctx: Context, guild: Guild, is_new: bool) {
        debug!("Serenity guild created {:#?}", guild.id);
        debug!("Guild members: {:?}", guild.members);

        let chan_test_id = 774712259871506443u64;
        let chan = ctx.cache.channel(chan_test_id).await;
        debug!("Cached #test: {:?}", chan);
    }
}
```

**Comment by Tuetuopay** [comment]
It looks like serenity does not requests the member list on startup. I tried using the [Request Guild Members](https://discord.com/developers/docs/topics/gateway#request-guild-members) websocket command to no avail, the gateway replies with a `4001 Unknown Opcode`, despite the actual opcode used by serenity matching the one found in the docs (8)...

```rust
#[async_trait]
impl EventHandler for Bot {
    async fn guild_create(&self, ctx: Context, guild: Guild, is_new: bool) {
        // Send a member chunk request to the shard
        ctx.shard.chunk_guild(guild.id, None, ChunkGuildFilter::None, None);
    }
}
```

**Comment by kangalio** [comment]
After scavenging Discord's API docs, I found this: https://discord.com/developers/docs/topics/gateway#guild-create

> If you are using Gateway Intents, members and presences returned in this event will only contain your bot and users in voice channels unless you specify the GUILD_PRESENCES intent.

In other words, you have to turn on the Presence Intent switch for your bot in the Discord Developer Portal if you want to receive member data.

(This is totally stupid from Discord because there's also a Server Members intent which is **apparently** not related to member info at all. So yeah, Presence Intent is what Discord apparently wants you to turn on to get member data, _not "Server Members"_)

![Screenshot_20210213_175814](https://user-images.githubusercontent.com/21220820/107855841-22b40300-6e25-11eb-9c36-8616b01ce140.png)

**Comment by circumspect** [comment]
Just tested and this seems to work perfectly, thanks! Strangely enough the Server Members intent seems to be enough for discord.py, though that might need to be tested.
