### ISSUE TITLE
Support multiple Embed in builder

### ISSUE THREAD

**Issue by Wolvereness** [serenity-rs/serenity#1152]
# Support multiple Embed in builder

Opening an issue for this before I start development.

The intention would be to add a few more functions (like `add_embed`, `clear_embeds`). For the old/current methods, either:
* removing (not quite painless transition),
* deprecating (warnings during transition), or
* clarifying their documentation such that they will clear previous embeds and add one (painless transition).

**Comment by kangalio** [comment]
CreateMessage now has functions to add multiple embeds https://docs.rs/serenity/latest/serenity/builder/struct.CreateMessage.html

**Comment by Wolvereness** [comment]
I forgot/stopped-caring; I had originally hoped for some type of feedback.
