### ISSUE TITLE
Unsuccessful Request For Application Info

### ISSUE THREAD

**Issue by JIceberg** [serenity-rs/serenity#1155]
Below is the error that was produced
```
thread 'main' panicked at 'Could not access application info: Http(UnsuccessfulRequest(ErrorResponse { status_code: 401, url: Url { scheme: 
"https", host: Some(Domain("discord.com")), port: None, path: "/api/v6/oauth2/applications/@me", query: None, fragment: None }, error: "401: Unauthorized" }))'
```
I'm just running this (the rest of the program is in-line with the `e05_command_framework` example):
```rust
    let http = Http::new_with_token(&token);

    let (owners, bot_id) = match http.get_current_application_info().await {
        Ok(info) => {
            let mut owners = HashSet::new();
            if let Some(team) = info.team {
                owners.insert(team.owner_user_id);
            } else {
                owners.insert(info.owner.id);
            }
            match http.get_current_user().await {
                Ok(bot_id) => (owners, bot_id.id),
                Err(why) => panic!("Could not access the bot id: {:?}", why),
            }
        },
        Err(why) => panic!("Could not access application info: {:?}", why),  /* THIS IS THE LINE THAT'S PANICKING */
    };
```
I then tried just running the `e01_basic_ping_bot` but with my token and it said it was an invalid authentication error on `client.start()`. The token is correct. When I run a python script with my token, it works just fine with no issues.

Am I doing something wrong? For context, I'm using 0.9.3.

**Comment by vicky5124** [comment]
how is `token` being defined?

**Comment by JIceberg** [comment]
I have it set up using `dotenv`. I've tested both hardcoding it and using `dotenv` with the same result.
```rust
dotenv::dotenv().expect("Could not read .env");
let token = dotenv::var("DISCORD_TOKEN").expect("Expected a token in the environment");
```
In my `.env` file it's set up like `DISCORD_TOKEN=token`.

**Comment by adumbidiot** [comment]
@JIceberg Are you trying to use a user token? Those aren't supported by this library.

**Comment by JIceberg** [comment]
No, I am not using a user token.

**Comment by JIceberg** [comment]
For further context, I had a bot with this token I was testing and had successfully run this code several times. A week later, it no longer was working. Now no matter what bot token I use or what program I run, it does not work and prompts me with the same error.

**Comment by JIceberg** [comment]
Closing this because it randomly started working again.
