### ISSUE TITLE
`utils::user_has_perms` Fails When Cache Lacks Items

### ISSUE THREAD

**Issue by drklee3** [serenity-rs/serenity#1166]
`Message::delete` fails on the bot's own message during the permissions check in `utils::user_has_perms` with `Err(ChannelNotFound)` as private channels are not cached anymore (Bots no longer receive channel create events for private channels on v8).

Basic example:

```rust
let dm_chan = msg.author.create_dm_channel(&ctx).await.unwrap().id;

let m = dm_chan
  .say(&ctx, "hello")
  .await
  .unwrap();

dbg!(m.delete(&ctx).await);
// Err(ChannelNotFound)
```

Permission check for `Message::delete` with the cache should be skipped(?) if the message is both the bot's own and in a private channel.  It may also fail in other cases where it uses the cache.

Also, if private channels are no longer cached, it could probably be removed from the cache struct entirely.

**Comment by lanastara** [comment]
I just had the exact same problem on a public channel. deleting a message via http.delete_message works but message.delete return ChannelNotFound.

**Comment by Lakelezz** [comment]
If you pass only the HTTP to the method, e.g. `ctx.http`, it would work.

The issue stems from the fact that some channels are not cached when you are missing specific gateway intents.
When you supply the cache to the method, it will attempt to grab the channel from the cache, as it is missing, it will return `ChannelNotFound`.

**Comment by Lakelezz** [comment]
I will fix this. We will no longer return errors from utility methods when it's a cache related model error but send the request instead.
