### ISSUE TITLE
PresenceUpdateEvent::Presence::user is empty

### ISSUE THREAD

**Issue by damccull** [serenity-rs/serenity#1184]
Why is the PresenceUpdateEvent::Presence::user field almost always empty in the `presence_update` EventHandler function? The user_id is correct, but the user object is usually empty. It seems, to me, to be returning the presence object before the user has been populated fuly. How can I guarantee that it gets populated? Or do I need to do a separate user lookup call after getting the id?

**Comment by arqunis** [comment]
[As per their documentation](https://discord.com/developers/docs/topics/gateway#presence-update), Discord does not guarantee that it will send the user object in full; only the user id is a required field. If you want the user data, you'll have to perform a lookup.

However, I looked at the definition of the `Presence` and saw that [the deserialization of the user object is wrong](https://github.com/serenity-rs/serenity/blob/current/src/model/gateway.rs#L525-L538). It either expects full data for a user object, or just the user id. It doesn't account for some fields missing, which it should.
