### ISSUE TITLE
Help shows commands as unavailable but they work

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#1195]
The help command shows commands as unavailable but they work fine with the required permissions.
serenity v0.10.2 - [source](https://github.com/nickelc/modio-bot/blob/master/src/commands/subs.rs#L12-L16)

```rust
#[command]
#[description = "List subscriptions of the current channel to mod updates of a game"]
#[aliases("subs")]
#[required_permissions("MANAGE_CHANNELS")]
pub async fn subscriptions(ctx: &Context, msg: &Message) -> CommandResult {
  // snip
}
```
![image](https://user-images.githubusercontent.com/2128532/105057194-43cb4300-5a75-11eb-98e9-12c4946b979f.png)

I don't know if this is related but the help command doesn't work for those commands either.

![image](https://user-images.githubusercontent.com/2128532/105058182-3b273c80-5a76-11eb-8d55-dc998d975c59.png)

**Comment by vicky5124** [comment]
Do you have both privileged intents enabled? i know this issue happens when one of them is not set, causing members to not get cached properly

**Comment by nickelc** [comment]
> Do you have both privileged intents enabled? 

no

> i know this issue happens when one of them is not set, causing members to not get cached properly

but then i would expect the commands not working at all.

**Comment by Lakelezz** [comment]
The framework fetches uncached members via the REST API when you disable intents for caching members.
In contrast, the help system does not do this.

Please try enabling needed intents and see if it resolves that for the time being.
