### ISSUE TITLE
Adding stricter Clippy lints to Serenity

### ISSUE THREAD

**Issue by Th3-M4jor** [serenity-rs/serenity#1198]
I'm opening this issue to discuss if we should be a little more granular with the Clippy lints we deny globally, and if so which ones should we deny globally?

The full list can be found [here](https://rust-lang.github.io/rust-clippy/master/index.html).
I'd like to deny these globally to start with:
- [x] ~~[expect_used](https://rust-lang.github.io/rust-clippy/master/index.html#expect_used)~~
- [x] [unwrap_used](https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used)
- [x] [non_ascii_literal](https://rust-lang.github.io/rust-clippy/master/index.html#non_ascii_literal)

And maybe this one:
- [x] [missing_errors_doc](https://rust-lang.github.io/rust-clippy/master/index.html#missing_errors_doc)

As discussed in the Discord:
- [x] [let_underscore_must_use](https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_must_use)

I don't mind writing the PR to add and fix them once we settle on a list.

**Comment by Th3-M4jor** [comment]
Decided against adding a lint for usage of `expect()`, because currently all instances of it should panic.

**Comment by vicky5124** [comment]
As mentioned on the discord, implement [this](https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_must_use) clippy lint too.
