### ISSUE TITLE
Levenshtein approximation for command aliases too

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#1212]
Say you have a command named `info` with the alias `about`, `help inf` will ask if the user meant `info` but `help abou` will say the command wasn't found, I think it should ask if they meant `info` in both cases

**Comment by AriusX7** [comment]
I think instead of `help info`, it should ask if the user meant `help about`. Users might be unaware that `about` is an alias for `info`, so asking them if they meant `help info` might be confusing.

**Comment by Lakelezz** [comment]
I am looking into fixing this.
