### ISSUE TITLE
Add `public_flags` to `User`

### ISSUE THREAD

**Issue by Lakelezz** [serenity-rs/serenity#1220]
The representation of the [User object](https://discord.com/developers/docs/resources/user#user-object-user-structure) is lacking the `public_flags`-field.

**Comment by miqbalrr** [comment]
i'm new in rust or in this project, could i try to take this?

**Comment by Th3-M4jor** [comment]
I'd say it can't hurt to try, and make a PR if you think you can do it.

**Comment by Lakelezz** [comment]
I assigned you, if you need help, feel free to ask here or on our Discord!

**Comment by miqbalrr** [comment]
I Will start it tomorrow

**Comment by miqbalrr** [comment]
start working it

**Comment by Lakelezz** [comment]
Do you need any help with this? Any questions?

**Comment by miqbalrr** [comment]
honestly i have a problem with my condition, i don't even start it. pls give me more time for finishing this weekend

**Comment by Lakelezz** [comment]
No worries! I just wanted to provide help if needed :)

**Comment by miqbalrr** [comment]
thankyou, i will contact you in discord if i have some problems while finishing.

**Comment by Lakelezz** [comment]
Yes, you are more than welcome to do so :)!
