### ISSUE TITLE
simd-json feature flag

### ISSUE THREAD

**Issue by Licenser** [serenity-rs/serenity#1224]
Hi,
we recently started using serenity as in our project. We usually are quite cautious of computational cost and rely on simd accelerated json parsing/rendering. I would love to open a PR to add a feature flag to alow choosing between serde and simd-json but since that'll be quite a bit of work wanted to make sure if that would be a welcome contribution :)?

**Comment by arqunis** [comment]
> if that would be a welcome contribution :)

Yes, it would be. I remember considering to add `simd-json` support to the library a while ago to enhance serialisation/deserialisation performance for those that have SIMD available, but then I forgot about it. I'll gladly merge the pull request once it is open and reviewed.

**Comment by Zaitara** [comment]
This was added in #1237 as mentioned above.
