### ISSUE TITLE
serenity doesn't installed.

### ISSUE THREAD

**Issue by MisileLab** [serenity-rs/serenity#1238]
I trying **cargo install serenity**,
but console said "error: specified package serenity v0.10.2 has no binaries."

**Comment by vicky5124** [comment]
try `cargo add serenity`

`cargo install` is for applications, not for adding libraries to a project.

**Comment by MisileLab** [comment]
it said error: no such subcommand: `add`

**Comment by vicky5124** [comment]
`cargo install cargo-edit` and try again

**Comment by MisileLab** [comment]
Thank you!
