### ISSUE TITLE
Is it possible to test bots without involvement of Discord?

### ISSUE THREAD

**Issue by bartsmykla** [serenity-rs/serenity#1247]
Hi everyone! :-)

I'm playing with serenity and as I'm not proficient with it I would like to involve Discord API as least as possible. Is there any mock/playground mechanism which would let me play and test my bot before using real Discord API?

**Comment by drklee3** [comment]
Hi! I don't think there's a simple way to test serenity bots (and Discord bots in general) against a mock Discord API. I personally just use a secondary bot account to manually test against the Discord API. Do you have a reason why you don't want to use the real Discord API to test your bot?

Relevant issue: #758

**Comment by Mause** [comment]
It is possible to write unit tests, unfortunately, Serenity is built in a way that makes it quite difficult. I ended up having to use a HTTP proxy to mock out the HTTP calls that Serenity makes and was able to partially test it that way, though obviously, the websocket interactions are a bit more difficult.

**Comment by Lakelezz** [comment]
As the Discord API is closed source there is no reliable way to test or mock it. There are some projects in the past trying to achieve this.
Nonetheless, if you want to realiably test your bot, using the real Discord API is the only way.

**Comment by ks129** [comment]
Some other language libraries allow you to provide test entities into cache storage and if you fetch something or do action, then this is using cache instead of real API.

**Comment by Mause** [comment]
That doesn't mean there's no value in being able to write unit tests for certain commands though?

**Comment by Lakelezz** [comment]
This has been merged, I assume it should offer support to this case: #1266 
Hence I will close this issue, unless you are looking for something different.

If you want to test commits, you are able to trigger them manually by maintaining an `Arc` to the framework.
<https://docs.rs/serenity/0.10.5/serenity/client/struct.ClientBuilder.html#method.framework_arc>

**Comment by bartsmykla** [comment]
@Lakelezz thank you for responses, and let's close the issue :-)
