### ISSUE TITLE
No documentation on voice

### ISSUE THREAD

**Issue by SuperCuber** [serenity-rs/serenity#1256]
I searched far and wide and couldn't find any documentation on how to join a voice channel and send audio over it... Seems like something worth improving.

**Comment by Flat** [comment]
From the readme:
> voice: Enables registering a voice plugin to the client, 
> which will handle actual voice connections from Discord. lavalink-rs or Songbird are recommended voice plugins.

https://www.github.com/serenity-rs/songbird/tree/current/examples%2Fserenity%2Fvoice

**Comment by SuperCuber** [comment]
Yep, I found that eventually, but it took me a long while to do it... Maybe there's a better place to put this part?

**Comment by Lakelezz** [comment]
I do think it being on our README.md is sufficient, if you have any suggestions, please inform me.

I will close this in the meantime.
