### ISSUE TITLE
How can a bot react with a unicode character that has several codepoints?

### ISSUE THREAD

**Issue by legendofmiracles** [serenity-rs/serenity#1259]
I want my bot to react to certain messages that are sent outside of #bot with "#bot" but I can't figure out how to react with a `#`. 
It seems that the # emoji is actually 3 unicode characters: `U+23 U+FE0F U+20E3` and thus you can't make it a `char`. 
I also haven't been able to use `ReactionType::Unicode("\u{23}\u{fe0f}\u{20e3}")` to generate the emoji.
Since it's a inbuilt emoji it doesn't have a id that one can use. 

Any help would be appreciated.

**Comment by arqunis** [comment]
To react with the hash emoji in the current version, you will need to provide the percent-encoded string of the emoji to the `Message::react` method, like so:

```rust
use serenity::model::channel::ReactionType;

let ctx: &Context = ...;
let msg: &Message = ...;

msg.react(ctx, ReactionType::Unicode("%23%EF%B8%8F%E2%83%A3".to_string())).await?;
```

Alternatively, you can pull my fix (https://github.com/serenity-rs/serenity/pull/1263) from my fork of Serenity to avoid the percent-encoded string:
```toml
[dependencies.serenity]
git = "https://github.com/acdenisSK/serenity"
branch = "percent_reaction"
```
```rust
use serenity::model::channel::ReactionType;

let ctx: &Context = ...;
let msg: &Message = ...;

msg.react(ctx, ReactionType::Unicode("#️⃣".to_string())).await?;
```

**Comment by legendofmiracles** [comment]
The percent-encoded string works for me.
But I also can't wait for the PR to be merged. 
Thank you for taking matters into your own hands!
I really appreciate it.
