### ISSUE TITLE
Misleading Documentation / Missing Example

### ISSUE THREAD

**Issue by Seppel3210** [serenity-rs/serenity#1280]
The documentation for [CreateEmbed](https://docs.rs/serenity/0.10.5/serenity/builder/struct.CreateEmbed.html) says: "Refer to the documentation for [ChannelId::send_message](https://docs.rs/serenity/0.10.5/serenity/model/id/struct.ChannelId.html#method.send_message) for a very in-depth example on how to use this."
But on the page that is linked there is no example at all! Why did it say "very in-depth"??

**Comment by kangalio** [comment]
This is known in #914

**Comment by Lakelezz** [comment]
Closing as this is a duplicate.
