### ISSUE TITLE
No Stage  Channel Support

### ISSUE THREAD

**Issue by C0D3-M4513R** [serenity-rs/serenity#1292]
Reproduction;
- Add a Stage Cannel to a Server
- Invite the bot to the server:
- Run the bot (and possibly make sure, that the guild is cached)
- Recieve the following warning

```run:recv_event:handle_event{event=Err(Json(Error("unknown ChannelType value: 13", line: 0, column: 0)))}: serenity::gateway::shard: [Shard [0, 1]] Unhandled error: Json(Error("unknown ChannelType value: 13", line: 0, column: 0))```

**Comment by Lakelezz** [comment]
Hello, stage channels are supported as of `v0.10.5`.

**Comment by C0D3-M4513R** [comment]
Ok, so I was missing a `^` in my config. Sorry!

**Comment by nickelc** [comment]
> Ok, so I was missing a `^` in my config. Sorry!

fyi:
> The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement.

see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio
