### ISSUE TITLE
Channel editing fails silently

### ISSUE THREAD

**Issue by clubby789** [serenity-rs/serenity#1297]
Editing a channel can fail even with the required permissions, e.g. if a channel is moved into a category which already has 50 channels inside of it. The API will return the error message `{"parent_id": ["Maximum number of channels in category reached (50)"]}`, but the function will not return an `Err` result, meaning the issue is only noticed manually.

Serenity version: 0.10.5

Rust version (`rustc -V`): 1.51.0

Backtrace (make sure to run `RUST_BACKTRACE=1`): N/A

**Comment by Zaitara** [comment]
I do not see the issue, it works as expected?

**Comment by clubby789** [comment]
Sorry, I miswrote the original issue, now edited. The function does *not* return an `Err`, even when the API responds with an error message.

**Comment by Zaitara** [comment]
I see, can you give a reproducible code?

**Comment by clubby789** [comment]
```rust
#[command]
async fn movechan(ctx: &Context, msg: &Message) -> CommandResult {
    let cat: ChannelId = XXXXXXXXX; // ID of guild text category with 50 channels in it
    msg.channel_id.edit(&ctx.http, |c| c.category(cat)).await?;
    msg.channel_id.say(&ctx.http, "Moved").await?;
    Ok(())
}
```
The 'Moved' message will be printed and the command will return successfully, but the channel category won't change.

**Comment by Zaitara** [comment]
I see, indeed I can reproduce the bug but I get an error saying it can't decode discord error.
![image](https://user-images.githubusercontent.com/23212967/116824100-a9f15700-ab88-11eb-92ab-d29e97796eee.png)

**Comment by clubby789** [comment]
Ah I think when I reported it, the error was dropped silently, since the change you're fixing there seems to have been introduced more recently.

**Comment by Zaitara** [comment]
I see, could you try with this PR to see if it works now?

**Comment by clubby789** [comment]
Hmm, I've built using your fork + branch but the behaviour doesn't seem to have changed. The channel doesn't move and no error is logged.

**Comment by HarmoGlace** [comment]
Well I cannot reproduce, I get the following error : 
![image](https://user-images.githubusercontent.com/23212967/116829533-80debf80-aba4-11eb-9c59-04b4dfeff578.png)

I tried with the following code:
```rust
let cat = ChannelId(838486901438283809);

let edit = ChannelId(838487368340209665)
            .edit(&ctx.http, |c| c.category(cat))
            .await;

dbg!(edit);
```

**Comment by Zaitara** [comment]
I cannot reproduce unfortunately. What are the features you have enabled in serenity (show your Cargo.toml), your intents, your rust version and your operating system?

**Comment by Lakelezz** [comment]
As the issue should be resolved and there is no reply within 2 weeks, I will close this for now.
Please inform us if there are remaining problems and provide enough context to recreate the issue.
