### ISSUE TITLE
Modifying StandardFramework groups at runtime

### ISSUE THREAD

**Issue by NatKarmios** [serenity-rs/serenity#1302]
Are there any examples of using the `group_add()` and `group_remove()` methods of `StandardFramework` to change the commands available at runtime?

I've attempted to do this myself, but I can't seem to get around the memory restrictions.

**Comment by Lakelezz** [comment]
Can you elaborate what sort of errors you are encountering?

**Comment by NatKarmios** [comment]
It's mostly a case of not being sure how to achieve this properly - I'm relatively new to Rust.

Things I tried (and why they failed):
- Retrieving a clone of the `Arc<Box<dyn Framework ...>>` from context data; since the reference this gives isn't mutable, it prevents me from calling the relevant methods
- Wrapping an `Arc<Mutex<Box<StandardFramework>>>` in a new struct (which delegates command invocation to the inner framework after locking), and passing that the same way. This fails because attempting to lock the framework object again in the command that modifies the framework causes a deadlock.

I suppose the problem isn't so much modifying the framework, but more modifying it whilst invoking a command. Perhaps a fire-and-forget approach inside command invokation could work.

**Comment by NatKarmios** [comment]
Ok, I've found a way to get around the deadlock in my latter case:
- Copy the context and message with `.clone()`
- Modify the framework inside a `task::spawn` with an `async move` function

This was mostly a matter of understanding Rust's memory management it works now! Sorry for the false alarm.
