### ISSUE TITLE
Error running example codes.

### ISSUE THREAD

**Issue by luquinhas8551** [serenity-rs/serenity#1316]
Hello community, i have a problem when i try to run an example bot. The error is: "thread 'main' panicked at 'Expected a token in the environment: NotPresent', src\main.rs:33:89 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
Line 33: let token = env::var("TOKEN").expect("Expected a token in the environment");

Please if anyone knows how to fix, help me.

**Comment by arqunis** [comment]
`env::var("TOKEN")` means to retrieve the value of the environment variable called `TOKEN`. The error explains that this operation is not possible, as the environment variable does not exist. What is your operating system? Configuring environment variables highly depends on the OS.

**Comment by luquinhas8551** [comment]
> `env::var("TOKEN")` means to retrieve the value of the environment variable called `TOKEN`. The error explains that this operation is not possible, as the environment variable does not exist. What is your operating system? Configuring environment variables highly depends on the OS.

Ohh, im using windows 10.

**Comment by arqunis** [comment]
[This website](https://www.alphr.com/environment-variables-windows-10/) shows a thorough guide of setting an environment variable on Windows 10 graphically, though this is a permanent solution until you delete the environment variable. If you wish to set an environment variable just for the current session in a terminal, you can perform either `set <VARIABLE_NAME>=<VALUE>` if you are using cmd or Command Prompt, or `$env:<VARIABLE_NAME>=<VALUE>` if you are using PowerShell. This will make the variable available for subsequent commands, including those where you run your bot.

**Comment by Lakelezz** [comment]
I hope Denis was able to help you!
If there are any other problems, please inform us!

As this question seems to be answered, I will close this issue.
