### ISSUE TITLE
Closing the Bot

### ISSUE THREAD

**Issue by Selyatin** [serenity-rs/serenity#1318]
How can I close the bot manually? 

When I start the client, it'll enter a loop on it's own and I don't see a way to stop the bot manually without terminating the program.

 Any help?

**Comment by arqunis** [comment]
To close your bot, you need to shutdown all of its shards, [which you can do with the `ShardManager`](https://serenity-rs.github.io/serenity/current/serenity/client/bridge/gateway/struct.ShardManager.html#method.shutdown_all). The manager can be [accessed from the `Client`](https://serenity-rs.github.io/serenity/current/serenity/client/struct.Client.html#structfield.shard_manager), which you can safely `clone()` and pass around wherever you need it. [Example 6 shows](https://github.com/serenity-rs/serenity/blob/current/examples/e06_sample_bot_structure/src/main.rs#L43) [how to use](https://github.com/serenity-rs/serenity/blob/current/examples/e06_sample_bot_structure/src/main.rs#L112-L115) [the manager in a command](https://github.com/serenity-rs/serenity/blob/current/examples/e06_sample_bot_structure/src/commands/owner.rs#L11-L26) by using the `data` field of the `Client`.

**Comment by Selyatin** [comment]
Thanks
