### ISSUE TITLE
Redesign Parse trait

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#1327]
The Parse trait which I recently contributed (#1235) has a not-very-well thought out API and several shortcomings as a result:
- The `msg: Message` is always required even when the parse code doesn't need it
  - For example the message URL parser inside the Parse impl for Message does not need the Message parameter, but it cannot be invoked without it ([thread on serenity discord](https://discord.com/channels/381880193251409931/381912587505500160/840689396406812713))
- It's unusable for slash commands because those only carry a channel and maybe guild ID, but no message ID
- I'm also personally kind of unhappy about the name "Parse" because the trait does more than parsing; it also does network requests and detects the format

To address the first concern, all non-trivial parsing functions could be extracted from within the Parse implementations into their own free-standing functions, like the existing `serenity::utils::parse_XXX` methods.

To address the second concern, the trait function signature could be changed from `ctx: &Context, msg: &Message, s: &str` to `ctx: &Context, channel: ChannelId, guild: Option<GuildId>, s: &str`. Those are a lot of parameters though, maybe something can be improved still about that signature.

To address the third concern, we'd need some other name. `Extract`, `ParseAndRetrieve`, `Convert`, `ArgumentConvert`?

EDIT: changed `GuildId` to `Option<GuildId>` and added `ArgumentConvert` as per Arius' suggestions

**Comment by AriusX7** [comment]
The guild parameter would need to be an `Option<GuildId>` as commands can also be used in DMs.

I like `Convert` the best of these options, but personally I'd prefer something like `ArgumentConverter` as it's more precise.

**Comment by kangalio** [comment]
The corresponding PR is now merged in current and next
