### ISSUE TITLE
Message::link returns broken links

### ISSUE THREAD

**Issue by elkowar** [serenity-rs/serenity#1331]
Sometimes (but apparently not always), using `Message::link` doesn't give me the expected `<serverid>/<channelid>/<messageid>` link, but instead generates a link of the form `@me/<channelid>/<messageid>`. That broken link then still links to the right channel and message, but makes discord open it in the DM window (which is also weird behaviour from discords side, but still also a broken link from serenity.

# Expected behaviour
`Message::link()` consistently gives me a valid link to the message

# Current behaviour
`Message::link()` in some circumstances returns a link that contains `@me` where the server-id should be (even when the message i'm linking to _is_ in a server)

**Comment by Zaitara** [comment]
It seems to be because discord does not send the `guild_id` field if the message is not received through the gateway.

**Comment by elkowar** [comment]
Is it still possible to identify if the message is in a guild or not? (as in, is it possible to work around that by manually fetching that somehow)? If a workaround is possible, I'd be more than happy to look into doing a PR :P

**Comment by Zaitara** [comment]
I'll see, the library could check in the channels cache (if the feature is enabled), but it is the best we can do as the `guild_id` is needed to have a guild message link. Getting the channel would help in this case

**Comment by elkowar** [comment]
sounds good 👍🏻

**Comment by elkowar** [comment]
alternatively is there a `Guild::link_to_messsage` or sth that one could use to explicitly make sure a guild is always known?
