### ISSUE TITLE
Missing Activity::custom method

### ISSUE THREAD

**Issue by Tarinu** [serenity-rs/serenity#1346]
I wanted to set a custom activity on my bot and noticed that the method for creating one is missing, all the other ActivityTypes have a corresponding method under Activity implementation. As far as I know, I can't create the Activity instance myself either since it's marked as `non_exhaustive`. Is there a reason why it's missing or is it just an oversight?

Serenity version: 0.10.7

**Comment by Zaitara** [comment]
It is not possible for bots to set a custom activity currently. You can make a feature request to discord at https://github.com/discord/discord-api-docs

**Comment by Tarinu** [comment]
Thanks for answering, I wasn't aware it's not supported yet. I assumed since Custom ActivityType is documented in Discord's developer docs, it's also supported by their API. My bad.

Should I keep the issue open since technically it's still missing?

**Comment by Zaitara** [comment]
Their documentation is not only for bots, here it is for rpc only, you should close this issue
