### ISSUE TITLE
guild_member_removal event not firing

### ISSUE THREAD

**Issue by Selyatin** [serenity-rs/serenity#1363]
Hey guys, I'm trying to make **guild_member_removal** event handler work, but it's not firing for some reason.

I've enabled all **Privileged Gateway Intents**, but for some reason it's still not firing at all.

Any help?

**Comment by drklee3** [comment]
Do you have the `GUILD_MEMBERS` intent enabled in the serenity client too? 

Example how to set the intent:

https://github.com/serenity-rs/serenity/blob/22d2276dc31e25ef0680668aab7cb52b6692a06f/examples/e11_gateway_intents/src/main.rs#L40

If you already have it set, can you show your code?

**Comment by Selyatin** [comment]
Thanks, after setting the intents it started working properly!
