### ISSUE TITLE
Permission READ_MESSAGES should mention the new name READ_MESSAGES (and be renamed in next)

### ISSUE THREAD

**Issue by elkowar** [serenity-rs/serenity#1366]
The `Permissions` type does not currently seem to expose all the available permissions specified by the discord api at [Bitwise permission flags](https://discord.com/channels/734101524438974504/815594209939292161/846832461249642507). For example, VIEW_CHANNEL seems to be missing. These should be added.

**Comment by Zaitara** [comment]
Every permission seems to be supported, the `VIEW_CHANNEL` is named `READ_MESSAGES` (before that discord decided to rename it).

**Comment by elkowar** [comment]
Ohhhhhhh, okay, then nevermind! Would probably still be worthwhile to mention this in the documentation 👀

**Comment by Zaitara** [comment]
Yes, it should be specified in the `current` documentation and fully renamed in the `next` version, feel free to open a PR

**Comment by nickelc** [comment]
Fixed with the release of serenity `v0.11`.
