### ISSUE TITLE
Member add_role not working - Missing Permission

### ISSUE THREAD

**Issue by Selyatin** [serenity-rs/serenity#1370]
I'm getting `Missing Permission` error when I'm trying to add a role to a member.

I've these intents enabled:

```rust
 let mut client = match Client::builder(&bot_options.token)
            .event_handler(Handler::new(bot_options, info_sender, info_trigger_receiver, db))
            .intents(GatewayIntents::GUILDS | GatewayIntents::GUILD_MEMBERS | GatewayIntents::GUILD_MESSAGES)
            .await {
            Ok(client) => client,
            Err(err) => return Err(err.to_string())
        };
```

I've also invited the bot with administrator permissions, so what might be the issue here?

**Comment by drklee3** [comment]
Is the bot's highest role above the role you are trying to add to a member?

**Comment by Selyatin** [comment]
The bot doesn't have any roles assigned other than it's own self-assigned role

**Comment by Selyatin** [comment]
<img width="292" alt="Screenshot 2021-06-01 at 6 40 03" src="https://user-images.githubusercontent.com/50295732/120263358-3421fd80-c2a4-11eb-9bd9-1932288783c5.png">

**Comment by LuckShiba** [comment]
Is the bot's role (the one named `SelfBot`) position higher than the top role of the user trying to add the role?

**Comment by Selyatin** [comment]
Ah, after moving the `SelfBot` role to the highest position in the server settings it started working, thanks a lot!
