### ISSUE TITLE
How to create guild scoped slash command?

### ISSUE THREAD

**Issue by lukasdiegelmann** [serenity-rs/serenity#1372]
Hey, I am currently trying to get a discord bot with the **Slash Command API** running, but I have encountered a problem. I do not know how to create a guild scoped command (done with following API endpoint: `https://discord.com/api/v8/applications/<my_application_id>/guilds/<guild_id>/commands`). I looked at the `ApplicationCommand` type, but it just implements methods dedicated to global application commands and a `ApplicationCommand::build_application_command` method, which does not have documentation.

Help is very much appreciated!

**Comment by Zaitara** [comment]
The method is on a `GuildId`, see https://serenity-rs.github.io/serenity/current/serenity/model/id/struct.GuildId.html#method.create_application_command
