### ISSUE TITLE
Remove trivial dispatch errors (like OnlyForDM) in favour of manually written checks

### ISSUE THREAD

**Issue by acdenisSK** [serenity-rs/serenity#141]
This idea came from @fwrs.
cc @zeyla, opinions?

**Comment by zeyla** [comment]
This should be able to be part of #60, I have an idea for handling it but haven't finished the design enough yet to describe it. If not a part of closing #60, this should block on it before design is laid out.

**Comment by Caemor** [comment]
What is the reason for removing these dispatch errors?

**Comment by Lakelezz** [comment]
@acdenisSK changed their mind, let's close it : )
