### ISSUE TITLE
`validate_token` does not validate a valid token

### ISSUE THREAD

**Issue by Chronophylos** [serenity-rs/serenity#1432]
The last part of my token does not parse as base64.
I tried to parse it with the GNU command `base64` but it produces a couple of bytes and the error `invalid input`.
The token works, I can use it without problems.

**Comment by kangalio** [comment]
This was probably fixed by #1387, which is not yet published on crates.io. The base64 decoding was using the wrong charset in one place (sorry!)

**Comment by Chronophylos** [comment]
That explains that.

I'll close the issue since it is fixed
