### ISSUE TITLE
`Message::is_private` is incorrect for messages acquired over HTTP API

### ISSUE THREAD

**Issue by sbrocket** [serenity-rs/serenity#1439]
`Message::is_private` just checks whether `guild_id` is `None`, which causes it to be incorrect for messages from the HTTP APIs since `guild_id` is only returned for messages received over the gateway. Besides the fact that `is_private` is incorrect, which could be documented like `guild_id`, this confuses methods like `Message::delete` which check `is_private` to save HTTP requests when the cache is enabled.

There's a simple/dumb workaround if you know that the message is from a guild channel - you can just `msg.guild_id = Some(GuildId(1));` before using `delete` - but obviously that's not very pretty.

**Comment by NotNorom** [comment]
I've run into the same issues when trying to delete messages in bulk. My current workaround is to use &ctx.http, bypassing the cache whenever I need to make a delete call.

**Comment by kangalio** [comment]
For the underlying issue, see #832

**Comment by kangalio** [comment]
Fixed as far as we can in #2151, this issue can be closed
