### ISSUE TITLE
ClientBuider::framework_arc takes Arc<Box<...>>

### ISSUE THREAD

**Issue by Seppel3210** [serenity-rs/serenity#1443]
Taking a Box inside an Arc is redundant, because the Arc already allocates and allows for unsized types.

https://docs.rs/serenity/0.10.8/serenity/client/struct.ClientBuilder.html#method.framework_arc

**Comment by arqunis** [comment]
This is [already resolved on the `next` branch](https://github.com/serenity-rs/serenity/blob/next/src/client/mod.rs#L233-L241). The same hasn't been done on the `current` branch because it would be a breaking change.
