### ISSUE TITLE
msg.channel does not work in threads

### ISSUE THREAD

**Issue by kingbri1** [serenity-rs/serenity#1452]
With threads, the `msg.channel()` method causes the bot to panic and the command to not execute.

However, `msg.channel_id.to_channel()` works fine.

**Comment by kangalio** [comment]
In my testing `msg.channel()` does not panic with threads, it merely returns None. That is because it only looks up in the cache, and doesn't fall back to an HTTP request like `msg.channel_id.to_channel()` does.

**Comment by kingbri1** [comment]
Closing bcoz PR was already merged
