### ISSUE TITLE
command attibute macro on group attribute macro can't correctly parse when the commands are defined in another module

### ISSUE THREAD

**Issue by Xephobia** [serenity-rs/serenity#1453]
let's say this code 
```rust
#[command]
#[description = "generates a random 8 bit unsigned number"]
async fn r#u8(ctx: &Context, msg: &Message) -> CommandResult {
    msg.reply(ctx, rand::random::<u8>()).await?;
    Ok(())
}
```
present in `commands/random.rs`, if I create the group in the upper module file, `command.rs`, it fails with two errors :
```rust
error: the path must not have more than one segment
  --> src/commands.rs:37:12
   |
37 | #[commands(random::r#u8)]
   |            ^^^^^^

```
this one can be avoided by `use`ing the module globally (`use random::*;`), which is not desirable at certain times, but then another issue arise :
```rust
error: custom attribute panicked
  --> src/commands.rs:36:1
   |
36 | #[group]
   | ^^^^^^^^
   |
   = help: message: `"r#u8"` is not a valid identifier
```
I'm not sure if it's linked, but it's still two errors in macro expansion.

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
