### ISSUE TITLE
Documentation Page Not Found

### ISSUE THREAD

**Issue by nimit2801** [serenity-rs/serenity#1455]
Serenity version: current

Rust version (`rustc -V`): NA

Backtrace (make sure to run `RUST_BACKTRACE=1`): NA

Minimal test case if possible: NA

The Documentation page: https://serenity-rs.github.io/serenity/ says 404 Page Not Found
![image](https://user-images.githubusercontent.com/53462249/127729562-4ff3563e-b7a7-4b23-af0b-ff414740214a.png)

**Comment by HTGAzureX1212** [comment]
`docs.rs` exists for a reason for now: https://docs.rs/serenity/0.10.8/serenity/

You don't have to *always* use the GitHub pages documentation do ya?

(`unsafe`ly assuming that the GitHub Pages thing is the documentation.)

**Comment by HTGAzureX1212** [comment]
Just checked: that GitHub Pages thing you tried to access simply redirects you back to this repository.

**Comment by AriusX7** [comment]
You need to use a more specific link. https://serenity-rs.github.io/serenity/current/serenity/index.html works.

**Comment by nimit2801** [comment]
> 
> 
> You need to use a more specific link. https://serenity-rs.github.io/serenity/current/serenity/index.html works.

Can we change the link in the description of the repo then, it would send users to the right page?
Thanks for the direct link

**Comment by nimit2801** [comment]
So I'm currently working on Oauth, so I have an idea we can implement google Oauth or use firebase authentication for the same, since the whole UI is developed using HTML/vanilla js. But eventually, we have to then increase security :D

**Comment by kangalio** [comment]
We can also put a redirection HTML at serenity-rs.github.io/serenity like I do in poise: https://github.com/kangalioo/poise/blob/gh-pages/index.html

**Comment by nimit2801** [comment]
> 

I think this is a good solution!

> We can also put a redirection HTML at serenity-rs.github.io/serenity like I do in poise: https://github.com/kangalioo/poise/blob/gh-pages/index.html

**Comment by kangalio** [comment]
This issue can be closed
