### ISSUE TITLE
Audit log parsing fails

### ISSUE THREAD

**Issue by j2ghz** [serenity-rs/serenity#1466]
It seems discord has added new audit log models (83..112), and the parsing function returns an error:
https://github.com/serenity-rs/serenity/blob/b2565da364dc7c50b10d9991968cb286d17a4f6d/src/model/guild/audit_log.rs#L380-L381
```rust
Http(Request(reqwest::Error { kind: Decode, source: Error("Unexpected action number: 111", line: 1, column: 318) }))
```
Regardless of updating it, would it make sense to change it to return UnkownAuditLogEntry for unknown numbers? To contain the original json, similarly to how Event and EventHandler handle unkown events.

**Comment by nickelc** [comment]
Fixed by #1875
