### ISSUE TITLE
Different type when creating a channel versus when getting channel information

### ISSUE THREAD

**Issue by Chronophylos** [serenity-rs/serenity#1484]
When creating a channel with [`CreateChannel::bitrate`](https://docs.rs/serenity/0.10.9/serenity/builder/struct.CreateChannel.html#method.bitrate) the argument is a `u32`. When getting the bitrate from a guild channel it is `u64` see [here](https://docs.rs/serenity/0.10.9/serenity/model/channel/struct.GuildChannel.html#structfield.bitrate). When editing a channel the required argument is a `u64` see [`EditChannel::bitrate`](https://docs.rs/serenity/0.10.9/serenity/builder/struct.EditChannel.html#method.bitrate).

The same problem exists for [`CreateChannel::user_limit`](https://docs.rs/serenity/0.10.9/serenity/builder/struct.CreateChannel.html#method.user_limit) and [`CreateChannel::position`](https://docs.rs/serenity/0.10.9/serenity/builder/struct.CreateChannel.html#method.position).

Another thing I noticed is the different names of [`slow_mode_rate`](https://docs.rs/serenity/0.10.9/serenity/model/channel/struct.GuildChannel.html#structfield.slow_mode_rate) and [`CreateChannel::rate_limit`](https://docs.rs/serenity/0.10.9/serenity/builder/struct.CreateChannel.html#method.rate_limit)

**Comment by kangalio** [comment]
The slow_mode_rate and rate_limit thing was fixed in #1680
