### ISSUE TITLE
Outdated permission name

### ISSUE THREAD

**Issue by woongzeyi** [serenity-rs/serenity#1486]
Discord has changed its permission names since, but Serenity is still having the old permission names, which can be quite confusing for developers referencing `Permissions` from [Discord's developer documentation](https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags).
https://github.com/serenity-rs/serenity/blob/7392f3f237e3126fc1fa5affbd1359e1984da799/src/model/permissions.rs#L217-L329
An update on those permission names is highly needed, but it can be a breaking change and will need deprecations.

**Comment by Zaitara** [comment]
Could you please provide which permissions names are outdated? IIRC they are all renamed on `next`

**Comment by woongzeyi** [comment]
Here's an absolute difference between Discord's documentation and Serenity's Permission model on `next`: 
(Positional difference is ALSO included)
```diff
- CREATE_INVITE 
+ CREATE_INSTANT_INVITE
  KICK_MEMBERS
  BAN_MEMBERS
  ADMINISTRATOR
  MANAGE_CHANNELS
  MANAGE_GUILD
  ADD_REACTIONS
  VIEW_AUDIT_LOG
  PRIORITY_SPEAKER
  STREAM
- READ_MESSAGES
+ VIEW_CHANNEL
  SEND_MESSAGES
  SEND_TTS_MESSAGES
  MANAGE_MESSAGES
  EMBED_LINKS
  ATTACH_FILES
  READ_MESSAGE_HISTORY
  MENTION_EVERYONE
  USE_EXTERNAL_EMOJIS
+ VIEW_GUILD_INSIGHTS
  CONNECT
  SPEAK
  MUTE_MEMBERS
  DEAFEN_MEMBERS
  MOVE_MEMBERS
  USE_VAD
  CHANGE_NICKNAME
  MANAGE_NICKNAMES
  MANAGE_ROLES
  MANAGE_WEBHOOKS
  MANAGE_EMOJIS_AND_STICKERS
- REQUEST_TO_SPEAK
- USE_SLASH_COMMANDS
+ USE_APPLICATION_COMMANDS
+ REQUEST_TO_SPEAK
  MANAGE_THREADS
  USE_PUBLIC_THREADS
  USE_PRIVATE_THREADS
  USE_EXTERNAL_STICKERS
```
You can see here that there are 3 permission names which are outdated (is not exactly the same as Discord's), and 1 missing permission (and 1 mispositioned permission but okay).
