### ISSUE TITLE
Message components support?

### ISSUE THREAD

**Issue by anchpop** [serenity-rs/serenity#1487]
Message components are a recent feature, curious what the support status is. A list of supported features in the readme would be really nice - I see message components in the [docs](https://docs.rs/serenity/0.10.9/serenity/model/interactions/message_component/enum.Component.html) but they don't have an example I don't think so I'm not sure if they're still being developed or if they're really supported.

**Comment by vicky5124** [comment]
If the feature is documented, it is supported by the library. To send a component, you need to build them on `.send_message()`, the usage of this method is shown in example 9 (create message builder), and to react to the component interactions, you can use the collector system, which is shown in example 10 (collectors)

Generally, this library implements new features really fast, and PRs are tried to be made before the feature releases, when possible, if some member has access to the new feature before the maintainers of the library, like it was recently the case with #1460

**Comment by anchpop** [comment]
Thank you!
