### ISSUE TITLE
Incorrect docs for `edit_original_interaction_response()`

### ISSUE THREAD

**Issue by Th3-M4jor** [serenity-rs/serenity#1492]
For both `MessageComponentInteraction` and `ApplicationCommandInteraction` the docs for `edit_original_interaction_response` say that it doesn't work on ephemeral messages, this should actually be moved one function down to the method for deleting.

Tested it myself and you can edit ephemeral messages, it is deleting them that you cannot do.

**Comment by kangalio** [comment]
Oh you can't delete ephemeral responses? I thought I had done that before

EDIT: I was mistaken
