### ISSUE TITLE
Only spawn a thread in the event handler if there is a function for it

### ISSUE THREAD

**Issue by Milo123459** [serenity-rs/serenity#1505]
My bot doesn't have a function for the message event in the event handler, however, a thread is still spawned whenever the event is emitted. Is there a way to make sure it only emits and creates a new thread *if* the function for that event is in the event handler?

**Comment by arqunis** [comment]
> Is there a way to make sure it only emits and creates a new thread *if* the function for that event is in the event handler?

There is not, unfortunately. The event handler is simply just a trait. We cannot differentiate whether a function of a trait has been overridden by an `impl`ementor, or the default implementation has been chosen instead. As an alternative, [you could disable the `GUILD_MESSAGES` intent][GUILD_MESSAGES] to avoid receiving events related to messages (such as `MESSAGE_CREATE`). Thus, no tasks/threads will be spawned for those events. 

[GUILD_MESSAGES]: https://serenity-rs.github.io/serenity/current/serenity/client/bridge/gateway/struct.GatewayIntents.html#associatedconstant.GUILD_MESSAGES

**Comment by Milo123459** [comment]
Oh right, that makes sense
