### ISSUE TITLE
Ratelimiting is not checked when sending messages with files

### ISSUE THREAD

**Issue by DeboMac** [serenity-rs/serenity#1506]
Hello,

Calling Http::send_files does not check the ratelimiting, it just performs a basic post reqwest.
On the opposite, Http::send_message calls Http::fire, and thus checks the ratelimiting. 
Both methods are being called in ChannelId::send_message, so it is a bit misleading to have one request where ratelimiting is managed by serenity, and the other one where it's not.

Thank you very much for the great crate !

**Comment by DeboMac** [comment]
For anyone having the same issue, my current workaround is to use the crate "multipart" to get the data of the body, like this:

```
let mut multipart = multipart::client::lazy::Multipart::new();
multipart.add_stream("file", std::io::Cursor::new(data), Some("filename"), mime::Mime::from_str("application/octet-stream").ok());
let multipart = multipart.prepare().unwrap();
```
Then manually building the content-type header, and instantiate a RequestBuilder (from serenity):
```
    let mut request_builder = serenity::http::request::RequestBuilder::new(RouteInfo::CreateMessage {
        channel_id: channel.0,
    });
    let mut headers = HeaderMap::new();
    headers.insert(reqwest::header::CONTENT_TYPE, reqwest::header::HeaderValue::from_str(format!("multipart/form-data; boundary={}", multipart.boundary()).as_str()).unwrap());
    request_builder.headers(Some(headers));
```
Finally, add the body to the request builder and fire the request:

```
let data: Vec<u8> = multipart.bytes().filter_map(Result::ok).collect();
request_builder.body(Some(data.as_slice()));

let request = request_builder.build();
let message = client.fire::<serenity::model::prelude::Message>(request).await.unwrap();
```
Fire uses the ratelimiter, so you should be fine with this !

(note that I am not adding any text with my file, but this could certainly be done with multipart.add_text)

**Comment by arqunis** [comment]
This is a troubling issue indeed. However, the fix is [already present on the `next` branch](https://github.com/serenity-rs/serenity/blob/next/src/http/client.rs#L3427-L3449), and I suggest depending on it instead of this workaround. It would be nice if the fix could be backported to `current`, but that would involve including a necessary breaking change, which is forbidden on the `current` branch.
