### ISSUE TITLE
Add an example for message components

### ISSUE THREAD

**Issue by berzi** [serenity-rs/serenity#1509]
We could use an example on how to use message components like action rows, select menus etc, since they're a rather new feature which people are likely to be interested in, and how they work and are structured can be confusing. I'm still learning serenity myself so I don't feel confident writing an example myself just yet.

**Comment by Milo123459** [comment]
Hmm. Would it use something like a collector, or listen for the interaction_create event? I'm happy to implement this, and it probably makes sense to do both.

**Comment by berzi** [comment]
Ideally, all features should be covered by at least an example, right?

Although personally what I find most practical as a developer is seeing small, focussed examples in the documentation of the functions themselves. Those should be easier to make and could inspire the more complete, stand-alone ones.

I will likely start to help out myself on this once I feel confident enough.

**Comment by Milo123459** [comment]
> Ideally, all features should be covered by at least an example, right?

Not at all. IMHO it makes more sense to split them out.

I'll contribute this soon.

**Comment by ghost** [comment]
I am working on a bot with this feature. I can try to contribute to this. I'm using the interaction inside the EventHandler. so I can add an example to this repo when I'm done experimenting with this.

**Comment by vicky5124** [comment]
Components example should be included on the `collectors` example, as otherwise they are not that useful, and it wouldn't really show anything new.
