### ISSUE TITLE
Basic example e01_basic_ping_bot

### ISSUE THREAD

**Issue by gloatoriginal** [serenity-rs/serenity#1512]
I'm currently trying to start the base example and am constantly met with token "NotPresent" Even though I have copied my discord bot token into the token location in the base example where it says "DISCORD_TOKEN". Any help would be appreciated.

**Comment by drklee3** [comment]
If you are replacing "DISCORD_TOKEN" within the actual rust file, it would be trying to load the environment variable with the *name/key* of your actual token which isn't really what you want to do.

The examples get the token from environment variables so you will need to set the environement variable `DISCORD_TOKEN` to your token. 

For example if you are using an unix-like system you can run it with the cargo command.

`DISCORD_TOKEN="yourtoken" cargo run`

You can also use something like [dotenv](https://crates.io/crates/dotenv) to store `DISCORD_TOKEN="yourtoken"` in an .env file.

**Comment by gloatoriginal** [comment]
Awesome, thank you so much, I feel like a dunce.
