### ISSUE TITLE
Bug in error-reporting when using command framework

### ISSUE THREAD

**Issue by elkowar** [serenity-rs/serenity#1520]
When writing a command using the command macros, I encountered a broken error-message from the borrow checker, that only happens when using these macros. I created a small example repo to show the effect under https://github.com/elkowar/serenity-bug-report.

![image](https://user-images.githubusercontent.com/5300871/135416342-9ae4963c-f20c-4b20-a425-ccaaff5e761f.png)

Concretely, the error message mentions the lifetime `'fut` on `ctx`, which is however already properly cloned. The error is correctly resolved by also cloning `msg`, unlike the error message suggests. Removing the `#[command]` attribute fixes the compiler error.

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
