### ISSUE TITLE
Sub commands searched in help without command base name

### ISSUE THREAD

**Issue by JSH32** [serenity-rs/serenity#1532]
If you invoke help command using the framework with a subcommand like `.help add` with add being a subcommand to any other command it will show the first match. The intended behavior is `.help command add` showing the help because there might be two subcommands with the same name.

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
