### ISSUE TITLE
Remove redundant guild ID parameter from several EventHandler methods

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#1540]
The Member parameter of guild_member_addition already contains the guild ID, so the guild ID parameter on guild_member_addition is redundant.

Similarly, the VoiceState parameter of voice_state_update already contains the guild ID, so the guild ID parameter on voice_state_update is redundant.

**Comment by vicky5124** [comment]
Same issue with `guild_role_create`, `guild_role_update` and `guild_stickers_update`, where guild_id is available on `Role` and `Sticker`
