### ISSUE TITLE
Support "Curly Quotes" for `Args.quoted`

### ISSUE THREAD

**Issue by dfontana** [serenity-rs/serenity#1545]
### Overview
Users on Mavericks+ Apple platforms (eg iOS) by default have their quote keys input "Curly Quotes" rather than straight quotes (also known as "Smart Quotes" or "Smart Punctuation"). This causes arguments to fail parsing, as it appears [lexing checks against straight quotes only](https://docs.rs/serenity/0.10.9/src/serenity/framework/standard/args.rs.html#106-133). While users could be asked to [change their defaults](https://apple.stackexchange.com/questions/136402/how-to-disable-smart-quotes), it's an abrasive experience that they may not wish to endeavor; and - at least on iOS - is a global setting they may not wish to change for this one use case.

### Details

These Curly quotes appear to be [unicode characters](https://unicode-table.com/en/sets/quotation-marks/) `201C` and `201D`.

**Potential Solves**

- Bot owners could check themselves, and alert the user -- [kinda like the rust compiler](https://github.com/rust-lang/rust/issues/58436). This won't be very graceful, however, and would probably introduce some complexity around argument count validation when using the macros.
- Args could be standardized to replace various known quote shapes with their straight line forms before passed into lexing, but this may have unintended consequences.
- The lexer function (linked earlier) could check for multiple quote styles; the major downsides being if these quotes were intermixed it could be tricky to get right. It might be fair to assume the two types would not be mixed (as so: `"The “lazy” fox"`) or perhaps the first quote encountered can govern the style for the remainder of lexing.

Thoughts? I stumbled upon this in a guild with some friends, some of which use iPhone and others Android; some of whom are very not technical and it took some explaining to rectify what happened. But it's an annoying experience.

**Comment by arqunis** [comment]
I have opened https://github.com/serenity-rs/serenity/pull/1553, which I have implemented per your third solution. Could you try it yourself if it works for your users? I have tested it myself by manually copying (I don't own an Apple device) the curly quote characters into an argument, which with my PR work the same as `"`.

**Comment by dfontana** [comment]
Oh awesome! I will gladly get this booted and test it, will report back

**Comment by dfontana** [comment]
Happy to report your branch does the trick 🎉 I was able to test on my iPad which has smart quotes, see image below inside the spoiler 😄 Thank you for this!

<details>
    <summary>Image of Both </summary>
<img width="834" alt="QuotesWork" src="https://user-images.githubusercontent.com/15203135/137594489-b0b678f2-ac86-4c0e-a626-c58c9ceb5858.png"/>
</details>
