### ISSUE TITLE
`Webhook::edit` avatar parameter different from `create_webhook_with_avatar`

### ISSUE THREAD

**Issue by JellyWX** [serenity-rs/serenity#1547]
The type of `avatar` on `Webhook::edit` is of `Option<&str>`, whereas on `create_webhook_with_avatar`, it is `AttachmentType`. 

Surely these should be the same type? It would nevertheless be useful to be able to edit a webhook's avatar by using the `AttachmentType` instead of just a string

**Comment by mkrasnitski** [comment]
With #1652 now merged into the `next` branch, this problem has been addressed. You can now call `Webhook::edit_avatar`, which takes an `Into<AttachmentType>`, or additionally call `delete_avatar`.
