### ISSUE TITLE
Confusion about no prefix functionality

### ISSUE THREAD

**Issue by Stef16Robbe** [serenity-rs/serenity#1574]
The [prefix docs](https://docs.rs/serenity/0.10.9/serenity/framework/standard/struct.Configuration.html#method.prefix) say the following about having no prefix command character:

`Note: Passing empty string "" will set no prefix.`

To my understanding this means that commands will be executed without using a prefix, e.g:

```
let framework = StandardFramework::new()
        .configure(|c| c.prefix("")) // set the bot's command prefix
        .group(&GENERAL_GROUP);
```
would achieve:

![image](https://user-images.githubusercontent.com/43065653/141490928-ef4c3f6d-e8b1-4f94-a62a-ed7f9c280f66.png)

Should it work like this? Currently it does not, nothing happens using the ping pong example of this repo.
If it shouldn't work like this, how would I achieve this result?

**Comment by arqunis** [comment]
> To my understanding this means that commands will be executed without using a prefix

No, what the note is saying that by passing `""` into `Framework::prefix` will [reset the list of prefixes][list] the framework will use to distinguish commands from normal messages.

If you wish to be able to invoke commands without a prefix, there are two solutions:

- Set [`Configuration::no_dm_prefix`][no_dm] to true -- if you would like to invoke commands in DMs without a prefix, but keep them everywhere else (i.e. guilds), then this option will allow that.
- Set [`Configuration::prefixes`][prefixes] with `""` -- unlike `Configuration::prefix`, this will not reset the list of prefixes, at least on the `v0.10.9` release. On `current` (and `next`), it has been fixed. If you are depending on Serenity from git, then the only solution will be to push `""` into [`Configuration::prefixes`][prefixes_field], a hidden, but accessible field.

[list]: https://docs.rs/serenity/0.10.9/src/serenity/framework/standard/configuration.rs.html#462
[no_dm]: https://docs.rs/serenity/0.10.9/serenity/framework/standard/struct.Configuration.html#method.no_dm_prefix
[prefixes]: https://docs.rs/serenity/0.10.9/serenity/framework/standard/struct.Configuration.html#method.prefixes
[prefixes_field]: https://github.com/serenity-rs/serenity/blob/current/src/framework/standard/configuration.rs#L129

**Comment by kangalio** [comment]
Can this issue be closed?

**Comment by your-diary** [comment]
Today I just encountered the exactly same question as the OP.

- I think the documentation is poorly worded.

- Do I still have to stick to this workaround after 2 years?

    > *If you are depending on Serenity from git, then the only solution will be to push "" into [Configuration::prefixes](https://github.com/serenity-rs/serenity/blob/current/src/framework/standard/configuration.rs#L129), a hidden, but accessible field.*

    ```rust
    let framework = StandardFramework::new()
        .configure(|c| {
            c.prefixes.push("".to_owned());
            c
        })
        .group(&GENERAL_GROUP);
    ```
    
    If so,

    - The workaround should be documented anywhere. (I'm sorry if it is documented already.)
    - `Configuration::prefixes` shouldn't be hidden.

    (But..., is setting no prefix so rare to justify not exposing an official way (rather than a workaround)? I've created many Discord bot in many languages and I've never wanted to set prefixes (maybe because my bots are deployed to a server with the small number of members).)

---

### How did I find this issue?

As a beginner for this crate, I first read the example shown in `README.md`:

```rust
    let framework = StandardFramework::new()
        .configure(|c| c.prefix("~")) // set the bot's prefix to "~"
        .group(&GENERAL_GROUP);
```

The comment suggests `c.prefix()` sets the bot's prefix, so I removed the call of `.configure()`, but my bot didn't work.

So I visited the official documentation of [`Configuration::prefix`](https://docs.rs/serenity/0.11.6/serenity/framework/standard/struct.Configuration.html#method.prefix) and it says

> Passing empty string `""` will set no prefix.

Then I tried `c.prefix("")` to no avail.

**Comment by your-diary** [comment]
Ah, it seems [examples/e01_basic_ping_bot/src/main.rs](https://github.com/serenity-rs/serenity/blob/current/examples/e01_basic_ping_bot/src/main.rs) is more fundamental and better suited for the purpose.
