### ISSUE TITLE
Getting a user's voice channel from an interaction

### ISSUE THREAD

**Issue by bollian** [serenity-rs/serenity#1601]
I'm receiving an application command for joining a voice channel, but can't figure out how to get the sender's current voice channel. As far as I can tell, the correct path is to get a `VoiceState` from the `User` contained within the `ApplicationCommandInteraction` I'm handed as part of the interaction handler. All examples I can find use the `Guild` object to achieve this, but I can't figure out how to construct one / fill the cache with one.

**Comment by vicky5124** [comment]
https://gitlab.com/vicky5124/lavalink-rs/-/blob/master/examples/poise_basic_queue/src/main.rs#L151-188
This is how I do it with poise, if it helps.

**Comment by bollian** [comment]
As far as I can tell, poise just gets the information from the cache using `Cache::guild`. I have code that tries to do this, but my cache isn't containing the necessary `Guild`.

**Comment by vicky5124** [comment]
Guild is obtained on startup, make sure you have the basic GUILDS intent enabled, and that the `cache_ready` event fired up. Also, there were issues building cache on past versions, make sure you are using the latest version of serenity!

**Comment by bollian** [comment]
Adding the intent did the trick, thanks! Would you mind if I added that advice to the Cache documentation?

**Comment by vicky5124** [comment]
The intents or cache documentation should be updated noting which cache elements will become available with each intent, and not only for this use case.

**Comment by bollian** [comment]
Unfortunately, I don't think I know the API well enough to do that.

**Comment by kangalio** [comment]
Done in #2249
