### ISSUE TITLE
Allow event handler methods to return results.

### ISSUE THREAD

**Issue by VixieTSQ** [serenity-rs/serenity#1615]
Sorry if I am mistaken but I seem to not be able to return a result out of a event handler method. I.E:

```
use anyhow::Result;

#[async_trait]
impl EventHandler for Handler {
    async fn ready(&self, _: Context, ready: Ready) -> Result<()> {
        println!("{} is connected!", ready.user.name);
    }
}
```
I'd like to be able to propagate errors for the sake of convenience.

**Comment by vicky5124** [comment]
The event function structure is defined by the `EventHandler` trait, it would need to be modified for that to be possible in the first place. The issue with events returning a Result is that there would be no easy or ergonomic way to move those returned values into a different place, as every single event spawns a task to call the handler function.
If you wish to have this functionality, use the [RawEventHandler](https://serenity-rs.github.io/serenity/current/serenity/prelude/trait.RawEventHandler.html) with a custom implementation of your own to handle errors.

**Comment by kangalio** [comment]
Or, wrap every event handler function with your error handling
```rust
use anyhow::{Error, Result};

async fn ready(handler: &Handler, ctx: Context, ready: Ready) -> Result<()> {
    println!("{} is connected!", ready.user.name);
    Ok(())
}

async fn message(handler: &Handler, ctx: Context, msg: Message) -> Result<()> {
    println!("{} sent a message", msg.author.name);
    Ok(())
}

async fn on_error(e: Error) {
    // Central error handling goes here
}

#[async_trait]
impl EventHandler for Handler {
    async fn ready(&self, ctx: Context, ready: Ready) {
        if let Err(e) = ready(self, ctx, ready).await { on_error(e).await }
    }

    async fn message(&self, ctx: Context, msg: Message) {
        if let Err(e) = message(self, ctx, msg).await { on_error(e).await }
    }
}
```

**Comment by VixieTSQ** [comment]
I ended up choosing a variant on @kangalioo response. It works but I still wish I wouldn't have to do it. Unsure if I should close this or not. I get it would be difficult and probably worth less than the effort it would take to implement but I'm fairly sure is possible by @vicky5124 response.

**Comment by w1kee** [comment]
i don't like this design

**Comment by kangalio** [comment]
Can you explain some more @w1kee ?

**Comment by w1kee** [comment]
i think that there should be FallibleEventHandler, whose methods return `Result<(), Self::Err>`

**Comment by kangalio** [comment]
Where would returned errors be handled?

**Comment by vicky5124** [comment]
The `FallibleEventHandler` trait could have an `on_event_error` method that would have the `Box<dyn std::error::Error>` as a parameter, and there they could be handled.
