### ISSUE TITLE
Example 1 not working - Token Not Found (but the token is right)

### ISSUE THREAD

**Issue by RylanYancey** [serenity-rs/serenity#1621]
## What i've done:

1. Made sure my dependencies are correct
```toml
// in Cargo.toml
[dependencies]
serenity = "0.10.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
```

2. Copied the code (of Example 1 -> basic ping bot) manually into the Rust project

3. Created a discord application and bot on Discord Developer Portal

4. Copied the token and added it to the DISCORD_TOKEN field in main.rs

5. Ran the code 
> Note: I'm using Linux WSL to run this.  I'm not using a makefile. I'm using `cargo run` to run the code. 

## The issue i'm having

> this error: `thread 'main' panicked at 'Expected a token in the environment: NotPresent', src/main.rs:44:89
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

This issue arises out of line 44, which is this:
```rs
    let token = env::var("OTIxODU5NTk0NzQ4MzA5NTE1.Yb5Cpg.Oq-zzdjlMQrjofC0nrOTkNxvqc4").expect("Expected a token in the environment");
```
for some reason, the env::var field is rejecting my token and outputting an error. 

## What I've tried

Changing the `[dependencies]` field to include the serenity dependency the same way it does in Github. (the way it does in github makes the toml file break). 

I've also regenerated my token twice. See image of comparison. 

![image](https://user-images.githubusercontent.com/76256852/146656465-b9bee552-b875-4647-9117-4861eda0acae.png)
![image](https://user-images.githubusercontent.com/76256852/146656470-acc6056e-7700-4ab9-92b7-9641b52a533c.png)

> I've already regenerated the token, this one is no longer valid so nobody can take it from this image.

### Other Things

I did notice that the version of the example project was in 2018.  Is it possible this example is outdated? if so, it desperately needs to be updated.  I'm using Rust 2021 edition. 

### Conclusion

I've followed all information in the README as I understand it, and have made sure to read all the comments in the file. 

I also read the starter guide on the Serenity crates.io page. 

I am new to Rust, with this being my first non-console project. Its possible I am missing something simple.  Any advice or direction is greatly appreciated.

**Comment by OverHash** [comment]
When you do `env::var("OTix...").expect("Expected a token in the environment");`, Rust is looking up the environmental variable `OTIx...` to find out what the value is at that given key. Since I presume you have not set this value, the lookup will fail.

You can fix this by making your line simply
```rs
let token = "OTIx...";
```
or alternatively, setting the `DISCORD_TOKEN` environmental variable first by running
```bash
DISCORD_TOKEN=OTIx... cargo run
```

**Comment by arqunis** [comment]
Thanks for the outstanding report! Unfortunately, I advise you to **IMMEDIATELY** reset your bot's token -- it grants access to its whole Discord account, meaning someone can perform malicious actions with it.

As @OverHash said, the example retrieves the token via an environment variable called `DISCORD_TOKEN`. Most people misinterpret this as the place to put their token, but we're actually trying to suggest a best practice for storing secrets, like a Discord token (i.e. secrets shouldn't be part of the binary and exist somewhere externally alongside the binary).

**Comment by RylanYancey** [comment]
@acdenisSK 
@OverHash 

Thanks for the response!

Changing it to `let token = "token";` proved to work.

Its very unintuitive to do that that way for beginners.  Perhaps the comments should be updated to prevent future confusion?

I was also sure to regenerate my discord token, as I clarified in the issue post.

**Comment by adumbidiot** [comment]
I'm fairly certain the example is written like that so people don't use `let token = "token";` as they might accidentally share the code and their token. As for the comments, the token line is annotated with "Configure the client with your Discord bot token in the environment." in the example. Is that not clear enough?

**Comment by kangalio** [comment]
I suppose it could say
```rust
    // Retrieves the Discord bot token from an environment variable
    // Don't copy-paste your token here! Instead, create an environment variable called DISCORD_TOKEN
    let token = env::var("DISCORD_TOKEN").expect("Expected a token in the environment");
```
