### ISSUE TITLE
Open CVEs in chrono dependency

### ISSUE THREAD

**Issue by Tony-Goat** [serenity-rs/serenity#1643]
I was investigating my source code with `cargo audit` when I discovered that there are two open CVEs with the chrono library

```
Crate:         chrono
Version:       0.4.19
Title:         Potential segfault in `localtime_r` invocations
Date:          2020-11-10
ID:            RUSTSEC-2020-0159
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:      No safe upgrade is available!
Dependency tree:
chrono 0.4.19
├── serenity 0.10.9
│   └── multi-target-bot-specialist 2.1.1
└── log4rs 1.0.0
    └── multi-target-bot-specialist 2.1.1

Crate:         time
Version:       0.1.43
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23
Dependency tree:
time 0.1.43
└── chrono 0.4.19
    ├── serenity 0.10.9
    │   └── multi-target-bot-specialist 2.1.1
    └── log4rs 1.0.0
        └── multi-target-bot-specialist 2.1.1

error: 2 vulnerabilities found!
```

I went to the chrono library github and discovered that the last code change in chrono was over a year ago, and only minor changes have been made to the CI/CD and readme. There are also several unaddressed, open issues regarding this (See: chronotope/chrono#602, chronotope/chrono#629, and chronotope/chrono#547). So, to the best of my judgement, it would seem chrono is unmaintained and will probably not be updated in the near future.

What would be the scope of moving Serenity away from chrono and to a more well supported library, such as the time crate?

Addendum:
This is only an issue in multithreaded environments, as explained in the time-rs/time#293 thread. However, Serenity heavily leans towards multithreading, so it may become an issue if a thread calls one of the offending functions at the wrong time.

**Comment by Tony-Goat** [comment]
This is the full overview of the interactions between the buggy time library, buggy chrono library, and Serenity.

> `time` Library:
> `localtime_r` is referenced in `sys.rs:293` during the function `time_to_local_tm()`
> 
> `time_to_local_tm()` is referenced in `lib.rs:420` during the function `at()`
> 
> `at()` is referenced in `lib.rs` at:
> 	Line 427: `at()` called by `now()`
> 	Line 443: `at()` called by `Tm::to_local()`
> 
> `Tm::to_local()` is referenced in `display.rs:22` during the `fmt()` method in `Display` trait implementation for `Tm`
> 
> `chrono` Library:
> `localtime_r` is referenced in `sys/unix.rs:84` during the function `time_to_local_tm()`
> 
> `time_to_local_tm()` is referenced in `sys.rs:64` during the `local()` method implementation of the `Timespec`
> 
> `Timespec` is referenced in:
> 	`offset/local.rs` Line 102: `Timespec::local()` called by `local::now()` function
> 	`offset/local.rs` Line 164: `Timespec::local()` called by `local::Local.from_local_datetime()` method in `TimeZone` trait implementation
> 	`offset/local.rs` Line 188: `Timespec::local()` called by `local::Local.from_utc_datetime()` method in `TimeZone` trait implementation
> 
> `local::now()` is referenced in `offset/local.rs:96` during the `local::Local::today()` method
> 
> `Local::from_local_datetime()` is referenced in:
> 	`offset/local.rs` Line 130: `Local.from_local_datetime()` called during `offset_from_local_datetime()` method in `TimeZone` trait implementation
> 	`offset/local.rs` Line 146: `Local.from_local_datetime()` called during `from_local_date()` method in `TimeZone` trait implementation
> 
> `Local::from_utc_datetime()` is referenced in:
> 	`datetime.rs` Line 353: `Local.from_utc_datetime()` called during `default()` method in `Default` trait implementation
> 	`offset/local.rs` Line 138: `Local.from_utc_datetime()` called during `offset_from_utc_datetime()` method in `TimeZone` trait implementation
> 	`offset/local.rs` Line 172: `Local.from_utc_datetime()` called during `from_utc_date()` method in `TimeZone` trait implementation
> 
> Where does chrono import the outdated time library?
> 	`lib.rs:461`: Create imported as `oldtime`
> 	`date.rs:11`: Definition used for trait implementations & testing, no external method calls involved
> 	`datetime.rs:9`: Definition used for trait implementations & testing, no external method calls involved
> 	`round.rs:10`: Calls `Duration::nanoseconds()`
> 	`format\parsed.rs:8`: Calls `OldDuration::days()`, `OldDuration::seconds()`
> 	`naive\date.rs:11`: Calls `OldDuration.num_days()`, `OldDuration.year()`, `OldDuration.of()`, `OldDuration::days()`, `OldDuration::weeks()`
> 	`naive\datetime.rs:11`: Calls `OldDuration::seconds()`
> 	`naive\time.rs`: Calls `OldDuration::nanoseconds()`, `OldDuration::seconds()`, 
> 	`offset\fixed.rs`: Calls `OldDuration::seconds()`
> 
> Where does Serenity import the chrono library?
> 	`model\event.rs:14`, `model\invite.rs:5`, `model\voice.rs:5`,
> 	`model\channel\guild_channel.rs:6` `model\channel\private_channel.rs:26`,
> 	`model\guild\member.rs:8`: Only used for type definitions and direct field access
> 
> 
> 	`model\channel\mod.rs:19`, `model\user.rs:588` : Only used for type definition
> 
> 
> 	`cache\mod.rs:1012`, `utils\mod.rs:810`: Only used in testing
> 
> 
> 	`model\id.rs:4`: Line 18: Calls Utc.timestamp_millis() -> No Definition Found?
> 
> 
> 	`utils\custom_message.rs:1`: Line 267: Calls `Utc::now()`
> 	`build\edit_voice_state.rs:3`: Line 37: Calls `Utc::now()`
> 		Calls `SystemTime::now()` -> Thread safe standard library function
> 		Calls `NaiveDateTime::from_timestamp()`
> 			Calls `NaiveDateTime::from_timestamp_opt()`
> 				Calls `NaiveDate::from_num_days_from_ce_opt`
> 					Calls `YearFlags::from_year_mod_400()` -> Returns element from const array
> 					Calls `NaiveDate::from_of()` -> Constructs from provided flags
> 		Calls `DateTime::from_utc()` -> Constructs from arguments
> 
> 
> 	`model\guild\mod.rs:17`:
> 		Line 2489: Calls `Datetime::deserialize`
> 			Calls `DateTime<UTC>.deserialize()`
> 				Calls `DateTime<FixedOffset>.with_timezone()`
> 					Calls `TimeZone.from_utc_datetime()` --> Known possibly unstable function, check invariances
> 
> 
> 		Line 3206 & 3238: `FixedOffset::east` produces DateTime<Utc> Structure
> 			Calls `FixedOffset::east_opt()` -> Returns directly built struct
> 
> 
> 	`model\channel\message.rs:12`: Line 372 Calls to `DateTime.timestamp()`
> 		Calls to NaiveDateTime.timestamp()
> 			Calls NaiveDateTime.date.num_days_from_ce()
> 				Calls NativeDate.year() -> Returns a struct field
> 			Calls NaiveDateTime.time.num_seconds_from_midnight() -> Returns a struct field
> 
> 
> 	`builder\create_embed.rs:20`: Line 499, 510: Calls `DateTime.to_rfc3339()`
> 	`builder\edit_member.rs:4`: Line 118: Calls `DateTime.to_rfc3339()`
> 		Calls `DateTime.format_with_items()`
> 			Calls `DateTime.naive_local()`
> 				Calls `Timezone::Offset.fix()`
> 					Calls `FixedOffset::east()` -> Known safe from `model\guild\mod.rs`
> 			Calls `DelayedFormat::new_with_offset()`
> 					Calls `TimeZone::Offset.fix()` -> Known Safe
> 			Calls `NaiveDateTime.date()` -> Returns struct field
> 			Calls `NaiveDateTime.time()` -> Returns struct field
> 

In essence: Since Serenity uses the `Offset::UTC` versions of the functions instead of `Offset::Local`, `localtime_r` is never called and there's never any risk of the datarace that causes crashes within the Serenity codebase, unless Chrono decides to change how `DateTime<UTC>` is deserialized. 

Users of the library should know that to prevent crashes from this CVE, they should completely avoid all `Offset::Local` versions of Chrono's and Time v0.1.43 functions, and should instead prefer to use newer versions of the Time library.

**Comment by arqunis** [comment]
`chrono` is no longer a required dependency. Users now have the liberty to choose between `chrono` and `time` through [the use of features](https://github.com/serenity-rs/serenity/blob/current/Cargo.toml#L183). Although, we are still using `chrono` by default.
