### ISSUE TITLE
Pattern for Multi-Function Bots

### ISSUE THREAD

**Issue by ztroop** [serenity-rs/serenity#1660]
Hello! I've reviewed the `examples` folder and documentation and it's not immediately clear to me how to implement multiple background tasks for a given bot. I can easily answer messages by leveraging the `EventHandler`trait and using `Client::builder`. However, I'd also like to run arbitrary background tasks asynchronously as well... The only way I can do that now is that I would create a new client for each task. It feels inefficient and wanted to know if there's any recommended patterns to accomplish this sort of scenario.

**Comment by nickelc** [comment]
Have you seen the [e13_parallel_loops] example?
Alternatively, you check out my [bot].
 
[e13_parallel_loops]: https://github.com/serenity-rs/serenity/blob/current/examples/e13_parallel_loops/src/main.rs
[bot]: https://github.com/nickelc/modio-bot/blob/b9f41da2fcb005a7feb5bda3f0367102d06d1638/src/main.rs#L82-L103

**Comment by kangalio** [comment]
Use `tokio::spawn()` to start a background task anywhere
