### ISSUE TITLE
more helpful message/documentation on GuildId#members about these intents?

### ISSUE THREAD

**Issue by KisaragiEffective** [serenity-rs/serenity#1676]
When I run below code, it is always `Err`.
```rs
                let x = guild.id().members(&ctx.http, None, None).await;
                println!("{:?}", x);
```

I noticed that there's Server member's intent. After I turned on that, it yields `Ok`.
So maybe add note on both message and documentation about intents?

**Comment by kangalio** [comment]
Can't reproduce with gateway intents `GatewayIntents::empty()` and code `dbg!(GuildId(703332075914264606).members(&ctx, None, None).await);` (this code executes fine)

What serenity version are you running?
