### ISSUE TITLE
Simpler slash command example with functions.

### ISSUE THREAD

**Issue by BuyMyMojo** [serenity-rs/serenity#1724]
An example on slash commands that is cleaned up and streamlined for basic commands in functions.

Like showing how to migrate a command that is currently called by `~avatar @user` into `/avatar @user` would be a very useful resources

**Comment by adumbidiot** [comment]
Have you seen https://github.com/serenity-rs/serenity/blob/current/examples/e14_slash_commands/src/main.rs?

**Comment by BuyMyMojo** [comment]
> Have you seen https://github.com/serenity-rs/serenity/blob/current/examples/e14_slash_commands/src/main.rs?

Yes but that has all the definition inside the very start of the file and no larger functions for the commands. No specific functions for a command at all as far as I can see

**Comment by adumbidiot** [comment]
Yeah its not really a framework, just showing how to interact with the slash commands api. You probably want something like https://github.com/kangalioo/poise.

**Comment by overlisted** [comment]
#1462
