### ISSUE TITLE
Message Recieved, but no content

### ISSUE THREAD

**Issue by jodonnell77** [serenity-rs/serenity#1726]
I have been having a problem where I am receiving a message, with the proper author and messageID, but the content string is blank. I am trying to follow the Example 1.

rustc 1.58.1 (db9d1b20b 2022-01-20)

**Comment by EnokiUN** [comment]
Perhaps there's an issue with your intents? Check if you have the message content intent for your bot.

**Comment by kangalio** [comment]
This issue can be closed, this is a classic case of missing MESSAGE_CONTENT
