### ISSUE TITLE
Proxy setting not applied to every outgoing request to Discord

### ISSUE THREAD

**Issue by lapin-b** [serenity-rs/serenity#1739]
This is more of a compound bug report but it will be on the same thing. If this issue needs splitting, I won't mind doing so.

## The context

Per pull request #1266, proxy support has been added to Serenity which would make testing behavior of slash commands ─ hopefully ─ a little bit easier. I also take note that the [`HttpBuilder::proxy` method](https://github.com/serenity-rs/serenity/blob/3a64da19e75f2c70830beeca9c0963f7d579a992/src/http/client.rs#L164) is intended to be used with twilight-http-proxy.

## Current behavior

Given what's above, I'll assume that setting the proxy to `None` in the [requests sent with the rate-limiting logic](https://github.com/serenity-rs/serenity/blob/3a64da19e75f2c70830beeca9c0963f7d579a992/src/http/ratelimiting.rs#L192) is a desired behavior because disabling rate-limiting and enabling proxying seem to be a requirement to send requests through a proxy. (1st component of this issue)

That said, even with proxying enabled and rate-limiting disabled, looking at what requests my proxy software is recording, *not all HTTP requests* go through the proxy because they are not present in the log. In fact, the "lightweight" requests sent with [`Http::wind`](https://github.com/serenity-rs/serenity/blob/3a64da19e75f2c70830beeca9c0963f7d579a992/src/http/client.rs#L3457) do not appear because the proxy is always set to `None`. (2nd component of this issue)

## Expected behavior

Assuming that the rate-limiter not sending through the proxy is desired behavior, I would expect that all requests sent via the "normal" and the "light" methods are sent via the configured proxy and not to Discord directly.

If something is not clear, I'll happily rephrase certain parts of this issue and try to make it clearer.

## Minimal reproduction steps

- Run a proxy software that relays queries to Discord. I'm still personally exploring the topic and haven't settled on a definite piece of software. System-wide proxying is disabled.
- Create the `Http` client and Discord client separately
```rust
#[tokio::main]
async fn main() -> eyre::Result<()> {
    // Discord
    let http = HttpBuilder::new(token)
        .application_id(std::env::var("APPLICATION_ID").unwrap().parse().unwrap())
        .proxy("http://127.0.0.1:3000")
        .unwrap()
        .await
        .unwrap();

    let mut client = ClientBuilder::new_with_http(http)
        .event_handler(Handler)
        .raw_event_handler(RawHandler)
        .intents(
            GatewayIntents::GUILDS
                | GatewayIntents::GUILD_MEMBERS
                | GatewayIntents::GUILD_BANS
                | GatewayIntents::GUILD_MESSAGES
                | GatewayIntents::GUILD_MESSAGE_REACTIONS,
        )
        .await
        .context("Failed to create client")?;
}
```
- Create a basic application command that sends a basic follow-up response (I can build one if necessary)
- Compile and run the bot
- Execute the slash-command
- HTTP request to fetch the gateway and register the commands appear in the proxy log. The HTTP request to send the interaction response does not appear.

## System information

Rust version: 1.58.1
Serenity version: 0.10.10; `unstable_discord_api` feature flag is enabled

**Comment by arqunis** [comment]
> In fact, the "lightweight" requests sent with [`Http::wind`](https://github.com/serenity-rs/serenity/blob/3a64da19e75f2c70830beeca9c0963f7d579a992/src/http/client.rs#L3457) do not appear because the proxy is always set to `None`. (2nd component of this issue)

If ratelimiting has been disabled, and a proxy set, `Http::wind` should be sending its requests through the proxy. The method is just a wrapper around `Http::request`, and that method makes sure to pass on the proxy to use when performing a request (assuming the aforementioned conditions had been met). Do other methods like `Http::fire` also display this behaviour? For `Http::wind` to drop (i.e. forward to Discord instead) requests, I can only assume that's a major bug, but the code doesn't give a clear clue why.

> Assuming that the rate-limiter not sending through the proxy is desired behavior

The idea is that you avoid executing ratelimiting-related behaviour twice if a proxy implements its own behaviour, which in that case, yes, it is desired behaviour. I wouldn't oppose supporting proxies in the ratelimiter, however. It would require a small breaking change to the `Ratelimiter`'s public API to be able to pass a proxy, but the rest would be simple.

**Comment by lapin-b** [comment]
I have investigated a little further to validate (or invalidate) my hypothesis. It turns out that I had missed that I was using slash-commands from the bot running on the server and not the one I'm using for development. Obligatory "whoops, my oversight on that small but very important detail" moment.

That said, the questions I have asked are answered and I'll keep note of the possibility of adding proxy support to the ratelimiter.
