### ISSUE TITLE
Group checks seemingly do not work

### ISSUE THREAD

**Issue by Kirottu** [serenity-rs/serenity#1741]
I have a check for a Moderator group which checks and makes sure the user has the correct role, but this check does not seem to be working. Not at least for the help message. The moderator group is still visible in the help message. On a further look calling the commands in the Moderator group is in fact impossible, but the option being visible is a problem.

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
