### ISSUE TITLE
issue with e14_slash_commands, application_id not present.

### ISSUE THREAD

**Issue by SFSteffensen** [serenity-rs/serenity#1771]
i was trying out some of the examples but it seems e14_slash_commands has an issue with application id.
it works fine building, but when run I get an error.

Backtrace: `thread 'main' panicked at 'Expected an application id in the environment: NotPresent'`
although the id has been put in.
example:
```rs
 let application_id: u64 = env::var("952855883019350026")
        .expect("Expected an application id in the environment")
        .parse()
        .expect("application id is not a valid id");
```
Serenity is configured as: 
`serenity = { default-features = false, features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"], version = "0.10.10" }`
rust ver: `rustc 1.59.0 (9d1b2106e 2022-02-23)`

**Comment by arqunis** [comment]
You should have either kept the original string, or replaced the whole expression with the ID. `std::env::var` is a function to read a value of an environment variable. The example uses this to retrieve the token and the application ID without hardcoding values. `DISCORD_TOKEN` and `APPLICATION_ID` are *not* placeholders -- they are the names of the environment variables to read from.

Defining environment variables depends on your operating system, but if you are on Linux (or at least, use a shell like bash), you can set an environment variable using either:
1. `export APPLICATION_ID=952855883019350026`, then building/running the example
2. `APPLICATION_ID=952855883019350026 cargo build ...`

If you do not want to do this and are fine with hardcoding values, you can just do this:
```rust
let application_id: u64 = 952855883019350026;
```
