### ISSUE TITLE
Support returning multiple prefixes in a single `dynamic_prefix` hook or similar configuration option

### ISSUE THREAD

**Issue by JRMurr** [serenity-rs/serenity#1773]
I'm porting over my old discord py bot which i had support for adding multiple prefixes per guild. This honestly is not very used so if this feature is too much I'm cool with closing this.

`dynamic_prefix` only allows for returning a single prefix per hook. You can add multiple `dynamic_prefix` hooks but would be nice if a single hook could return an iterable like https://docs.rs/serenity/latest/serenity/framework/standard/struct.Configuration.html#method.prefixes does.

**Comment by mkrasnitski** [comment]
You can call `dynamic_prefix` multiple times to add more than one hook.

**Comment by evieluvsrainbows** [comment]
@mkrasnitski he already stated that in his initial issue description - he wants an option to where he can add multiple dynamic prefixes in only one parameter call.

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
