### ISSUE TITLE
`Args::quoted` requires the current token to be a quoted token.

### ISSUE THREAD

**Issue by AlterionX** [serenity-rs/serenity#1775]
This just seems kind of weird to me and leads to some unexpected behavior.

For example:
```rs
let mut args = Args::new("something \"hello\"", &[Delimiter::Single(' ')]);
args.quoted();
args.advance();
asset_eq!(args.current(), Some("\"hello\""));
```
but
```rs
let mut args = Args::new("\"something\" \"hello\"", &[Delimiter::Single(' ')]);
args.quoted();
args.advance();
asset_eq!(args.current(), Some("hello"));
```

Not sure if I'm missing why `quoted` is so complicated while `unquoted` does do what I'd expect it to do.

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
