### ISSUE TITLE
Music player question

### ISSUE THREAD

**Issue by quartz55** [serenity-rs/serenity#178]
Hey there, this isn't really an issue as much as it is a question/discussion.

Found this little library the main reason to compel me to finally dive deep into rust, mainly in the form of a discord music bot in rust! 😄 

For this I kind of need a way to query the current gateway connection if it is sending something to the voice channel, or at least a way to know how many bytes from the AudioSource reader have been read/sent over the wire in order to keep track of the currently playing song (for play/pause functionality as well as autoplaying next song in queue).

However, my main downfall is my inexperience with concurrent programming in rust. I was thinking of implementing all of this functionality described above outside the library, and I would probably need to run some sort of asynchronous process that takes care of all the state needed and is responsible for managing the voice connection (or VoiceManager) by maybe splitting a stream into buffers and sending those bytes over the gateway connection and thus being able to track the music playback all by itself. Possibly I would need to create a separate music player thread for each server and it is this need of sending all sort of different data between different threads that has been poisoning my progress.

**Now the question of this topic is:**
Would it be better to implement this functionality directly into the library (maybe like how [discord.py](http://discordpy.readthedocs.io/en/latest/api.html#discord.VoiceClient.create_stream_player) does it) or to keep it separated as a library user implementation?

_NOTE: Sorry if this isn't the correct place to ask this_

**Comment by Roughsketch** [comment]
If you are talking about adding pause, resume, and on_finished methods then I believe that would best be put in the library since it is common functionality that users would want.

**Comment by zeyla** [comment]
For now we're going to leave this functionality out of the standard serenity library proper, but will likely add this in an official external "audio extra" crate.
