### ISSUE TITLE
On the `next` branch, no commands work and guilds appear invalid

### ISSUE THREAD

**Issue by Kirottu** [serenity-rs/serenity#1789]
After trying to migrate my project to slash commands with `poise`, which uses serenity's next branch I noticed that none of the commands work. After printing out the `Ready` event it appears that the server I was testing in was marked as unavailable. After that I tried migrating the project to work on the serenity next branch, and the issue persisted. So this appears to be an issue with serenity and not poise.

Steps to reproduce:
1. Make a bot with the next branch
2. Run it
3. No commands should work and if in the `ready` event the `Ready` struct is printed out, whatever server it is in shows as unavailable.

It was suspected that this may be due to the change to discord api version 10 by poise's dev. That is all the info I got on this.

**Comment by adumbidiot** [comment]
Make sure to enable the [`MESSAGE_CONTENT`](https://serenity-rs.github.io/serenity/next/serenity/model/gateway/struct.GatewayIntents.html#associatedconstant.MESSAGE_CONTENT) intent.

**Comment by kangalio** [comment]
Does this issue still occur? @Kirottu
