### ISSUE TITLE
Rewrite the lib in Go - Attempt 2

### ISSUE THREAD

**Issue by Lakelezz** [serenity-rs/serenity#1805]
Please re-evaluate https://github.com/serenity-rs/serenity/issues/524 as GOLANG now added generics.
Also Denis is asleep, we may get this accepted before he wakes up!

No more lifetimes, only go(od) times!

serenity.go already has such a positive vibe :)

**Comment by VixieTSQ** [comment]
I second this!

**Comment by iddm** [comment]
Good morning guys. I have just woken up, didn't realise it was a joke, how dare you!

**Comment by Lakelezz** [comment]
> Good morning guys. I have just woken up, didn't realise it was a joke, how dare you!

Sorry, this is serious, we must go forward, the name Rust just does not fit the cheerful vibe GO!!! has.

**Comment by Lakelezz** [comment]
Imagine TWICE singing: SERENITY GO!
There are so many great opportunities hiding in this decision...

**Comment by VixieTSQ** [comment]
Go🚀is🚀fast🚀and🚀definitely🚀memory🚀safe🚀. It🚀also🚀has🚀a🚀garbage🚀collector🚀which🚀we🚀all🚀know🚀is🚀better🚀than🚀hard🚀to🚀learn🚀rust🚀ownership🚀.

**Comment by tazz4843** [comment]
This sounds like an amazing idea. We should implement this as soon as possible!

**Comment by justanotherbyte** [comment]
Sped

**Comment by NotNorom** [comment]
To the moon! 🚀🚀🚀

**Comment by VixieTSQ** [comment]
> To the moon! 🚀🚀🚀

_GO_ to the moon

**Comment by kangalio** [comment]
Go is faster anyways https://youtu.be/5cEunr8hPE0

**Comment by VixieTSQ** [comment]
now that go is officially no longer funny, I move we close this issue (and open another one just like it next year)
