### ISSUE TITLE
Inconsistent feature name casing

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#1820]
List of serenity features with multiple words:
- default_native_tls
- default_no_backend
- absolute_ratelimits
- voice-model
- standard_framework
- unstable_discord_api
- simdjson
- rustls_backend
- rustls_backend_marker
- native_tls_backend
- native_tls_backend_marker

All of them use snake_case, except voice-model with kebab-case and simdjson with flatcase. For consistency, all features should use snake_case

To make this a non-breaking change, we can redirect the old name to the new name
```diff
-simdjson = ["simd-json"]
+simd_json = ["simd-json"]
+simdjson = ["simd_json"] # redirect

-voice-model = ["serenity-voice-model"]
+voice_model = ["serenity-voice-model"]
+voice-model = ["voice_model"] # redirect
```

**Comment by Milo123459** [comment]
I presume this should be targetted at the next branch?

**Comment by kangalio** [comment]
By redirecting the old feature names to the new ones, the change can be non-breaking and target the current branch
