### ISSUE TITLE
Event for when all shards are ready

### ISSUE THREAD

**Issue by Milo123459** [serenity-rs/serenity#1831]
Wasn't sure how to implement this so I'm putting it here in an issue so perhaps someone else can pick it up or explain how to implement it.

**Comment by Headline** [comment]
Hi! 

I have this implemented, here's the link below for reference.

https://github.com/Headline/discord-compiler-bot/blob/80a615b74ce1295e475bb60c791d29a924d9bf07/src/events.rs#L245-L261

**Comment by Milo123459** [comment]
Do you think you could work on adding this event directly into serenity?

**Comment by Headline** [comment]
> Do you think you could work on adding this event directly into serenity?

It's really up to the maintainers to decide if they'd want such an event. I'd implement it if green lit

**Comment by GnomedDev** [comment]
What would happen in the case that (with 2 shards)

Shard 0: Ready
Shard 0: Disconnects
Shard 1: Ready
Shard 0: Ready (again)?

Or even if, after a while of running, a shard disconnects and reconnects, would this trigger the callback again?
