### ISSUE TITLE
Missing `Attachment` in `ApplicationCommandOptionType` enum

### ISSUE THREAD

**Issue by flibdev** [serenity-rs/serenity#1851]
Feature was added to Discord API on 8th Feb 2022 - [Change Log](https://discord.com/developers/docs/change-log#interaction-modals-and-application-command-attachment-option-type)

It's not clear in the documentation currently if the attachment will be included in the `options` or `resolved` fields of the `ApplicationCommandInteractionData` struct

**Comment by kangalio** [comment]
This can be closed too, then? See #1852
