### ISSUE TITLE
Snowflakes and anything containing them don't appear to be deserialized properly with the simdjson feature

### ISSUE THREAD

**Issue by MelonShooter** [serenity-rs/serenity#1869]
Serenity version: 0.11.1

Rust version: 1.60

When I enabled the ``simdjson`` feature, my bot wouldn't properly add guild data from the ``GuildCreate`` event into the cache and practically any event that deserializes a snowflake (which is practically all of them) would never be called:

``` rust
10:20:19 [WARN] [Shard [0, 1]] Unhandled error: SimdJson(Error { index: 0, character: '💩', error: Serde("event GuildCreate: Serde(\"Serde(\\\"invalid type: string \\\\\\\"694316796257501295\\\\\\\", expected tuple struct ChannelId\\\") at character 0 ('💩')\") at character 0 ('💩')") })

10:20:19 [WARN] [Shard [0, 1]] Unhandled error: SimdJson(Error { index: 0, character: '💩', error: Serde("event GuildMemberUpdate: Serde(\"invalid type: string \\\"720900750724825138\\\", expected tuple struct UserId\") at character 0 ('💩')") })
```

This appears to be an issue for deserialization for snowflake IDs. With some basic debugging, I noticed that when ``from_value``, which appears to call ``simd_json::serde::from_owned_value``, is called in ``serenity::model::event::deserialize_event_with_type`` for the GuildCreate event, an Err Result is returned and propagated. Without the simdjson feature enabled, the ``from_value`` function properly defers deserialization to the ``snowflake ``module within ``serenity::model::id`` when a snowflake ID is encountered while the event is being deserialized, but this doesn't appear to happen when the feature is enabled. Unfortunately, I'm not experienced enough with serde and simd-json to know why this would be happening and whether the bug is from this crate or not, so I thought I'd just post it here first so others who know more than me on this can investigate and figure it out. I've put a code snippet below showing what I described and the result of it as well.

Minimal test case:
``` rust
use serde_json::{Map, Value as SerdeValue};
use serenity::model::id::ChannelId;
use simd_json::owned::Object;
use simd_json::owned::Value as SimdJsonValue;

#[test]
fn simd_json_test() {
    let mut map = Object::new();

    map.insert(
        "id".to_string(),
        SimdJsonValue::from("367538590520967181".to_string()),
    );

    let id: ChannelId = simd_json::serde::from_owned_value(map.remove("id").unwrap()).unwrap();

    println!("{id}");
}

#[test]
fn serde_test() {
    let mut map = Map::new();

    map.insert(
        "id".to_string(),
        SerdeValue::from("367538590520967181".to_string()),
    );

    let id: ChannelId = serde_json::from_value(map.remove("id").unwrap()).unwrap();

    println!("{id}");
}
```

Result:
``` rust
running 2 tests
test serde_test ... ok
test simd_json_test ... FAILED

failures:

---- simd_json_test stdout ----
thread 'simd_json_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { index: 0, character: '💩', error: Serde("invalid type: string \"367538590520967181\", expected tuple struct ChannelId") }', tests/test.rs:15:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    simd_json_test

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '--test test'
```

**Comment by nickelc** [comment]
It's the same with `utils::Colour`.

**Comment by Headline** [comment]
@Licenser Could you take a look at this?

Is this a serde simd-json incompatibility issue?

**Comment by Licenser** [comment]
Taking a peak :)

**Comment by Licenser** [comment]
So,
took a look. Thanks for the wonderful reproduction, that made it a quick fix! simd-json `0.4.14` should solve this.

**Comment by MelonShooter** [comment]
I just verified that it appears to be working for both snowflakes and colors so I'll close this issue. Based on some quick profiling, it appears using the ``simdjson`` feature significantly reduces instruction count on startup, so good job.

**Comment by Licenser** [comment]
It's worth pointing out that the code is still using serde-json derive which is significantly slower than using simd-Jason's own derive at least when using it directly from a byte array.

The downside is that the own derive isn't as flexible (a bit of a tradeoff between speed, performance and ease of use) so a number of items would need to be manually implemented.

Not sure if it's worth the effort, just wanted to give a heads up on that :)
