### ISSUE TITLE
token fails to parse creation time

### ISSUE THREAD

**Issue by Yarn** [serenity-rs/serenity#1906]
note: i'm using commit `aad22f9981496e9d62b83e4d59c49ed8a634708e` but looking at the current source I expect the same issue would still occur.

I recently generated a discord token (regenerated it a few times and it happened consistently) where the second section doesn't parse correctly.

For example `OTc1MDAwMDAwMDAwMDAwMDA.G0mmRn.MDAw` (the first and last sections were edited)

This produces (results in just None being returned)
```rust
base64::decode_config(timestamp_base64, base64_config) = Err(
    InvalidLastSymbol(
        5,
        110,
    ),
)
```

Adding `let base64_config = base64_config.decode_allow_trailing_bits(true);` allows it to parse and the bot to run normally but the produced timestamp is `1751651526`/`2025-07-04T17:52:06` which isn't the actual creation time of the token.

A playground showing the issue
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3d7f33009749150372ab85ee726d09f0

**Comment by kangalio** [comment]
The token format changed, but I can't find any info on the new format. I'm thinking we should remove the token parsing functions entirely, since Discord doesn't intend users to parse tokens (and as such silently makes changes and doesn't tell what they are)

**Comment by kangalio** [comment]
Can be closed
