### ISSUE TITLE
Question: How to force the EventHandler to run/rerun based on internal/external app logic?

### ISSUE THREAD

**Issue by alphastrata** [serenity-rs/serenity#1952]
I want my bot to send messages to specific users based on its internal logic as triggered by another app, i.e not responding to ppl/commands/pings etc from the servers it is in.

Is there a way to manually/forcefully make the event loop run? [all the examples seem to be a 'response' to something originating within discord servers and are nested in the `impl EventHandler for Handler`]

(my current solution is to crash and Restart the `Client` which is...  not elegant at all as my 'ready()` method looks like something perhaps even a mother couldn't love...

**Comment by kangalio** [comment]
The `Client`, which you create on startup and call .start() on, has a field `cache_and_http` which can be used for arbitrary HTTP requests https://docs.rs/serenity/latest/serenity/client/struct.Client.html#structfield.cache_and_http

**Comment by alphastrata** [comment]
> The `Client`, which you create on startup and call .start() on, has a field `cache_and_http` which can be used for arbitrary HTTP requests https://docs.rs/serenity/latest/serenity/client/struct.Client.html#structfield.cache_and_http

I love you!

**Comment by alphastrata** [comment]
> The `Client`, which you create on startup and call .start() on, has a field `cache_and_http` which can be used for arbitrary HTTP requests https://docs.rs/serenity/latest/serenity/client/struct.Client.html#structfield.cache_and_http

@kangalioo do you happen to have/know of any bots that're using this? I couldn't find any examples of how the field is used in the docs or examples/

Apologies for the followup question post closing the thread.

**Comment by kangalio** [comment]
I can't find an example right now but the idea is
- clone the `Arc<CacheAndHttp>` out of Client (Arc is cheap to clone) and store it (easy, because it's owned => no lifetimes)
- pass your stored CacheAndHttp (or the contained Http, depending on method) to whichever methods you want to invoke
    - all Discord API methods in serenity take `impl AsRef<Http>` or `impl CacheHttp` or something like that; which you can pass your CacheAndHttp instance into
- e.g. `ChannelId(123456789).say(&your_cache_and_http.http, "hey there").await`
