### ISSUE TITLE
Sometimes serenity will suddenly refuse to compile citing a lifetime issue.

### ISSUE THREAD

**Issue by mkrasnitski** [serenity-rs/serenity#2001]
Sometimes, serenity will fail to build because of some lifetimes not matching up. However, doing a `cargo clean` always fixes the issue. this seems to be a compiler bug. Below is an image of the bug happening.

![image](https://user-images.githubusercontent.com/42564254/174837474-ec44603b-22d1-4b2f-a98c-8e1c76a18671.png)

**Comment by nickelc** [comment]
I think I didn't see the error anymore after I disabled incremental builds.
```toml
# ~/.cargo/config
[build]
incremental = false
```

**Comment by GnomedDev** [comment]
> I think I didn't see the error anymore after I disabled incremental builds.
> 
> ```toml
> # ~/.cargo/config
> [build]
> incremental = false
> ```

The whole reason this is annoying is because it means you have to clean the incremental build cache with `cargo clean -p serenity` which takes a while for the rebuild, so making all checks have the same speed as if it just did `cargo clean -p serenity` doesn't seem like a solution.

**Comment by nickelc** [comment]
It's just to confirm where the error is coming from.

My theory is that using rust-analyzer + cargo check/build/clippy triggers a bug with incremental builds.
Similar issues went away for me in the past when I set a different `target_dir` for the `rust-analyzer` process.

**Comment by mkrasnitski** [comment]
I don't use rust-analyzer, I only invoke cargo from the CLI.
