### ISSUE TITLE
Unsuccessful Request For Application Info

### ISSUE THREAD

**Issue by daveiator** [serenity-rs/serenity#2012]
I've run into the same error as #1155 , and can't figure out what went wrong.

Produced error:
```
thread 'main' panicked at 'Could not access application info: Http(UnsuccessfulRequest(ErrorResponse { status_code: 401, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v10/oauth2/applications/@me", query: None, fragment: None }, error: DiscordJsonError { code: 0, message: "401: Unauthorized", errors: [] } }))', src\main.rs:79:21
```

This only happens on my laptop, on my desktop the bot starts without problems. I use the same OS on both, which leads me to suspect that it has something to do with my machine.

The code doesn't really seams matter. The `example programs` also don't run on my Laptop with the same issue.

I've tried running it on __Windows__ and __Ubuntu with WSL2__

Maybe someone can help me find out what causes this.
### Versions:
* rustc: 1.61.0
* serenity: 0.11.2

**Comment by jzeuzs** [comment]
Do you have a valid token?

**Comment by daveiator** [comment]
Yes. Like I've said, it runs fine on my other machine with the same token

**Comment by daveiator** [comment]
It works again. I don't know what caused it but the problems gone. I didn't deliberately update anything, so the reason remains unsolved. I can only assume that it was a problem caused by discords end who rejected my login.
