### ISSUE TITLE
use of undeclared crate or module `tokio`

### ISSUE THREAD

**Issue by w1kee** [serenity-rs/serenity#2049]
hey! i made a new cargo project, added the serenity line in the `Cargo.toml`, and put the example ping pong code in main.rs, but i'm getting this error message:
```
error[E0433]: failed to resolve: use of undeclared crate or module `tokio`
  --> src/main.rs:18:3
   |
18 | #[tokio::main]
   |   ^^^^^ use of undeclared crate or module `tokio`

error[E0752]: `main` function is not allowed to be `async`
  --> src/main.rs:19:1
   |
19 | async fn main() {
   | ^^^^^^^^^^^^^^^ `main` function is not allowed to be `async`

Some errors have detailed explanations: E0433, E0752.
For more information about an error, try `rustc --explain E0433`.
```
what version of `tokio` i should import?

**Comment by arqunis** [comment]
If it is at least `1.0`, it should be fine. Additionally, you will also have to enable the `rt-multi-thread` and `macros` features for `tokio`. [See how it is done in Example 1](https://github.com/serenity-rs/serenity/blob/current/examples/e01_basic_ping_bot/Cargo.toml#L9).

**Comment by tjb** [comment]
@acdenisSK would it be appropriate to add this information under the Installation portion of the documentation? If so, I can open a PR for it this week.

**Comment by arqunis** [comment]
@tjb Sure!
