### ISSUE TITLE
Send DM examples?

### ISSUE THREAD

**Issue by BuyMyMojo** [serenity-rs/serenity#2055]
I'm trying to send a DM to a user provided in a command but `user.create_dm_channel();` and `user.direct_message();` both require a CacheHttp object. Looking through the docs and the examples I don't see any mention of this.

Could you add some examples on how to use those functions in the docs and in this issue for me too please

**Comment by BuyMyMojo** [comment]
This was meant to go into the poise repo, sorrt!!

**Comment by sloganking** [comment]
@BuyMyMojo I am tying to send direct messages, what is the `poise repo`?

**Comment by kangalio** [comment]
Poise is another repository. Here's the moved issue: https://github.com/serenity-rs/poise/issues/94

Quick answer: pass `&Context` as the value for the `impl CacheHttp` parameter

**Comment by sloganking** [comment]
This works for me, for future readers.

```rust
#[command]
async fn messageuser(ctx: &Context, msg: &Message) -> CommandResult {
    let channel = msg.author.create_dm_channel(ctx).await.unwrap();
    channel.say(ctx, "Direct message!").await.unwrap();   
}
```

Thanks @kangalioo for the quick response!
