### ISSUE TITLE
Message deserialization errors if it has select menu

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#2062]
If I got the details correct: #1986 accommodated for Discord sending the `values` field on components in the wrong place. Discord seems to have fixed the problem now so deserialization fails due to missing `values` field.

This was noticed via get_interaction_response calls failing with a select menu present in the retrieved message https://discord.com/channels/381880193251409931/919310428344029265/999359158635741224

**Comment by bumblepie** [comment]
I ran into the same issues (currently building out some example stuff that uses select menus in both modals and messages so it's a good test) and both of the following fixes work:
```rs
...
/// The result location for modals
#[serde(default)]
pub values: Vec<String>,
```
```rs
...
/// The result location for modals
pub values: Option<Vec<String>>,
```
I think the latter probably expresses the intent more cleanly - this model is currently being used in places where this field will be present (modal submit interactions) and where it won't be (message component interactions) and there's a difference between having an empty list (no values selected) and no list (this part of the model doesn't exist). In the future it might be good to revisit the model to confirm it's aligned with the discord API (especially as I think select menus aren't officially supported in modals yet according to [the docs](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal) (?) So things are unstable and likely to change) but to get a quick fix in it should be ok.
