### ISSUE TITLE
Help-Command Sub-Sub-Group Usage Documentation

### ISSUE THREAD

**Issue by florian1345** [serenity-rs/serenity#2080]
The usage documentations in the help command of commands of sub-sub-groups are missing the first prefix.

# Code Example

```rust
#[group]
#[commands(...)]
#[sub_groups(sub)]
struct Root;

#[group("Sub")]
#[prefix("sub")]
#[commands(...)]
#[sub_groups(subsub)]
struct Sub;

#[group("SubSub")]
#[prefix("subsub")]
#[commands(my_command, ...)]
struct SubSub;
```

When running `help sub subsub my_command`, the usage would display `subsub my_command [...]` instead of the expected `sub subsub my_command [...]`.

# Version Information

Rust version: 1.62.1
Serenity version: 0.11.5

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
