### ISSUE TITLE
The voice channel is now a text channel.

### ISSUE THREAD

**Issue by WinLinux1028** [serenity-rs/serenity#2085]
The voice channel has changed to a text channel:
https://support.discord.com/hc/en-us/community/posts/4878939035543-Open-text-chat-in-voice-channel
but [serenity::model::channel::GuildChannel](https://docs.rs/serenity/latest/serenity/model/channel/struct.GuildChannel.html#method.is_text_based) still does not treat the voice channel as a text channel.

Because of this problem, I can't create a webhook in voice channel.

**Comment by vicky5124** [comment]
They allow sending messages and attachments along with webhooks, but they are not a TextChannel still, as they lack many other features such as Slowmode, Descriptions, Channel Follows and Threads. The methods should be updated to allow sending messages and creating webhooks in VoiceChannels, but they shouldn't be TextChannels.
