### ISSUE TITLE
Member-Roles out of sync between partial-member and member

### ISSUE THREAD

**Issue by Giftzwerg02** [serenity-rs/serenity#2091]
My bot creates roles and assigns them to/removes them from guild-members.
While the bot is running, if a role is created and assigned to a member, the state of the member is not update, while the state of the partial-member is:

Related code:
```rust
// adding a role
#[command]
async fn subscribe(ctx: &Context, msg: &Message) -> CommandResult {
    let role: Role = /* ... */;
    let mut member = msg.member(ctx).await?;
    member.add_role(ctx, role.id).await?;
}

// removing a role
#[command]
async fn unsubscribe(ctx: &Context, msg: &Message) -> CommandResult {
    let role: Role = /* ... */;
    let mut member = msg.member(ctx).await?;
    let partial_member = msg.member.as_ref().ok_or_else(|| anyhow::Error::msg("Member not found"))?;

    debug!("member roles: {:?}", member.roles);
    debug!("partial member roles: {:?}", partial_member.roles);

    member.remove_role(ctx, role.id).await?;
}
```

Output from the debug logs:
```yaml
[2022-08-12T15:40:24Z DEBUG discord_channel_assigner::commands::assign::unsubscribe] member roles: 
    [
        # ...
        RoleId(1007672359811023031)] # <-- differs     
[2022-08-12T15:40:24Z DEBUG discord_channel_assigner::commands::assign::unsubscribe] partial member roles: 
    [
        # ...
        RoleId(1007674817257934862)] # <-- differs
```

When looking at the role-names, the role in the partial-member log is equal to the one I expected and fetched into the role-variable in the code-snippet above. The one in the member log seems to be from an old state where the user once had this role.

The problem "solves" itself when restarting the bot, yet this sync should happen automatically.
It also doesn't seem like the cache is an issue here, since I also tried it after removing the `cache` feature from the library:
```toml
serenity = { version = "0.11.5", features = [ "base64",
    "builder",
    "bytes",
    "chrono",
    "client",
    "command_attr",
    "dashmap",
    "default_no_backend",
    "flate2",
    "framework",
    "gateway",
    "http",
    "levenshtein",
    "model",
    "parking_lot",
    "rustls_backend",
    "standard_framework",
    "static_assertions",
    "tokio",
    "typemap_rev",
    "utils",
    "uwl" ]}
```

**Comment by kangalio** [comment]
`msg.member()` uses the cached Member data (if it exists), however the cache is intended to always be up to date... Which gateway intents have you enabled?

**Comment by Giftzwerg02** [comment]
Well, after not changing the code for a month and now coming back to it I am successfully unable to reproduce this behaviour which previously happened 100% of the time...

To answer your question:
```rust
let intents = GatewayIntents::non_privileged() | GatewayIntents::MESSAGE_CONTENT;
```
Given what I've read now (after your hint), I thought that I would need to add privileged intents (or at least the `GatewayIntents::GUILD_MEMBERS` intent). So now that it works without adding that makes me even more confused...

**Comment by kangalio** [comment]
Hmm yeah GUILD_MEMBERS isn't included in non_privileged so it's not active here... Maybe serenity can update its member cache from other sources too

**Comment by kangalio** [comment]
I cannot reproduce on the current branch; even with no intents other than `GatewayIntents::GUILD_MESSAGES` enabled, the roles seem to be in sync. I tried: assigning a role, dismiss that role, creating a new role, assigning that new role

I propose this issue to be closed. If someone managed to reproduce, it can be reopened.
