### ISSUE TITLE
`EventHandler` method impls with `&mut self`

### ISSUE THREAD

**Issue by shtrophic** [serenity-rs/serenity#2098]
So I am writing a bot in serenity that has access to a database via the crate `mysql_async`.
To be able to add database queries to the method implementations of `EventHandler`, my implementing struct owns a instance of `mysql_async::Conn`.

However, since the method-impls for `EventHandler` only take an immutable reference to self, methods changing tables in the database cannot be added, since a mutable reference would be needed in this case. 

Is this something that can be added? Otherwise, what could a possible workaround look like?

**Comment by GnomedDev** [comment]
Use interior mutability (`Mutex<mysql_async::Conn>`) or use a connection pool such as deadpool or sqlx.
