### ISSUE TITLE
error: failed to run custom build command for `ring v0.16.20` 

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#2101]
Hi. I'm running latest Arch Linux and when i'm running `cargo build`.
Here is the following error:
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/andrias/Documents/serenity/target/debug/build/ring-24bda62ad47ba771/build-script-build` (signal: 4, SIGILL: illegal instruction)
  --- stdout
  OPT_LEVEL = Some("0")
warning: build failed, waiting for other jobs to finish...

**Comment by mkrasnitski** [comment]
What was your stderr? Also, try running with `RUST_BACKTRACE=full`.

**Comment by kangalio** [comment]
Can't reproduce ([terminal log](https://pastebin.com/qbK2FuD1), Arch Linux too)

If I remember correctly, incremental compilation sometimes spazzes out and causes crashes like this. In those cases `cargo clean` usually helps

**Comment by kangalio** [comment]
No response for 2 months

**Comment by Sedorikku1949** [comment]
> Hi. I'm running latest Arch Linux and when i'm running `cargo build`. Here is the following error: error: failed to run custom build command for `ring v0.16.20`
> 
> Caused by: process didn't exit successfully: `/home/andrias/Documents/serenity/target/debug/build/ring-24bda62ad47ba771/build-script-build` (signal: 4, SIGILL: illegal instruction) --- stdout OPT_LEVEL = Some("0") warning: build failed, waiting for other jobs to finish...

try this: https://github.com/briansmith/ring/issues/815
