### ISSUE TITLE
`CreateEmbed` documentations is wrong

### ISSUE THREAD

**Issue by sizumita** [serenity-rs/serenity#2125]
https://github.com/serenity-rs/serenity/blob/b1cc7022228608563e815c3f82b971d5ca6bfc74/src/builder/create_embed.rs#L233
`Z` is needed end of timestamp string or raise error `ParseError(ParseError(TooShort))`

**Comment by mkrasnitski** [comment]
As it stands, this example actually panics (!) because the `Into<Timestamp>` implementation is supposed to be infallible, therefore a parsing error can't be bubbled up. However, this has been fixed on the `next` branch, in #2032.
