### ISSUE TITLE
Add create_forum_thread() in a channel

### ISSUE THREAD

**Issue by j2ghz** [serenity-rs/serenity#2142]
Creating a thread in the new Forum channel types works differently, and the existing methods like create_public_thread() can't be used.
Discord API docs: https://discord.com/developers/docs/resources/channel#start-thread-in-forum-channel

**Comment by trkohler** [comment]
may I take this one? as a part of hacktoberfest.

**Comment by kangalio** [comment]
Yeah please, if you can (you gotta have access to a large server with forum channels whitelisted to test this, which most here don't have)

**Comment by trkohler** [comment]
yes, you make a point, I forgot they are not easily available. Is there a chance someone from Discord can give one for test?

**Comment by j2ghz** [comment]
@trkohler ping me at https://discord.gg/tachiyomi if you need one

**Comment by kangalio** [comment]
For the record: j2ghz has a large server with forums and has provided a test forum channel to trkohler

**Comment by oSumAtrIX** [comment]
@trkohler We can provide one on our 70.000 members Discord server, forums are regularly used there & we would actually need Serenity to work on it. [Add me](https://osumatrix.me/#discord) or [join here](https://revanced.app/discord).

**Comment by kangalio** [comment]
@trkohler how's it going, do you want assistance?

**Comment by trkohler** [comment]
i've already prepared the code, but need to test on the real forum (which I have). Just having busy workweeks. Hope to finish on that weekends 

I can publish the draft PR so you may see

**Comment by stormofice** [comment]
Hasn't this been fixed by https://github.com/serenity-rs/serenity/pull/2357?
