### ISSUE TITLE
[Request] Remove channel messages from cache after `ChannelDeleteEvent` is handled or provide cached messages to event handler

### ISSUE THREAD

**Issue by BuyMyMojo** [serenity-rs/serenity#2180]
The [`CacheUpdate`](https://github.com/serenity-rs/serenity/blob/next/src/cache/event.rs#L80) implementation for `ChannelDeleteEvent` Removes all cached messages unlike when messages are specifically deleted. It could be useful to log messages from within a channel after is deleted and then remove them from the cache or if the cached messages could be provided as a `MessageIterator`  like `channel_messages_field` outputs or could just be the same output as:
```rs
ctx.cache.channel_messages_field(channel.id.0, |s| {
        s.filter_map(|m| {
            if m.channel_id.0 == channel.id.0 {
                Some(m.clone())
            } else {
                None
            }
        })
    .collect::<Vec<_>>()
});
```

An example usecase;

When a channel is deleted in my server I log the information of the channel and upload it to my own hastebin for archival but since messages are removed when the event fires there is obviously no messages to be put into the logged channel's info.

Example output of deleted ticket channel in current state: https://paste.buymymojo.net/afubewecudoveriz

~~This issue is a little messy, sorry!~~

**Comment by kangalio** [comment]
Done in #2194
