### ISSUE TITLE
Discord token base64 encoding uses non-standard encoding, resulting in occasional errors

### ISSUE THREAD

**Issue by zbuc** [serenity-rs/serenity#2187]
I was trying to use the `utils::token::validate` function to validate my Discord tokens and noticed that it occasionally panicked due to base64 encoding errors. This seemed strange to me as the tokens were valid; I tracked it down and I think the solution is to use a forgiving base64 decode call.

I am also not sure if Discord tokens ever use padding (i.e. should `URL_SAFE_NO_PAD` be used?) but it doesn't seem to matter in practice because padding is optional for the `URL_SAFE` config.

**Comment by kangalio** [comment]
This issue can be closed for the same reason as #2188
