### ISSUE TITLE
Is there a way to require mentioning the bot?

### ISSUE THREAD

**Issue by DoubleCouponDay** [serenity-rs/serenity#2192]
In my serenity bot application I would like to require that the user mentions the bot before a command proceeds. This is because I don't want to take up command name real estate in my user's servers.

One way I considered to do this is by checking the message as the command fires:

    let mentions_me = msg.mentions_me(&ctx).await;

    if mentions_me.unwrap_or_default() == false {
         println!("message did not mention me.");
         return Ok(());
    }

However, after looking at[ the configuration](https://docs.rs/serenity/latest/serenity/framework/standard/struct.Configuration.html#method.on_mention) passed to the serenity framework, it's apparent that commands starting with a mention will not be considered.

Is this a feature that Serenity supports?

**Comment by kangalio** [comment]
> However, after looking at[ the configuration](https://docs.rs/serenity/latest/serenity/framework/standard/struct.Configuration.html#method.on_mention) passed to the serenity framework, it's apparent that commands starting with a mention with not be considered.
> 
> Is this a feature that Serenity supports?

What do you mean? Setting `.on_mention(...)` will run commands if they start with a bot mention. Is that not what you want?

**Comment by DoubleCouponDay** [comment]
Thanks for your consideration. I realised that you can copy the [bot's application id](https://discord.com/developers/applications) and use it as a user id in an `on_mention()` call.
