### ISSUE TITLE
error[E0061]: this function takes 1 argument but 2 arguments were supplied

### ISSUE THREAD

**Issue by svg-rs** [serenity-rs/serenity#2258]
was trying to supply a variable to the content field

code:
```rs
#[tokio::main]
async fn send() {
    // You don't need a token when you are only dealing with webhooks.
    let http = Http::new("");
    let webhook = Webhook::from_url(&http, "https://discord.com/api/webhooks/1034629307168993332/4jENJGkYH-MURcGFesW4XfhCz1dIKD749NCe4d8MVp8mYNuDshC2cFOSh6msSaaCbF80").await.expect("Replace the webhook with your own");
    webhook
        .execute(&http, false, |w| w.content("windows user {}", whoami::username()).username("real"))
        .await
        .expect("Could not execute webhook.");
}
```

error:
```rs
error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> src\main.rs:64:38
    |
64  |         .execute(&http, false, |w| w.content("windows user {}", whoami::username()).username("real"))
    |                                      ^^^^^^^                    ------------------ argument of type `std::string::String` unexpected
```

i am new to rust, any help?

**Comment by catuhana** [comment]
`w.content` takes one argument, you're passed two. You need to use `format!` macro.
```rs
w.content(format!("windows user {}", whoami::username())).username("real"))
```

Also you might want to join serenity's Discord server for questions, I don't think creating issue is a good way to ask questions. If you dont want to join server for some reason, discussion page makes more sense.

**Comment by bentuhana** [comment]
`w.content` takes one argument, you're passed two. You need to use `format!` macro. `w.content(format!("windows user {}", whoami::username())).username("real"))`

Also you might want to join serenity's Discord server for questions, I don't think creating issue is a good way to ask questions. If you dont have Discord, discussion page makes more sense.
