### ISSUE TITLE
CommandOptionData duplicates values in `resolved`

### ISSUE THREAD

**Issue by alercah** [serenity-rs/serenity#2269]
Consider a `CommandDataOption` that looks like this:

```rust
CommandDataOption{
  value: Some(String(s)),
  resolved: Some(String(s)),
}
```

This results in two copies of `s`, both owned, meaning that there is a string being needlessly duplicated somewhere in memory to produce this struct.

**Comment by kangalio** [comment]
As far as I can tell, this is issue is resolved in the next breaking version of serenity https://serenity-rs.github.io/serenity/next/serenity/model/prelude/struct.CommandDataOption.html

![Screenshot_20221106_001830](https://user-images.githubusercontent.com/21220820/200146008-90a926dd-02d5-446d-b4b8-d1c8a292ebaa.png)
![image](https://user-images.githubusercontent.com/21220820/200146031-f332207e-9083-48af-ba61-cfc313d8179f.png)
