### ISSUE TITLE
embeded messages

### ISSUE THREAD

**Issue by TheoW03** [serenity-rs/serenity#2282]
embeds arent working.

when I do it like this 
![image](https://user-images.githubusercontent.com/95878514/201501826-8a6ae8d1-3975-480f-a754-db2a38cc45ab.png)
i get this
{"description":"Making a basic embed","fields":[{"inline":false,"name":"A field","value":"Has some content."}],"title":"Embed title","type":"rich"}

and when I do |m| m.embed({|e|}) I get an error. about m being undefined?

**Comment by TheoW03** [comment]
![image](https://user-images.githubusercontent.com/95878514/201502301-da53de18-1256-4574-a841-87040e86e28e.png)


when i do it like this it has nor response :')

**Comment by TheoW03** [comment]
![image](https://user-images.githubusercontent.com/95878514/201503041-97f2f94f-74b9-4793-a6c4-3335ba27f26b.png)


For any noobs out there this is how embeds get sent on discord.rs

**Comment by mkrasnitski** [comment]
> when i do it like this it has nor response :')

I think you're forgetting to `.await` the result of `msg.channel_id.say`. In Rust, futures don't do anything unless you `.await` them. AFAIK clippy (or maybe the compiler itself) detects this and gives a warning, because futures are marked `#[must_use]`.

**Comment by kangalio** [comment]
Yeah, this is what it looks like:

![Screenshot_20221113_143634](https://user-images.githubusercontent.com/21220820/201524610-79c43438-e4c0-4028-8ca3-43be67163889.png)

**Comment by MehulKChaudhari** [comment]
Hey @TheoW03 Could you please help with this error, That would be helpful. 
![image](https://github.com/serenity-rs/serenity/assets/55375534/464c7670-4380-4058-a0fc-b9bc325b6707)

I am getting this error 
![image](https://github.com/serenity-rs/serenity/assets/55375534/79c3349d-261d-43b1-9c22-6c1f976038ac)
