### ISSUE TITLE
custom rich presence for bot

### ISSUE THREAD

**Issue by TheoW03** [serenity-rs/serenity#2284]
Does this exist in this library for discord bots?

custom rich presence for bots?

**Comment by TheoW03** [comment]
Also can you use emoji ID's with 

msg.channel_id.react?

**Comment by mkrasnitski** [comment]
For simple questions like this I suggest joining our discord: [discord.gg/serenity-rs](https://discord.gg/serenity-rs). The time it takes to receive answers should be much faster than on GitHub!

**Comment by kangalio** [comment]
Yes (`Context::set_presence`) and yes (`msg.channel_id.react(ctx, 'EMOJIHERE')`)
