### ISSUE TITLE
support for task loops

### ISSUE THREAD

**Issue by MrJico** [serenity-rs/serenity#2329]
Is there any way to run a task on a loop for example this python snippet  changes the status to online and sends a message.

```python
import discord,asyncio,os
from discord.ext import commands, tasks


token = 'xxx'
bot = commands.Bot(command_prefix='.')

@bot.event
async  def on_ready():
    change_status.start()
    print('bot in active')

@tasks.loop(seconds=30)
async def change_status():
    channel = bot.get_channel(ch_id)
    await bot.change_presence(activity=discord.Game('online'))
    await bot.channel.send('here')
bot.run(token)
``` 
looked in the source code and the docs, couldn't find any thing related.

**Comment by kangalio** [comment]
Is `tokio::time::interval` not sufficient?

**Comment by MrJico** [comment]
it thinks, there is too much over head when using intervals, and you have to hack the code to work properly
, if you think other wise fell free to provide and example.

**Comment by MrJico** [comment]
> Is `tokio::time::interval` not sufficient?

i thinks, there is too much over head when using intervals, and you have to hack the code to work properly
, if you think other wise fell free to provide and example.

**Comment by kangalio** [comment]
Here's an example of `tokio::time::interval`:

```rust
async fn say_hi_every_second() {
    let mut timer = tokio::time::interval(std::time::Duration::from_secs(1));
    loop {
        println!("Hi!");
        timer.tick().await;
    }
}

tokio::spawn(say_hi_every_second());
println!("Repeating background task started");
```

Whether this is hacky or involves too much overhead seems subjective. In any case, in my opinion an API for repeating background tasks seems like it should go into a third-party crate instead of serenity, because it has nothing to do with Discord specifically
