### ISSUE TITLE
Race condition when `SUPPRESS_EMBEDS` is set when editing a message

### ISSUE THREAD

**Issue by oSumAtrIX** [serenity-rs/serenity#2333]
Discord does not cancel their async task when they receive a request to edit a message with the flag `SUPPRESS_EMBEDS`. So when a message is sent and the flag is set when sending the message edit request right after that, Discord will still display the embed. 

For that reason, Serenity should queue a task to edit the message after `MESSAGE_UPDATE` event is fired to fix this race condition. A certain timeout should be considered as well which Discord does not document.

If this is too abstract for Serenity, this race condition should be documented in the inline docs.

**Comment by kangalio** [comment]
Can't reproduce. Code:

```rust
let mut msg = channel_id.say(&ctx, "https://github.com/serenity-rs/serenity/issues/2333").await?;
msg.edit(&ctx, EditMessage::new().suppress_embeds(true)).await?;
```

Can you provide a minimal reproducible example?

**Comment by oSumAtrIX** [comment]
The race condition is a little rare, but most of the time, it works, though I was able to reproduce the race condition with the following code:

https://github.com/revanced/revanced-discord-bot/blob/main/src/utils/code_embed/utils.rs#L96-L98

**Comment by kangalio** [comment]
> The race condition is a little rare, but most of the time, it works

I just tried 63 times and the embed was successfully suppressed everytime except the very first try - and that one resolved after refreshing, so it was just a client-side display error

I am testing on the next branch, although I'd be surprised if that was the reason for our different results - the sent API requests should have stayed same

**Comment by oSumAtrIX** [comment]
Just to be sure, how does Serenity handle suppressing embeds? I am imagining following scenario:

1. User sends a link
2. Discord server starts parsing the link
3. Serenity suppresses an embed
4. Discord server has not parsed the link yet and therefore dismisses the suppression
5. Embed is displayed on client once Discord finishes parsing

In this scenario we would have a race condition. I can also imagine Discord queuing suppressing the embed before finishing parsing the link. In that case this would not explain, why the first time, the embed was not suppressed in your test case.

As a new test case, a slow loading page can be used to check if there's a race condition. Discord probably only parses until `</head>`, so if the site sends the content slowly the window to suppress the embed to cause a race condition could be higher.

**Comment by kangalio** [comment]
> how does Serenity handle suppressing embeds?

First sends an HTTP request for sending the message, then sends an HTTP request to suppress embeds.

> As a new test case, a slow loading page can be used to check if there's a race condition. Discord probably only parses until </head>, so if the site sends the content slowly the window to suppress the embed to cause a race condition could be higher.

With "Discord", are you referring to the Discord server? Discord API requests do not contain HTML; there's no `</head>` in them. Or are you referring to the Discord client? It receives events via a websocket connection; not via HTML either.

**Comment by oSumAtrIX** [comment]
> Discord API requests do not contain HTML

This is not what I mean. Discord servers parse the website content to get the `<meta>` elements from `<head>`. That way, they can extract data to create the embed. Once the servers parse the website, they send an event to the Discord client to display the embed. This means that the Discord client never parses the website content itself (Otherwise, the client IP would be exposed to the website).

So I imagine you cannot suppress the embed while Discord servers are busy parsing the site (because there is none yet).

**Comment by kangalio** [comment]
Ah I didn't catch that you were talking about parsing the _website content_

Managed to reproduce (very first try in the video, as well as close to end again)

https://user-images.githubusercontent.com/21220820/232015026-5cb5b65a-d90d-4353-8f44-bdda7b0e679b.mp4

```rust
msg.channel_id
    .say(ctx, format!("https://codereview.stackexchange.com/questions/260653/very-slow-discord-bot-to-play-music{}", msg.id.0))
    .await?
    .edit(&ctx, EditMessage::new().suppress_embeds(true))
    .await?;
```

(the ✅ reaction is from the surrounding [`testing`](https://github.com/serenity-rs/serenity/blob/current/examples/testing/src/main.rs) code)

My previous reproduction attempts were flawed because I always used the same URL, but Discord seems to cache embeds per URL

---

> If this is too abstract for Serenity, this race condition should be documented in the inline docs.

I think it is too abstract. If I were a serenity user I'd not expect such bookkeeping to take place behind the scenes implicitly. I agree the race condition should instead be documented, and we can also add an example on how to mitigate this issue yourself, using a collector.

**Comment by oSumAtrIX** [comment]
Sounds good, but I am not entirely sure if it is conventional to put a workaround to a certain issue in the inline docs of an API, instead somewhere externally such as a FAQ, wiki or docs page. 

Closing therefor, unless you insist on adding it to inline docs (if fine in the case of Serenity), feel free to open the issue for tracking purposes in that case. Thanks!

**Comment by kangalio** [comment]
I _would_ have PRed a fix two days ago with the gotcha and the workaround in the docs:

```rust
let msg_id = msg.id;
let mut message_updates = serenity::collector::collect(&ctx.shard, move |ev| match ev {
    Event::MessageUpdate(x) if x.id == msg_id => Some(()),
    _ => None,
});
let _ = timeout(Duration::from_millis(2000), message_updates.next()).await;
msg.edit(&ctx, EditMessage::new().suppress_embeds(true)).await?;
```

But I stumbled into a rabbit hole and discovered serenity's ShardRunner loop is kinda faulty and only checks incoming shard messages every ~500ms, so collector events can get lost. That's messy to fix though, so not sure when that's gonna happen
