### ISSUE TITLE
How to add reaction to an interaction

### ISSUE THREAD

**Issue by ChristianPerez34** [serenity-rs/serenity#2340]
I am using [slash commands example](https://github.com/serenity-rs/serenity/tree/current/examples/e14_slash_commands) as a base to create a discord bot.

Found myself stuck trying to figure out how to add a reaction to the message the bot responds with. Using the following snippet as an example:

```rust
#[async_trait]
impl EventHandler for Handler {
    async fn interaction_create(&self, ctx: Context, interaction: Interaction) {
        if let Interaction::ApplicationCommand(command) = interaction {
            println!("Received command interaction: {:#?}", command);

            let content = match command.data.name.as_str() {
                "ping" => commands::ping::run(&command.data.options),
                "id" => commands::id::run(&command.data.options),
                "attachmentinput" => commands::attachmentinput::run(&command.data.options),
                _ => "not implemented :(".to_string(),
            };

            if let Err(why) = command
                .create_interaction_response(&ctx.http, |response| {
                    response
                        .kind(InteractionResponseType::ChannelMessageWithSource)
                        .interaction_response_data(|message| message.content(content))
                })
                .await
            {
                println!("Cannot respond to slash command: {}", why);
            }
        }
    }

}
```

How could I go about to add reactions to a message the bot responds with?

As an example assume `ping` command (/ping) responds with "pong". I would like to add a reaction to pong.

**Comment by arqunis** [comment]
You will need to retrieve the `Message` object that is generated for the response with [`ApplicationCommandInteraction::get_interaction_response`](https://serenity-rs.github.io/serenity/current/serenity/model/application/interaction/application_command/struct.ApplicationCommandInteraction.html#method.get_interaction_response). You will be then free to use [`Message::react`](https://serenity-rs.github.io/serenity/current/serenity/model/channel/struct.Message.html#method.react) on it.

**Comment by ChristianPerez34** [comment]
> You will need to retrieve the `Message` object that is generated for the response with [`ApplicationCommandInteraction::get_interaction_response`](https://serenity-rs.github.io/serenity/current/serenity/model/application/interaction/application_command/struct.ApplicationCommandInteraction.html#method.get_interaction_response). You will be then free to use [`Message::react`](https://serenity-rs.github.io/serenity/current/serenity/model/channel/struct.Message.html#method.react) on it.

Thanks for the quick reply!

I'm running into a different error where it appears to not be accepting the emoji for some reason.

```rust
let message = ApplicationCommandInteraction::get_interaction_response(&command, &ctx.http)
        .await
        .unwrap();
    println!("{:?}", message);
    // let message = command.get_interaction_response(&ctx.http).await.unwrap();
    message
        .react(&ctx, ReactionType::from_str(":one:").unwrap())
        .await
        .unwrap();
```

I'm running into the following error

```rust
Http(UnsuccessfulRequest(ErrorResponse { status_code: 400, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v10/channels/928283873811509295/messages/1071641460472029215/reactions/:one:/@me", query: None, fragment: None }, error: DiscordJsonError { code: 50035, message: "Invalid Form Body", errors: [DiscordJsonSingleError { code: "NUMBER_TYPE_COERCE", message: "Value \"\" is not snowflake.", path: "emoji_id" }] } }))
```

**Comment by arqunis** [comment]
Reacting with Tweemojis requires using their Unicode value, which for `:one:` is 1️⃣:
```rust
message
    .react(&ctx, ReactionType::Unicode("1️⃣".to_string()))
    .await
    .unwrap();

**Comment by ChristianPerez34** [comment]
Thanks a bunch!
