### ISSUE TITLE
Update bot examples.

### ISSUE THREAD

**Issue by pxp9** [serenity-rs/serenity#2345]
Could you update your bot examples please ?

**Comment by arqunis** [comment]
Could you elaborate on what you mean? How are they outdated, or what are they missing?

**Comment by pxp9** [comment]
My bad, i did not understand at first , the difference between ping bot in README and ping bot in examples.

One of them uses the framework and the other it does not use the framework.

you can close the issue if you want it.

Thank you for your fast response.
