### ISSUE TITLE
Our application can no longer connect to the voice channel.

### ISSUE THREAD

**Issue by abokado0107** [serenity-rs/serenity#2379]
### This can be found in the songbird repository.

**Songbird version:** (version)
0.3.0

**Rust version (`rustc -V`):** (version)
rustc 1.65.0 (897e37553 2022-11-02)

**Serenity/Twilight version:** (version)
Serenity 0.11.5

**Output of `ffmpeg -version`, `yt-dlp --version` (if relevant):**
ffmpeg version 4.2.4-1ubuntu0.1

**Description:**
Our application can no longer connect to the voice channel.
To be more precise, it connects, but we can no longer speak.
```
<unknown time> DEBUG runner{config=Config { crypto_mode: Normal, decode_mode: Decrypt, gateway_timeout: Some(10s), preallocated_tracks: 1, driver_retry: Retry { strategy: Backoff(ExponentialBackoff { min: 250ms, max: 10s, jitter: 0.1 }), retry_limit: Some(5) }, driver_timeout: Some(10s) }}: /home/renne/.cargo/registry/src/github.com-1ecc6299db9ec823/songbird-0.3.0/src/driver/connection/mod.rs:335: Expected ready for key; got: op5/vSpeaking(Speaking { delay: None, speaking: MICROPHONE, ssrc: 5166, user_id: Some(UserId(438191250437308417)) })
<unknown time> DEBUG runner{config=Config { crypto_mode: Normal, decode_mode: Decrypt, gateway_timeout: Some(10s), preallocated_tracks: 1, driver_retry: Retry { strategy: Backoff(ExponentialBackoff { min: 250ms, max: 10s, jitter: 0.1 }), retry_limit: Some(5) }, driver_timeout: Some(10s) }}: /home/renne/.cargo/registry/src/github.com-1ecc6299db9ec823/songbird-0.3.0/src/driver/tasks/mod.rs:300: Failed to connect for GuildId(940648772772442143): failed to connect to Discord RTP server: websocket issue (Json(Error("invalid value: integer `18`, expected opcode in [0--9] + [12--13]", line: 1, column: 8))).
```

From the log above, it is possible that something called `opcode 18` is being sent and it is no longer working properly.

**Steps to reproduce:**

Songbird sample code doesn't work.

https://github.com/serenity-rs/songbird/blob/current/examples/serenity/voice/src/main.rs

Work:
Connect to VC normally.

**Comment by Erk-** [comment]
See https://github.com/serenity-rs/songbird/pull/170

**Comment by kangalio** [comment]
Songbird 0.3.2 has been released with the fix to this issue https://github.com/serenity-rs/songbird/releases/tag/v0.3.2
