### ISSUE TITLE
Upgrading from version 0.10 to 0.11 results in an unresponsive bot

### ISSUE THREAD

**Issue by asg0451** [serenity-rs/serenity#2386]
Today I started seeing errors from Songbird due to a Discord API change, so I wanted to upgrade to the latest version of Songbird, which entails upgrading Serenity too. However, when i just increment the version and make the minor changes required to get it to compile, the bot is completely unresponsive to commands, even when looking at `trace`-level logs.

**Comment by kangalio** [comment]
Have you set the correct gateway intents? In particular it sounds like you could be missing MESSAGE_CONTENT

**Comment by asg0451** [comment]
Ok so adding message_content didnt do it, but i looked at the logs for the old version, saw the intents it requested, and added those manually to the new code, and that works. thanks!
