### ISSUE TITLE
Flatten serenity::model

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#2394]
It would be better if all model types were accessible via just `serenity::model::ModelType`. I don't think anyone can remember which serenity::model submodule a model type belongs to.

This would also make the job of `serenity::model::prelude` redundant.

A few types should be renamed to be less ambiguous, like `Rule` and `Options`.

There should ideally be redirects from the old paths to the new paths.

This needs to wait until at least after #2393

**Comment by mkrasnitski** [comment]
I'd nominate this to go into 0.13 - since literally every user interacts with the model in some way, this is a breaking change that would be widely felt, and we're already loaded pretty heavy on those for 0.12.

**Comment by kangalio** [comment]
Good point, I agree

**Comment by kangalio** [comment]
We could also just add `pub use submodule::*;` for every model submodule. That way, the old paths stay accessible perfectly accessible, but `serenity::model::ModelType` also works. That's how I do it in poise: https://docs.rs/poise/latest/poise/#reexports.

What do you think about that?

I think this feature would be very nice for new code written using serenity, to avoid noisy long paths and duplicate-ish imports.

**Comment by ivinjabraham** [comment]
Is this intended to be open after [this message](https://github.com/serenity-rs/serenity/pull/2419#issuecomment-1544304653) by @mkrasnitski?

**Comment by GnomedDev** [comment]
Doesn't look like it.
