### ISSUE TITLE
why is the initial connection so slow?

### ISSUE THREAD

**Issue by loshtbh** [serenity-rs/serenity#2407]
Code Snippet

```rust
pub async fn load(token: String, cx: broadcast::Sender<()>) -> Result<Client> {
    let intents = GatewayIntents::GUILD_MESSAGES | GatewayIntents::MESSAGE_CONTENT; 
    let client = Client::builder(&token, intents).event_handler(Handler::new(cx)).await?;
    Ok(client)
}
```

it sometimes takes 2-3 mins for the client to connect and invoke `async fn ready(&self, _: Context, ready: Ready)`,
am i doing something wrong?

**Comment by kangalio** [comment]
Can you show the code that calls `load()`? Maybe that's what's slow. I don't see why the code you posted should be slow

**Comment by loshtbh** [comment]
> Can you show the code that calls `load()`? Maybe that's what's slow. I don't see why the code you posted should be slow

hey! i forgot to close this, i had dns issues with my server, rebooting and switching to cloudfare dns fixed it :)
