### ISSUE TITLE
EventHandler: message never getting triggered

### ISSUE THREAD

**Issue by connorcinna** [serenity-rs/serenity#2408]
Serenity version: 0.11.5

Rust version (`rustc -V`): rustc 1.68.2 (9eb3afe9e 2023-03-27)

Minimal test case if possible: 
Sending any message in the text channel does not trigger my message EventHandler.
I also have interaction_create and ready EventHandlers that work as expected with slash commands and on startup. 

Here's my code for message: 

```rust
async fn message(&self, ctx: Context, msg: Message) {
        println!("Reached Message Handler");
        msg.channel_id.say(&ctx.http, "Hello").await.expect("Unable to send message to channel.");
}
```

Nothing is output in the channel or in my console. My bot has 'bot' and 'application.commands' scope with Administrator permissions. Any help is very appreciated!

**Comment by arqunis** [comment]
Do you have the [`GUILD_MESSAGES`](https://serenity-rs.github.io/serenity/current/serenity/model/gateway/struct.GatewayIntents.html#associatedconstant.GUILD_MESSAGES) intent enabled?

**Comment by connorcinna** [comment]
That fixed it. I thought the default non-privileged permissions were already there, but I needed to 'OR' them with the privileged ones I was using. Thanks!
