### ISSUE TITLE
How to share a HashMap using client.data?

### ISSUE THREAD

**Issue by LuckyMika** [serenity-rs/serenity#2411]
I am trying to share a HashMap with a String and an asynchronous function between the `main` function and the Eventhandler for my own command framework. I am pretty new to rust and any help on this would be apreciated.

**Comment by kangalio** [comment]
If you're making your own framework, you don't need `client.data` (it's a bit clunky so I wouldn't recommend it if not needed). You can store it in the EventHandler as a struct field instead. Example:

```rust
struct Handler {
    hashmap: Arc<Mutex<HashMap<...>>>,
}
impl EventHandler for Handler {
    ...
}

async fn main() {
    let handler = Handler {
        hashmap: Arc::new(Mutex::new(HashMap::new())),
    };

    Client::builder()
        .handler(handler)
        ...
}
```

To access the hashmap within the handler, call `self.hashmap.lock()`

If you don't need to modify the hashmap after creation, you don't need the Mutex. And if the main function doesn't need access to the hashmap after starting the serenity client, you don't need the Arc

**Comment by LuckyMika** [comment]
Thank you for the answer! My problem is that, since I am trying to share an async function, it can't be shared between threads safely. My type for the function looks like this
```rust
type Command = Box<dyn Fn(Context, Message) -> Pin<Box<dyn Future<Output = bool>>>>;
```
How could I make this shareable between threads?

**Comment by kangalio** [comment]
Add a Send (and Sync?) bound to the dyn Fn

**Comment by LuckyMika** [comment]
I actually figured it out and added + Send and everything is working now. Thank you for your help
