### ISSUE TITLE
Question about on message events

### ISSUE THREAD

**Issue by ehuff700** [serenity-rs/serenity#2416]
Is there any way to listen for message events within the context of a channel outside of using the function "message" within the EventHandler? For context on my use case, I'm trying to listen for a message within a channel and perform some actions based on the message content. I found the ChannelId.messages_iter() method but this doesn't seem to actively stream for messages.

**Comment by kangalio** [comment]
Check MessageCollector https://docs.rs/serenity/latest/serenity/collector/message_collector/struct.MessageCollectorBuilder.html
