### ISSUE TITLE
Is it time for a new release version bump?

### ISSUE THREAD

**Issue by PeterGrace** [serenity-rs/serenity#2427]
Hi!

I notice that there's been work in HEAD that hasn't been rolled up into a library version release.  One of those features (forum-thread-related activities) is something I would like to use in my bot.  I prefer to pin my versions and not use a git reference to the main branch.  

Is there anything I can do to help test any remaining "we're not sure if this works yet" type items?

**Comment by GnomedDev** [comment]
The only thing stopping a release currently seems to be release notes being written, which I think there is an open PR for.

**Comment by kangalio** [comment]
I think they're referring to the 74 unreleased commits on `current` https://github.com/serenity-rs/serenity/compare/v0.11.5...current

I think it would be a good idea to release those as 0.11.6, perhaps at the same time with 0.12. Because 0.12 has so many breaking changes, many people will stay on 0.11 for a while

**Comment by PeterGrace** [comment]
Hi @GnomedDev, @kangalio , just curious to hear whether there's more parties needed for quorum on this decision?  Thanks for your contributions to this project!

**Comment by OvermindDL1** [comment]
Is it just the release notes that's holding it back or is something else needing to happen, like something needing to be finished first?

**Comment by arqunis** [comment]
For v0.11.6, there weren't hard blockers. I had mostly been waiting if new pull requests were going to be made for the `current` branch, but the momentum for those on `current` has died down, so I've just released [v0.11.6](https://crates.io/crates/serenity/0.11.6) on crates.io.
