### ISSUE TITLE
command_attr lacks some of the Discord Permissions

### ISSUE THREAD

**Issue by CmdrSharp** [serenity-rs/serenity#2434]
**The following are missing** (https://discord.com/developers/docs/topics/permissions). If there's a reason for any of them not being added / available, I think that should be documented.

- CREATE_INSTANT_INVITE
- STREAM
- VIEW_CHANNEL
- VIEW_GUILD_INSIGHTS
- MANAGE_GUILD_EXPRESSIONS
- USE_APPLICATION_COMMANDS
- MANAGE_EVENTS
- MANAGE_THREADS
- CREATE_PUBLIC_THREADS
- CREATE_PRIVATE_THREADS
- USE_EXTERNAL_STICKERS
- SEND_MESSAGES_IN_THREADS
- USE_EMBEDDED_ACTIVITIES
- MODERATE_MEMBERS
- VIEW_CREATOR_MONETIZATION_ANALYTICS
- USE_SOUNDBOARD
- SEND_VOICE_MESSAGES

**The following are documented here but not on the Discord site.** If they're intended to be supported, I think they should be documented.

- PRESET_GENERAL
- PRESET_TEXT
- PRESET_VOICE
- CREATE_INVITE (perhaps replaced by CREATE_INSTANT_INVITE?)

Finally; these are already added in [src/model/permissions.rs](https://github.com/serenity-rs/serenity/blob/1ba2346ce629cd0e4f3c8c24e8830c22d08fedc7/src/model/permissions.rs#LL222C7-L222C7) with their bitflags (which are documented on the Discord site and thus easy to update). If there's no special reason to; perhaps they shouldn't be added twice, in different places, using different formats?

**Comment by tazz4843** [comment]
> If there's a reason for any of them not being added / available, I think that should be documented.

Looks like the last time these were updated was just over a year ago, adding stickers, which predates a lot of the missing permissions: https://github.com/serenity-rs/serenity/commit/34bc5fec302c1f66cc851d6626f04a8831c4f8b2
