### ISSUE TITLE
Does AttachmentType::Bytes send correct Content-Type?

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#2439]
@joshument:
> Does anyone know how to get a file to embed?
> It seems like any mention of images requires uploading it somewhere first but if I can't use the discord CDN then I'd have to run my own https server along with the bot
> [...]
> Figured it out
> had to save it as a file and then use AttachmentType::Path

@kangalio 
> then it embedded as a file, but not before?? that's weird
> which AttachmentType variant did you use before? 

@joshument
> Bytes
> I tried loading from memory cause I had it in memory

@kangalio 
> okay and with Bytes, the file didn't embed, but with Path, it does?
> screams like wrong Content-Type on serenity's side

@joshument
> I'll have to double check again
> But I think so

https://discord.com/channels/381880193251409931/919310428344029265/1109085020414541846

**Comment by jlabbude** [comment]
Tried `CreateAttachment::bytes` and encountered the exact same issue, had to use `CreateAttachment::file` as well for it to work.

**Comment by ivinjabraham** [comment]
@jlabbude I took a look at your repository and I don't think there's a bug. `CreateAttachment::bytes` expects the file data to be passed, but in your use case `DynamicImage::into_bytes()` only returns the image's pixels as a byte vector and leaves out the file headers.

`CreateAttachment::file` still uses `CreateAttachment::bytes` so it is unlikely there is a fault with latter.

**Comment by ivinjabraham** [comment]
I think this issue has already been addressed in aad35f4. Seems like a misunderstanding of the expected parameters of `send_file`.

**Comment by GnomedDev** [comment]
It seems like no one has run into this issue since the attachment rework, or it may never have been an issue. If anyone runs into this again, feel free to ping me and I'll re-open the issue.
