### ISSUE TITLE
Document or automate `attachment://` URLs in embeds

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#2440]
![Screenshot_20230520_102552](https://github.com/serenity-rs/serenity/assets/21220820/81bb0c9f-0586-4327-a073-579d51b520cb)
[Link](https://discord.com/developers/docs/reference#editing-message-attachments-using-attachments-within-embeds)

Serenity should either document this, or CreateEmbed should automatically move attachments it receives into the multipart form data and generate the `attachment://` URL

[Context](https://discord.com/channels/381880193251409931/381912587505500160/1109320645134782484)
[Another instance](https://discord.com/channels/381880193251409931/381912587505500160/1110949279029276755)

**Comment by NightFeather0615** [comment]
The first context should work fine without attachments (at least on my machine), Discord embed supports HTTP(S) URLs by default.

I notice that [`CreateEmbed`](https://docs.rs/serenity/latest/serenity/builder/struct.CreateEmbed.html) has a function called [`attachment`](https://docs.rs/serenity/latest/serenity/builder/struct.CreateEmbed.html#method.attachment) but it seems to set the attachment to embed's image, is there a [FAQ page like discord.py](https://discordpy.readthedocs.io/en/stable/faq.html#local-image) that we can use to provide a tutorial for local images?

By the way, the embed's author section doesn't seem to show up if you don't have a name set.

**Comment by GnomedDev** [comment]
Looks like this is already a thing with `CreateEmbed::attachment`, a helper for `CreateMessage` would just be a leaky abstraction imo. If anyone disagrees, feel free to let me know and I'll re-open the issue.
