### ISSUE TITLE
Select Menu does not include User Select, Role Select, Mentionable Select, or Mentionable Select

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#2450]
The select menu builder does not include User Select, Role Select, Mentionable Select, or Channel Select. It only seems to have the String select.  

The full list from [Discord's API](https://discord.com/developers/docs/interactions/message-components#component-object-component-types) can be seen in the image below. 

![image](https://github.com/serenity-rs/serenity/assets/19809270/e29630f6-87e4-4f92-bc84-0b2ecbbc59fa)

I was creating a menu like the following 

![image](https://github.com/serenity-rs/serenity/assets/19809270/1bacdf49-0fab-4c94-bee1-ab508073c097)

When I noticed Discord has a menu for it in their API.

![image](https://github.com/serenity-rs/serenity/assets/19809270/75d5d562-17db-4609-bd9d-6d241ddec547)

**Comment by ghost** [comment]
I created a quickly modified version in [this commit](https://github.com/world177/serenity/commit/5151f901b80506e70f07bba4eeaf43b3d0fce7d7). I think this is only half of what is required for it. I think it still needs the "[resolved object](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-resolved-object)."

![image](https://github.com/serenity-rs/serenity/assets/19809270/189a6efe-d15b-4bf8-a8cd-74d5fd80e092)

![image](https://github.com/serenity-rs/serenity/assets/19809270/18c4dee1-1650-4416-af8a-54e48248f70a)

It has a lot of duplicated code, but Discord also seems to be treating the different select options as their own component types. So, I felt like this approach was probably more future proof to changes. I didn't really test it yet, but they do seem to all have a bot respond with the correct select menu.

**Comment by GnomedDev** [comment]
As mentioned in the closed PR above, this was added in #2224.
