### ISSUE TITLE
Using colour variables in embed_error_colour and embed_success_colour attributes in the help macro

### ISSUE THREAD

**Issue by Delta-official** [serenity-rs/serenity#2458]
Currently it doesn't seem to be possible to use a `Colour` instance (like the ones defined in `utils::colours`) in the `embed_error_colour` and `embed_success_colour` attributes in the `help` macro. It would be nice to have such functionality.

**Comment by GnomedDev** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
