### ISSUE TITLE
Possibly old information in example README

### ISSUE THREAD

**Issue by AurumTheEnd** [serenity-rs/serenity#2469]
Hi, just started working with this crate and going through the examples. I noticed the following text in [examples/e16_sqlite_database/README.md](https://github.com/serenity-rs/serenity/blob/9fc3f1180ddee5526a78c6e72deaaa9dd7be1f03/examples/e16_sqlite_database/README.md):

![image](https://github.com/serenity-rs/serenity/assets/47597303/2af4b0ce-689b-4e13-b835-9f9a2a21f846)

Does that still apply? The last commit of the README is 2 years old, but since there is no tracking number for the bug on SQLX's side, I don't know enough to verify if it still persists.

**Comment by kangalio** [comment]
Good point, I should have added a link to check on the issue. Rummaging through my browser history, I found https://github.com/launchbadge/sqlx/issues/1260 which links to https://github.com/launchbadge/sqlx/issues/1399, both of which are still open

If you have the time, you could open a PR to add these links to the comments :))
