### ISSUE TITLE
[bug/branch:next] `max_length` and `min_length` have incorrect signature

### ISSUE THREAD

**Issue by matteopolak** [serenity-rs/serenity#2476]
[`CreateCommandOption#max_length`](https://github.com/serenity-rs/serenity/blob/next/src/builder/create_command.rs#L268) and [`CreateCommandOption#min_length`](https://github.com/serenity-rs/serenity/blob/next/src/builder/create_command.rs#L259) both take `&mut self` and return `&mut Self`, instead of `mut self` and `Self` respectively, as per all of the other builder methods in the new `next` branch.

Is this intentional, or should these be changed?

**Comment by mkrasnitski** [comment]
This is unintentional, and was missed as part of the builder rework as those methods were added to `current` while the rework PR was still open. Subsequent rebases missed changing the signatures.
