### ISSUE TITLE
Can't get a list of members from a GuildChannel

### ISSUE THREAD

**Issue by johnedmonds** [serenity-rs/serenity#2483]
Example code in the `ready` method:

```rust
async fn ready(&self, ctx: Context, ready: Ready) {
    println!("{:?}", ready.guilds.clone().into_iter().next().unwrap().id.channels(&ctx.http).await.unwrap().into_iter().next().unwrap().1.members(&ctx.cache).await);
}
```

This prints out
```
Err(Model(GuildNotFound))
```

**Comment by Phant80m** [comment]
funily enough i tried something similar and it also didnt like it.

**Comment by johnedmonds** [comment]
Looked into this and it could be happening because the `ready` event only sends guilds as "unavailable." Theoretically, the API should follow up with "Guild Created" events when the guild becomes available so maybe the code should check there. I haven't confirmed this theory yet though.

**Comment by arqunis** [comment]
This is true. Discord does not send the data of all the guilds your bot is in upon connecting to the gateway and receiving the `READY` event. This happens gradually as `GUILD_CREATE` events are rolled out for each guild after `READY`. There's the [`cache_ready`](https://serenity-rs.github.io/serenity/current/serenity/prelude/trait.EventHandler.html#method.cache_ready) event you can use instead, which is dispatched after the cache has been populated with data of all the guilds.

**Comment by johnedmonds** [comment]
I've confirmed that this is how it works. This is probably worth documenting but I'll close this since it's not an issue anymore.
