### ISSUE TITLE
Canary webhooks marked as invalid

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#2491]
Serenity version: 0.11.6

Rust version: rustc 1.71.0-nightly (1a6ae3d69 2023-04-27)

Webhooks copied from discord canary are mistakenly marked as invalid. I didn't include the backtrace because it's just tokio.

Test case:
```rs
use serenity::http::Http;
use serenity::model::webhook::Webhook;

#[tokio::main]
async fn main() {
    let hook = "https://canary.discord.com/api/webhooks/id/token";

    let http = Http::new("");
    let _webhook = Webhook::from_url(&http, hook).await.expect("invalid hook");
}
```

**Comment by HexPandaa** [comment]
Should be fixed with #2499
