### ISSUE TITLE
Crate does not build with just `http` and `builder` features enabled

### ISSUE THREAD

**Issue by jonhoo** [serenity-rs/serenity#2494]
```console
$ tail -n2 Cargo.toml
[dependencies]
serenity = { version = "0.11.6", default-features = false, features = ["http", "builder", "rustls_backend"] }
$ cargo check
   Compiling serenity v0.11.6
error[E0405]: cannot find trait `CacheHttp` in this scope
   --> /home/jon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serenity-0.11.6/src/model/channel/mod.rs:170:49
    |
170 |     pub async fn delete(&self, cache_http: impl CacheHttp) -> Result<()> {
    |                                                 ^^^^^^^^^ not found in this scope
    |
help: consider importing this trait
    |
16  + use crate::http::CacheHttp;
    |

For more information about this error, try `rustc --explain E0405`.
error: could not compile `serenity` (lib) due to previous error
```

This happens because `fn delete` (which is `cfg(feature = "http")`) tries to use `CacheHttp`:
https://github.com/serenity-rs/serenity/blob/ca8f28831e5a708cba03c7c61687a6d607a5fd56/src/model/channel/mod.rs#L169-L170

but that trait is only imported with `cfg(feature = "model")`:
https://github.com/serenity-rs/serenity/blob/ca8f28831e5a708cba03c7c61687a6d607a5fd56/src/model/channel/mod.rs#L35-L36

Trying to add `model` to the list of features produces lots of more compiler errors. The same happens if you fail to include the `builder` feature.

**Comment by jonhoo** [comment]
The issue that comes up if the `model` feature is then added is that this impl doesn't exist, which causes lots of other things to fail to build:
https://github.com/serenity-rs/serenity/blob/ca8f28831e5a708cba03c7c61687a6d607a5fd56/src/lib.rs#L133-L134

But enabling _that_ feature causes other things not to build due to the lack of the `gateway` feature. Adding `gateway` does finally allow the crate to build.

**Comment by mkrasnitski** [comment]
The situation is slightly better on the `next` branch, which is nearing an imminent release of 0.12. The `model` feature (plus a choice of tls backend) is enough to build, although replacing `model` with just `http` + `builder` is still not enough.
