### ISSUE TITLE
`Member.remove_role()` appears to stop working after prolonged uptime

### ISSUE THREAD

**Issue by nryanl** [serenity-rs/serenity#2501]
## Description
[`.remove_role()`](https://github.com/serenity-rs/serenity/blob/ca8f28831e5a708cba03c7c61687a6d607a5fd56/src/model/guild/member.rs#L527-L550) fails to remove role from guild member. This occurs somewhat randomly after a prolonged uptime of ~100hrs / ~3-5 days.

## Possible Causes
After looking inside the `.remove_role()` function, we suspect this is either due to the `Member.roles` being incorrect and not containing the role we are trying to remove. Causing [this section](https://github.com/serenity-rs/serenity/blob/ca8f28831e5a708cba03c7c61687a6d60.7a5fd56/src/model/guild/member.rs#L534-L536) of the `.remove_role()` function to tell us the role was removed successfully when it actually failed to remove the role. This is alarming as we have removed the cache feature from Cargo.toml and so it cannot be an out of sync cache.

Our other theory is that [`.remove_member_role()`](https://github.com/serenity-rs/serenity/blob/ca8f28831e5a708cba03c7c61687a6d607a5fd56/src/model/guild/member.rs#L540) may be failing to remove the role successfully.

## What we're trying
```rust
info!("Roles that member {} has: {:?}", member.user.name, member.roles); 
if !member.roles.contains(&role_id) {
    warn!("Attempting to remove role from user {} that is not contained in member roles.", member.user.name);
}

match member.remove_role(&ctx, role_id).await {
    Ok(_) => {
        info!("Removed role {} from {} in guild {}", role_id, result.user_id, guild.id);
    },
    Err(_) => {
        warn!(
            "Failed to remove role from member \"{}\"",
            member.user.name
        );
        continue;
    }
}
```

Per the code snippet above, we have now set logs to tell us when this issue happens again, if it is because `Member.roles` does not contain the role we are trying to remove.

We will update whether that is the case when this issue happens again.

**Comment by nryanl** [comment]
Updating this issue:

I believe `Member.roles` is not updating correctly.
![image](https://github.com/serenity-rs/serenity/assets/107244904/fbcd067e-05c3-4a1e-a53d-0cbd676e8cf7)

Event log:
1) User was given role and was logged.
2) After 1 minute, the bot attempted to take away the role, entering
```rust
if !member.roles.contains(&role_id) {
    info!("Attempting to remove role from user {} that is not contained in member roles.", member.user.name);
}
```
and logging this failure. 
3) The bot fails to remove the role, as the user profile on the Discord client still lists the user as having the role.
4) The bot logs a successful role removal, or an `Ok` from `.remove_role()`

**Comment by anden3** [comment]
Guessing the role data comes from the gateway?
Does it appear if you fetch the member data via Http?

**Comment by sloganking** [comment]
> Guessing the role data comes from the gateway? Does it appear if you fetch the member data via Http?

@anden3 I am working with @nryanl on this. 

Member is gotten from a call to `guild.member()` so our full code is

```rust
let mut member = match guild.member(&ctx, result.user_id).await {
    Ok(n) => n,
    Err(_) => {
        warn!("Failed to get member {} from guild", result.user_id);
        continue;
    }
};

info!("Roles that member {} has: {:?}", member.user.name, member.roles); 
if !member.roles.contains(&role_id) {
    info!("Attempting to remove role from user {} that is not contained in member roles.", member.user.name);
} else {
    info!("!member.roles.contains(&role_id) was false and entered the else bracket.");
}
//remove role
match member.remove_role(&ctx, role_id).await {
    Ok(_) => {
        info!("Removed role {} from {} in guild {}", role_id, result.user_id, guild.id);
    },
    Err(_) => {
        info!(
            "Failed to remove role from member \"{}\"",
            member.user.name
        );
        continue;
    }
}
```

`guild.member()` (a serenity function and the thing we get a `Member` from) basically boils down to

```rust
pub async fn member(
    self,
    cache_http: impl CacheHttp,
    user_id: impl Into<UserId>,
) -> Result<Member> {
    let user_id = user_id.into();

    #[cfg(feature = "cache")]
    {
        if let Some(cache) = cache_http.cache() {
            if let Some(member) = cache.member(self.0, user_id) {
                return Ok(member);
            }
        }
    }

    cache_http.http().get_member(self.0, user_id.0).await
}
```

And we have cache feature disabled. So the only thing happening in this function should be the call to `cache_http.http().get_member(self.0, user_id.0).await`

which when opened looks like 

```rust
pub async fn get_member(&self, guild_id: u64, user_id: u64) -> Result<Member> {
        let mut value = self
            .request(Request {
                body: None,
                multipart: None,
                headers: None,
                route: RouteInfo::GetMember {
                    guild_id,
                    user_id,
                },
            })
            .await?
            .json::<Value>()
            .await?;

        if let Some(map) = value.as_object_mut() {
            map.insert("guild_id".to_string(), from_number(guild_id));
        }

        from_value::<Member>(value).map_err(From::from)
    }
```

Looking at the function above, as far as I can tell `get_member()` just sends an http request to the discord API, receives a json response and parses it. So unless I am misunderstanding something here, it looks like the discord API is sending back incorrect data? I'm not sure how that would be possible though, considering I assume the Discord desktop client and serenity bots use the same discord API.

**Comment by sloganking** [comment]
> 
The logs in @nryanl 's comment may be unclear. But basically when we attempt to remove a `roleId` from a `Member`, that member's `Member.roles` vector does not contain the `RoleId` we are trying to remove, even though the discord desktop client says that member has that role. 

Causing this part of the `remove_role()` function to say that the role was removed, when actually it was not. 
https://github.com/serenity-rs/serenity/blob/fe5febf9d21d77202737e00ca91066adb7f35f18/src/model/guild/member.rs#L534-L536

`remove_role()` doesn't have a bug in it per say. But the fact that the Member has a role, but that role is not listed in its `Member.roles` vector, is a bug.

**Comment by sloganking** [comment]
To test if this is a bug with `serenity` / `poise`, or the discord API. We could try writing a python bot that is put on the same server, and whenever we notice the rust bot is out of sync with the desktop client, we could have the python bot run a command to list the roles that a Member has. Thus getting the perspectives of two bots written in different languages but supposedly interacting with the same API. 

Does anyone have a better idea?

===

The above could not be a good test if the two bots talk to the same API but the API calls are re-directed to different discord back end servers (not a different guild). But I am not sure if that would be the case or how any of that works.

**Comment by nryanl** [comment]
This issue appears to be resolved after adding the GUILD_MEMBERS intent. (338+ hrs uptime, no problem)

**Comment by GnomedDev** [comment]
Without the members intent it is expected that member information goes out of sync after a while, after #2622 is merged though this should be fixed as it will use the dedicated endpoint for "remove this role" and isn't relying on cache at all. @nryanl
