### ISSUE TITLE
Custom activity

### ISSUE THREAD

**Issue by CodeDoctorDE** [serenity-rs/serenity#2505]
Recently discord launched the custom activity state: https://discord.com/developers/docs/change-log#activity-state-for-bot-users.
https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types

It would be nice if this library supports this activity type

**Comment by tazz4843** [comment]
Support already exists on `next`: #2503

This can't be backported to current though, as it includes breaking changes.

**Comment by CodeDoctorDE** [comment]
Okay thanks. Now I need to wait until poise updates to the latest next.
