### ISSUE TITLE
Shutdown is broken on `next` branch

### ISSUE THREAD

**Issue by scottbot95** [serenity-rs/serenity#2507]
Since the revert of #2400 in #2486, it is impossible to shutdown a serenity bot without killing the process. Calling `ShardManager.shutdown_all()` will hang forever and results in the following warning being logged:
```
WARN shutdown_all:shutdown{shard_id=ShardId(0) code=1000}: serenity::gateway::bridge::shard_manager: 287: Failed to cleanly shutdown shard 0, reached timeout: Elapsed(())
```

**Comment by tazz4843** [comment]
See #2523 as a possible fix

**Comment by kangalio** [comment]
#2523 confirmed stable by @tazz4843 

![image](https://github.com/serenity-rs/serenity/assets/21220820/f7051397-0b00-4ab9-9a6d-ddc4a74fc82e)
