### ISSUE TITLE
My discord bot can't see a person joining the server.

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#2512]
I try the following function but nothing happens:

  

```
async fn guild_member_addition(&self, ctx: Context, _guild_id: GuildId, new_member: Member) {
          let welcome_channel_id: u64 = 1136916857765498900; 
  
          let channel_id = ChannelId(welcome_channel_id);
          if let Err(why) = channel_id.say(&ctx.http, format!("Welcome to the server, {}!", new_member.user.name)).await {
              println!("Error sending message: {:?}", why);
          }
      }
```

I gave the bot admin rights, so it should have all the necessary permissions.

**Comment by Jakob5358** [comment]
Are you using the intent GatewayIntents::GUILD_MEMBERS?

You need to enable it both in your code and on the discord developer portal as it's a priveliged intent.

![image](https://github.com/serenity-rs/serenity/assets/75086936/59e30a95-9e26-4232-b640-f5cadccc7961)

**Comment by ghost** [comment]
I already did this but it didn't fix the problem

**Comment by c-git** [comment]
@Nazhik123 is the code publicly available so I can try to reproduce the problem?

**Comment by kangalio** [comment]
Closing because no response, will re-open on a reply
