### ISSUE TITLE
No way to make a non-event based bot.

### ISSUE THREAD

**Issue by Bjohnson131** [serenity-rs/serenity#2518]
Hello, I'd like to make a bot that will turn on, do some work, then quit. An example of this might be, say, counting the number of users currently active on the server, and updating a counter somewhere. Currently, either it is not possible to make such a bot, or none of the examples feature this ability. 

I'd like to request one-shot / cron-triggered event architecture. 
Thank you.

**Comment by BradG13542** [comment]
Hey, would the [`http`](https://docs.rs/serenity/latest/serenity/http/index.html) module help in this case? Something along the lines of:
```rust
use serenity::http::client::Http;

let client = Http::new("<your-bot-token>");

// wait until it's time to start...

let guild = client.get_guild_with_counts("<your-guild-id>");

// set counter to guild.approximate_presence_count
```

I haven't used this crate in a while but hopefully this'd help at least a little :)

**Comment by Bjohnson131** [comment]
I'll check this out! thank you!

**Comment by Bjohnson131** [comment]
Closing- the above method works ^^
