### ISSUE TITLE
Enhancement - Custom Statuses

### ISSUE THREAD

**Issue by Paddyk45** [serenity-rs/serenity#2546]
Recently, Discord added the ability to set a custom status to the bot API, it would be nice to have this feature in serenity

**Comment by jamesbt365** [comment]
It is supported. https://serenity-rs.github.io/serenity/current/serenity/model/prelude/enum.ActivityType.html

**Comment by Paddyk45** [comment]
> It is supported. https://serenity-rs.github.io/serenity/current/serenity/model/prelude/enum.ActivityType.html

That's the enum, there is no `Activity::custom()` though

**Comment by kangalio** [comment]
https://discord.com/developers/docs/change-log#activity-state-for-bot-users
![Screenshot_20230924_220650](https://github.com/serenity-rs/serenity/assets/21220820/99474a22-83d4-4e9d-95ca-51bff6d8feec)

**Comment by tazz4843** [comment]
Added in #2503 about a month ago: https://serenity-rs.github.io/serenity/next/serenity/model/prelude/enum.ActivityType.html

Switch to the next branch to use it: see https://serenity-rs.github.io/serenity/next/serenity/gateway/struct.ActivityData.html
