### ISSUE TITLE
`allowed_roles` doesn't seem to do anything

### ISSUE THREAD

**Issue by paavohuhtala** [serenity-rs/serenity#2549]
I'm trying to limit specific commands to specific users, but `allowed_roles` doesn't seem to have any effect, not on `#[group]` s nor individual `#[command]` s. I didn't find any open issues about this, except for #941 from 2020. I also tried defining multiple roles and just one role, and with roles that have already been created on the server and ones that don't exist. I also tried with `#[owner_privilege(false)] ` to see if the owner of the bot is always allowed to do everything, but that didn't seem to affect it either.

I'm using `version = "0.11"` with default features enabled, running on Windows 11 with rustc 1.72.1.

Here's a minimal repro extracted from my actual application, requring `DISCORD_TOKEN` to be set as an env variable:

```rust
use serenity::framework::standard::macros::{command, group};
use serenity::framework::standard::CommandResult;
use serenity::framework::StandardFramework;
use serenity::model::prelude::Message;
use serenity::prelude::*;

#[group]
#[commands(foo)]
#[allowed_roles("Test Admin")]
struct AdminOnly;

#[command]
async fn foo(ctx: &Context, msg: &Message) -> CommandResult {
    msg.reply(ctx, "Bar").await?;
    CommandResult::Ok(())
}

#[tokio::main]
async fn main() {
    let intents = GatewayIntents::non_privileged() | GatewayIntents::MESSAGE_CONTENT;
    let framework = StandardFramework::new()
        .configure(|c| c.prefix("!"))
        .group(&ADMINONLY_GROUP);

    let mut client = Client::builder(std::env::var("DISCORD_TOKEN").unwrap(), intents)
        .framework(framework)
        .await
        .unwrap();

    client.start().await.unwrap();
}
```

**Comment by paavohuhtala** [comment]
Looks like `allowed_roles` doesn't do anything when the bot is called by its owner on a server owned by the same user, but it did work when invited to a different server. So it looks like the more accurate issue is that  `#[owner_privilege(false)]` doesn't do anything on the owner's own server, unless this is by design.

**Comment by jamesbt365** [comment]
Well you have Administrator on servers you own, so this is probably by design.

**Comment by arqunis** [comment]
> [...] so this is probably by design

Yes, [this behaviour is intended](https://github.com/serenity-rs/serenity/blob/current/src/framework/standard/parse/mod.rs#L255). The role check is skipped if the server owner/administrator is invoking the command.
