### ISSUE TITLE
optional `description` field missing in `CreateAttachment`

### ISSUE THREAD

**Issue by Kneemund** [serenity-rs/serenity#2563]
Specifying a `description` for attachments when uploading or editing messages is currently not possible, because `CreateAttachment` does not support this optional field. 

The content of field is displayed as the image description/alt text when uploading image attachments. 

### Further References
- [API Attachment Object](https://discord.com/developers/docs/resources/channel#attachment-object)
- [API Example Payload](https://discord.com/developers/docs/reference#editing-message-attachments-example-request-bodies-multipartformdata)

**Comment by kangalio** [comment]
Implemented in #2575. Thank you for the initial work!
