### ISSUE TITLE
Guild's member permissions field is always empty

### ISSUE THREAD

**Issue by fulviodenza** [serenity-rs/serenity#2584]
Hi, I'm working on a bot using the serenity library.
I've encountered an issue while implementing a custom command, where the user permissions are not being retrieved correctly. The issue seems to be present in the following three lines of code:

```rust
#[command]
async fn reset_scores(ctx: &Context, msg: &Message, _args: Args) -> CommandResult {
    let member = msg.member(&ctx.http).await.unwrap();
    println!("{:?}", member);
}
```

printing the following member:

```rust
Member {
    deaf: false,
    guild_id: GuildId(REDACTED),
    joined_at: Some(Timestamp(2022-01-10 8:50:21.464 +00:00:00)),
    mute: false,
    nick: None,
    roles: [RoleId(REDACTED), RoleId(REDACTED)],
    user: User {
        id: UserId(REDACTED),
        avatar: Some(REDACTED),
        bot: false,
        discriminator: 0,
        name: "REDACTED",
        public_flags: Some(HOUSE_BRILLIANCE),
        banner: None,
        accent_colour: None,
        member: None
    },
    pending: false,
    premium_since: None,
    permissions: None,
    avatar: None,
    communication_disabled_until: None
}
```

### Expected Behavior:
The `println!("{:?}", member);` statement should print accurate user permission information for the specified member.

### Actual Behavior:
The output consistently shows the following output:

I tried solving setting the following intents, but does not seem to work:
```rust
let intents = GatewayIntents::GUILDS
    | GatewayIntents::MESSAGE_CONTENT
    | GatewayIntents::GUILD_INTEGRATIONS
    | GatewayIntents::GUILD_MESSAGE_REACTIONS
    | GatewayIntents::GUILD_MESSAGES
    | GatewayIntents::GUILD_MEMBERS;
```

It appears that the permissions: None field is not populated correctly. This behavior is unexpected, as it should reflect the user's permissions within the guild.

**Comment by jamesbt365** [comment]
See the documentation [here](https://docs.rs/serenity/latest/serenity/model/guild/struct.PartialMember.html).
![image](https://github.com/serenity-rs/serenity/assets/22662856/fb7dc8ee-98d7-4f22-a894-f480130581c7)

**Comment by fulviodenza** [comment]
Thanks for the response!

I'm using this method from EventHandler:
```rust
    async fn message(&self, ctx: Context, msg: Message) {
```
while I see from what you say that I should use `interaction_create` method in EventHandler which only handles slash commands:
```rust
    /// Dispatched when an interaction is created (e.g a slash command was used or a button was clicked).
    ///
    /// Provides the created interaction.
    async fn interaction_create(&self, _ctx: Context, _interaction: Interaction) {}
```
while I'm interested in Message commands since I'm have a dynamic prefix. Do you think is it still possible to get the permissions from the member? @jamesbt365

**Comment by jamesbt365** [comment]
Use the permissions method on the member object.

**Comment by jamesbt365** [comment]
Though if you are trying to lock a user out from a command, why not just decorate the command with a [command option](https://docs.rs/serenity/latest/serenity/framework/standard/struct.CommandOptions.html)? Unless you are trying to make a user info style command or locking out a specific argument, I don't see a reason to need permissions like this.

**Comment by fulviodenza** [comment]
> Use the permissions method on the member object.

member does not have a permission method, just a field, which is empty.

> why not just decorate the command with a [command option](https://docs.rs/serenity/latest/serenity/framework/standard/struct.CommandOptions.html)

I've tried using the macro #[required_permissions(ADMINISTRATOR)]
The code above the function looks like this:
```rust
#[command]
#[required_permissions(ADMINISTRATOR)]
```
but still the user who is not an administrator can execute the command

**Comment by jamesbt365** [comment]
Message.Member is a partial member, not a Member, you can get the actual member object with the cache or http.

Here is the method on the Member object.
https://docs.rs/serenity/latest/serenity/model/guild/struct.Member.html#method.permissions

> but still the user who is not an administrator can execute the command

Sounds like you are either the server owner or you have another misconfiguration, or you just forget to save and recompile.

**Comment by fulviodenza** [comment]
@jamesbt365 I needed to add the feature "cache" to make the macro work, thanks :)
