### ISSUE TITLE
Fix Tungstenite high vulnerability

### ISSUE THREAD

**Issue by emilkrebs** [serenity-rs/serenity#2605]
I saw this security warning in my repository:

https://github.com/emilkrebs/Generator-Discord/security/dependabot/7

Please update to Tungstenite `0.20.1`.

**Comment by mkrasnitski** [comment]
This is addressed on the `next` branch, which is imminently releasing (v0.12 expected today). After that, #2573 will be merged into the a newly created `v0.11.x` branch and included in the v0.11.8 patch release.

**Comment by jamesbt365** [comment]
Duplicate of #2550 (you also linked a private GitHub repository)

**Comment by emilkrebs** [comment]
Thanks!
