### ISSUE TITLE
How to use CommandResult?

### ISSUE THREAD

**Issue by Gremious** [serenity-rs/serenity#2608]
Commands return a `CommandResult`, however, I cannot see a way to interact with said result.

I was wondering if there is some sort of hook that would tell let me send a message on command error?

Consider the following command that immediatelly errors:

```rust
#[command]
#[only_in(guilds)]
#[required_permissions("ADMINISTRATOR")]
async fn test(ctx: &Context, msg: &Message) -> CommandResult {
        return CommandResult::Err(CommandError::from("Bad arguments."));
}
```

I also have the `StandardFramework`'s `on_dispatch_error` set to the hook exactly as shown in the example doc comment. 

However, calling the `test` command fails entirely silently, does not print anything in console or message in discord - is that intentional? Is there a `on_command_error` that's hidden somewhere? Or are we meant to handle errors entirely inside commands?

**Comment by arqunis** [comment]
Handling errors can be done inside of commands, but if you want to have a centralised error handler, [look into `StandardFramework::after()`](https://docs.rs/serenity/latest/serenity/framework/standard/struct.StandardFramework.html#method.after). The `CommandResult` is passed into the `after` hook.

**Comment by Gremious** [comment]
Perfect, thank you very much!
