### ISSUE TITLE
implement `Display` for `EmojiIdentifier`

### ISSUE THREAD

**Issue by vidhanio** [serenity-rs/serenity#2638]
is there a reason that there isnt a `<:{name}:{id}>` `Display` impl?

**Comment by kangalio** [comment]
No reason, as far as I can tell. EmojiIdentifier is definitely printable, because `ReactionType::from(emoji_identifier)` does implement Display

You can PR the Display impl ^^

**Comment by vidhanio** [comment]
> You can PR the Display impl ^^

done! :)
