### ISSUE TITLE
`CreateCommandOption::{max,min}_int_value` are unnecessarily unsigned.

### ISSUE THREAD

**Issue by vidhanio** [serenity-rs/serenity#2652]
The [relevant Discord API docs](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure) mention nothing about these fields requiring to be unsigned. Is this a bug (should the method accept an `i64`?) or a real undocumented requirement?

**Comment by ScottyThePilot** [comment]
It might be worth noting that these previously accepted an `i32` while `add_int_choice`/`add_int_choice_localized` still accept an `i32` and `CommandDataOptionValue::Integer` contains an `i64`.

**Comment by vidhanio** [comment]
the discord api spec states the max int size is 2^53 (i54), same as the json spec. i think the entire serenity api should just globally allow i64 and let the discord api error respond with an if you go above that. better than capping users off at i32.

**Comment by ARandomDev99** [comment]
I have created a [PR](https://github.com/serenity-rs/serenity/pull/2668) that addresses this issue.

**Comment by vidhanio** [comment]
closed by #2668! thanks @ARandomDev99 :)
