### ISSUE TITLE
The `get_channel_archived_public_threads` method doesn't encode the timestamp well

### ISSUE THREAD

**Issue by Kerollmops** [serenity-rs/serenity#2664]
While using the `Http::get_channel_archived_public_threads` method I got an error due to a miss-encoded `before` argument. The method asks for an `Option<u64>` but should rather ask for an `Option<Timestamp>` and encode it in ISO8601 as [described in the documentation](https://discord.com/developers/docs/resources/channel#list-public-archived-threads).

```
Error: Invalid Form Body (before: Could not parse 1700059153. Should be ISO8601.)

Caused by:
    Invalid Form Body (before: Could not parse 1700059153. Should be ISO8601.)
```

**Comment by mkrasnitski** [comment]
Closed by #2665.
