### ISSUE TITLE
Discord gateway event `GUILD_MEMBERS_CHUNK` is treated as an `UnknownEvent`

### ISSUE THREAD

**Issue by lapin-b** [serenity-rs/serenity#2666]
I have recently upgraded my code to use the latest and shiniest version to date, 0.12. While updating my code base, I noticed that the event handler for guild members chunks wasn't triggering anymore.

When enabling the debug output of Serenity, the events *do* in fact come through, but are not recognized as what they're supposed to be.

The guilds were requested as such, in the cache ready handler:
```rust
// `ctx` is a plain ol' `&Context`
// `guild_id` is a `&GuildId` in a for loop
ctx.shard.chunk_guild(*guild_id, None, false, gateway::ChunkGuildFilter::None, None);
```

The event handler for guild members chunks is simply doing some logging and calling another function that is responsible for one part of the handling:
```rust
#[async_trait]
impl EventHandler for Handler {
    // ...

    #[tracing::instrument(skip_all, fields(guild_id = ?chunk.guild_id, page = chunk.chunk_index + 1, total = chunk.chunk_count))]
    async fn guild_members_chunk(&self, ctx: Context, chunk: GuildMembersChunkEvent) {
        info!("Received a chunk of {} members from the guild", chunk.members.len());
        process_handler_result(crate::modules::datasync::guild_chunk(&ctx, &chunk).await);
    }
}
```

## Current behavior
The logging outputs similar to what follows:
```
2023-12-17T20:50:32.183720Z DEBUG run: serenity::client::dispatch: An unknown event was received: UnknownEvent { kind: "GUILD_MEMBERS_CHUNK", value: /* the whole payload */ }
```

## Expected behavior
The event is properly recognized as a guild members chunk and the appropriate event handler is called

## Environment information
- Rust version: `1.74.1`
- OS: Fedora Linux 39
- Serenity: as previously mentioned, `0.12.0`

**Comment by lapin-b** [comment]
I think it's time to share a few findings, in case I'm not the only one trying to catch the fish or somebody in the future finds a similar issue.

I have started writing a workaround (at least, what I thought was one) to deserialize the event manually and somehow call the proper event handler, using the raw event handler as such:

```rust
pub struct RawHandler;

#[async_trait]
impl RawEventHandler for RawHandler {
    async fn raw_event(&self, ctx: Context, ev: Event) {
        match ev {
            Event::Unknown(unknown_event) if unknown_event.kind == "GUILD_MEMBERS_CHUNK" => {
                warn!("Using workaround for GUILD_MEMBERS_CHUNK event");
                handle_raw_guild_members_chunk(&ctx, unknown_event).await;
            },

            _ => { /* No-op */ }
        };
    }
}

async fn handle_raw_guild_members_chunk(ctx: &Context, event: UnknownEvent) {
    let event_str = serenity::json::to_string_pretty(&event).unwrap();
    println!("{}", event_str);
    println!("{:?}", event);

    let chunk_event = match serenity::json::from_value::<GuildMembersChunkEvent>(event.value) {
        Ok(chunk_event) => chunk_event,

        Err(why) => {
            error!("Deserialization error\n{:?}", why);
            return;
        }
    };
}
```

I have printed the stringified event and its deserialized representation to later check for discrepancies between Discord's documentation and the implementation of the data structures.

Then, I took this bit of code for a spin by compiling and running the program before continuing writing the code. The deserialization operation returns an error: `Json(Error("invalid type: sequence, expected a map", line: 0, column: 0))`.

When taking a closer look at [Discord's documentation about the `GUILD_MEMBERS_CHUNK` event](https://discord.com/developers/docs/topics/gateway-events#guild-members-chunk), the `members` property is an array. In Rust, that property is [typed as a `HashMap<UserId, Member>`](https://github.com/serenity-rs/serenity/blob/d57a8cf369206c783ae5d9007839dcf0acd9677c/src/model/event.rs#L275).

**Comment by mkrasnitski** [comment]
Thank you for diagnosing this. The culprit is #2287, which simplified the Deserialize impl for `GuildMembersChunkEvent` but forgot to make sure the hashmap was being constructed out of the array rather than being directly deserialized.
