### ISSUE TITLE
`GuildAuditLogEntryCreate` has `Unknown` changes field when action is `Member(RoleUpdate)`

### ISSUE THREAD

**Issue by nryanl** [serenity-rs/serenity#2669]
Serenity version: `0.12.0`

Rust version (`rustc -V`): `rustc 1.74.0 (79e9716c9 2023-11-13)`

This bug can be replicated by implementing this event handler:
```rs
#[async_trait]
impl EventHandler for Handler {
    async fn guild_audit_log_entry_create(&self, ctx: Context, entry: AuditLogEntry, guild_id: GuildId) {
        println!("{:#?}", entry);
    }
}
```
for a basic bot with administrator privilege and all gateway intents (including all privileged intents) enabled.
Assigning someone a role results in this entry being printed:
```
AuditLogEntry {
    target_id: Some(
        GenericId(
            940020670115512390,
        ),
    ),
    action: Member(
        RoleUpdate,
    ),
    reason: None,
    user_id: UserId(
        940020670115512390,
    ),
    changes: Some(
        [
            Unknown,
        ],
    ),
    id: AuditLogEntryId(
        1188383715492102316,
    ),
    options: None,
}
```

In this case, we have information about the who, but no information about what role, or whether it was assigned or removed.

**Comment by arqunis** [comment]
Could you try out the fix from this PR? https://github.com/serenity-rs/serenity/pull/2670

```toml
# Cargo.toml
[dependencies.serenity]
git = "https://github.com/arqunis/serenity"
branch = "audit_fix"
# ...
```

**Comment by nryanl** [comment]
This is a good fix! Thank you :)
