### ISSUE TITLE
Error logged for gracefully exiting voice

### ISSUE THREAD

**Issue by jkcclemens** [serenity-rs/serenity#271]
`[19:29:25] [ERROR] serenity::voice::threading – (╯°□°）╯︵ ┻━┻ Error updating connection: WebSocket(IoError(Custom { kind: Other, error: Error { code: -9805, message: "connection closed gracefully" } }))`

https://github.com/zeyla/serenity/blob/master/src/voice/threading.rs#L77

**Comment by Lakelezz** [comment]
It's been now quite a while and there seems to be nobody else encountering this issue, I shall close this issue.
If it happens again, please inform us and - if possible - provide more information about possible circumstances.
