### ISSUE TITLE
Silent messages

### ISSUE THREAD

**Issue by remexre** [serenity-rs/serenity#2725]
Unless I'm missing it, it doesn't seem to be possible to send silent messages (ones with the behavior one gets from prefixing a message with `@silent `, i.e. making pings in the message not actually notify).

**Comment by GnomedDev** [comment]
I'm looking into this, it doesn't seem to be on the Discord API docs, but that may just be the docs search being bad.

**Comment by GnomedDev** [comment]
This is supported in the form of `MessageFlags::SUPPRESS_NOTIFICATIONS`.

**Comment by remexre** [comment]
Ah, okay; sorry for the bother and thanks!
