### ISSUE TITLE
Method to return the start message of a thread

### ISSUE THREAD

**Issue by algoatson** [serenity-rs/serenity#2751]
I've been looking for a while now, is there a method to retrieve the start message of a thread, what i'm trying to do is implement a functionality where users can rename their threads with a !rename command (since the bot is the one creating threads, users cannot change their thread name by default).

What i'm trying to do is grab the start message, check the author id against the user issuing the !rename command.

Is there a method to retrieve the start message of a thread.

**Comment by jamesbt365** [comment]
you can do this to get the first message of any channel:
```rs
    let get_messages = GetMessages::new().after(MessageId::new(0)).limit(1);
    let msgs = channel_id.messages(ctx, get_messages).await?;
 ```

**Comment by algoatson** [comment]
Thank you !

**Comment by FrenchPoetry** [comment]
This does not seem to work with thread channels

**Comment by nminhdangit** [comment]
Hi, i can't do this in version 0.12.2 because the MessageId struct require NonZeroU64

**Comment by jamesbt365** [comment]
Then construct one or call into().
