### ISSUE TITLE
feat(http): Http Error Codes as enum?

### ISSUE THREAD

**Issue by lukasfri** [serenity-rs/serenity#2752]
I searched through the issue tracker for issues linked to the error code field on the ``serenity::http::error::DiscordJsonError`` and couldn't find any, but this feels like an issue that should've come up, so I apologize if it has done so.

The error field feels it can be improved by either being replaced or supplemented by an enum that covers all currently existing error-codes, with (depending on implementation) either a variant or an Option for if the error-code is unknown.

A list from discords official docs is here:

https://github.com/discord/discord-api-docs/blob/main/docs/topics/Opcodes_and_Status_Codes.md

Would this be wanted? I could potentially implement it myself, with instructions of how the maintainers prefer such implementations.

**Comment by GnomedDev** [comment]
This sounds like something that would be wanted, using the `enum_number` macro we have which will handle the unknown case.

**Comment by jamesbt365** [comment]
Fixed on `next` by #2964.
