### ISSUE TITLE
Unable to run successfully e01_basic_ping_bot

### ISSUE THREAD

**Issue by lorenzo111111** [serenity-rs/serenity#2760]
I was trying to run the example 1 (see title), but I was unsuccessful.
I set the DISCORD_TOKEN correctly and initialization seems successful. However, when I receive a "!ping" message I got the following error:
Error sending message: Http(UnsuccessfulRequest(ErrorResponse { status_code: 401, url: "https://discord.com/api/v10/channels/1205198741049708545/messages", method: POST, error: DiscordJsonError { code: 0, message: "401: Unauthorized", errors: [] } }))

**Comment by jamesbt365** [comment]
Your bot doesnt have permissions to send messages in that channel.

**Comment by lorenzo111111** [comment]
> Your bot doesnt have permissions to send messages in that channel.

How can I solve?

**Comment by ivinjabraham** [comment]
Try checking [this out](https://discord.com/community/permissions-on-discord-discord), if you're still having trouble. You don't have to do anything with the code, it's all in the app itself.

**Comment by jamesbt365** [comment]
Closing as this doesn't seem to be a lib issue.
