### ISSUE TITLE
Use External Emojis shows up twice in formatted Permissions string

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#2769]
Reason:

There's actually just one permission, called USE_EXTERNAL_EMOJIS, but there's two shorthand accessor methods, called use_external_emojis() and external_emojis() (both using the same USE_EXTERNAL_EMOJIS internally). Every accessor method seems to be assigned an associated display name, which will be iterated when formatting permissions, and both use_external_emojis() and external_emojis() got the display name of "Use External Emojis"

Found in: https://discord.com/channels/381880193251409931/381912587505500160/1207880394725400626

**Comment by OvermindDL1** [comment]
Is this fixed by #2770 now?

**Comment by GnomedDev** [comment]
Yes, this was fixed by that PR.
