### ISSUE TITLE
Add support for Polls

### ISSUE THREAD

**Issue by SwannHERRERA** [serenity-rs/serenity#2840]
Discord recently makes available a new feature which is poll, at the date of creation of this issue it's in beta.

Realated to :
https://github.com/discord/discord-api-docs/pull/6746
Depends on :
https://github.com/discordjs/discord-api-types/pull/925

**Comment by tazz4843** [comment]
See #2836

**Comment by GnomedDev** [comment]
This was merged 3 weeks ago, and is supported on the `current` branch.
