### ISSUE TITLE
No variant or associated item named `Member` found for enum `serenity::all::Action` in the current scope.

### ISSUE THREAD

**Issue by Stay1444** [serenity-rs/serenity#2877]
I'm trying to handle the `FullEvent::GuildAuditLogEntryCreate` event, but when trying to match on the `AuditLogEntry.action` member variable the LSP gives the available options

```rs
    GuildUpdate,
    Channel(ChannelAction),
    ChannelOverwrite(ChannelOverwriteAction),
    Member(MemberAction),
    Role(RoleAction),
    Invite(InviteAction),
    Webhook(WebhookAction),
    Emoji(EmojiAction),
    Message(MessageAction),
    Integration(IntegrationAction),
    StageInstance(StageInstanceAction),
    Sticker(StickerAction),
    ScheduledEvent(ScheduledEventAction),
    Thread(ThreadAction),
    AutoMod(AutoModAction),
    CreatorMonetization(CreatorMonetizationAction),
    VoiceChannelStatus(VoiceChannelStatusAction),
    Unknown(u8),
```

But it then throws an error saying that it can't find that enum entry.

Happens when running `cargo build` too.

**Comment by jamesbt365** [comment]
There are multiple `Action`s in serenity, thus both cannot be in `serenity::all`. Use the full path.

**Comment by Stay1444** [comment]
I'm using the full path!

```
error[E0599]: no variant or associated item named `GuildUpdate` found for enum `serenity::all::Action` in the current scope
  --> src/event_handler.rs:43:40
   |
43 |                 serenity::all::Action::GuildUpdate => (),
   |                                        ^^^^^^^^^^^ variant or associated item not found in `Action`
```

The LSP completes that fine, and going to the definition shows me the correct Action enum.

**Comment by jamesbt365** [comment]
LSP's aren't perfect, `cargo check` will always give you the right result. You need to use the full path of `Action`,  `serenity::all::Action` is a reexport, not the full path.

The reexport points at `serenity::model::guild::automod::Action` **not** `serenity::model::guild::audit_log::Action` which you are intending to use here.

**Comment by Stay1444** [comment]
That was it, thank you.
