### ISSUE TITLE
Invalid Type Error

### ISSUE THREAD

**Issue by IBims1NicerTobi** [serenity-rs/serenity#2892]
Iterating over all the messages in a server yields me an invalid type error every time. The error is:
`invalid type: string "#d0334d", expected u32 at line 1 column 123537`
I don't really know what to do in order to help debug this but I assume this is a deserialization error.
Branch: `current`

**Comment by GnomedDev** [comment]
This is most likely caused by #2882 missing `deserialize_with = "discord_colours"` for `MessageReaction::burst_colours`. Can you confirm @jamesbt365?

**Comment by IBims1NicerTobi** [comment]
Ok I am testing rn with
```
#[serde(rename = "burst_colors", deserialize_with = "discord_colours")]
pub burst_colours: Option<Vec<Colour>>,
```
in message.rs and I will report back if that fixes it :)

**Comment by jamesbt365** [comment]
> This is most likely caused by #2882 missing `deserialize_with = "discord_colours"` for `MessageReaction::burst_colours`. Can you confirm @jamesbt365?

I did miss rename on that one, so I'm almost certain its needed here too. will investigate shortly and open a PR for it.
