### ISSUE TITLE
I don't receive the GuildCreate and GuildDelete events (for when the bot joins / gets kicked from a guild)

### ISSUE THREAD

**Issue by Stay1444** [serenity-rs/serenity#2896]
I'm trying to receive the GuildCreate and GuildDelete events to do some stuff when the bot joins or leaves a guild. I'm currently just seeing which events come through, like `dbg!(&event)`, and I see stuff like `Ready`, `ShardReady` and `GuildMemberRemoved` when the bot exists a guild, but I'm not getting the `GuildCreate` and `GuildDelete` ones. (I'm obviously adding the bot to a new server and kicking it)

Any ideas?

**Comment by jamesbt365** [comment]
You do not have the associated intents. https://docs.rs/serenity/latest/serenity/model/gateway/struct.GatewayIntents.html#associatedconstant.GUILDS

**Comment by Stay1444** [comment]
That was it, i thought GatewayIntents::privileged() included that, thank you.

**Comment by jamesbt365** [comment]
[privileged](https://docs.rs/serenity/latest/serenity/model/gateway/struct.GatewayIntents.html#method.privileged) only enabled the intents that require Discord to whitelist the bot (when your bot is verified), [non_privileged](https://docs.rs/serenity/latest/serenity/model/gateway/struct.GatewayIntents.html#method.non_privileged) does the opposite, If you are unsure what intents do what, everything is documented on that page.

You can also see Discord's documentation directly.
