### ISSUE TITLE
Proposal: Icon Change

### ISSUE THREAD

**Issue by Advik-B** [serenity-rs/serenity#2899]
Assuming this repo is being actively maintained

# Icon(s) for serenity
> I made 2 variants

Without Hands
![sernity-icon](https://github.com/serenity-rs/serenity/assets/86160411/baac22b4-cb4d-4447-9ecf-57007bfa1b18)

With Hands
![sernity-icon-hands](https://github.com/serenity-rs/serenity/assets/86160411/650a26d1-6a50-4151-b460-f49e48c618a7)

Raw File (if there is a professional designer somewhere, feel free to perfect this)
[sernity-icon.afdesign.zip](https://github.com/user-attachments/files/15802631/sernity-icon.afdesign.zip)

## DISCLAIMER
I am NOT a designer/artist I just downloaded affinity design free trial and (not so) quickly whipped this up
If you guys wanna use it, feel free to as I license the icons as WTFPL
<details>
<summary>See WTFPL license</summary>

```
        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
                    Version 2, December 2004 

 Copyright (C) 2024 Advik-B <https://github.com/Advik-B>

 Everyone is permitted to copy and distribute verbatim or modified 
 copies of this license document, and changing it is allowed as long 
 as the name is changed. 

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 

  0. You just DO WHAT THE FUCK YOU WANT TO.
 ```
</details>

[![WTFPL-icon](http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl-badge-1.png)](http://www.wtfpl.net/)

**Comment by arqunis** [comment]
> Assuming this repo is being actively maintained.

It is. Much of the development happens on the `next` branch, since the `current` branch is restricted to non-breaking additions and fixes, which is why it might appear dead if you're just looking at the `current` branch alone.

Now, as for the icon proposal itself:
I appreciate the effort in wanting to change the icon by already having made variants we could use, but I must respectfully decline. We are content with the current icon, even if it was crudely drawn in MSPaint. It has a unique charm that way. It was also made by the original maintainer of Serenity, so we'd like to retain for sentimental purposes.

**Comment by Advik-B** [comment]
> > Assuming this repo is being actively maintained.
> 
> It is. Much of the development happens on the `next` branch, since the `current` branch is restricted to non-breaking additions and fixes, which is why it might appear dead if you're just looking at the `current` branch alone.
> 
> Now, as for the icon proposal itself: I appreciate the effort in wanting to change the icon by already having made variants we could use, but I must respectfully decline. We are content with the current icon, even if it was crudely drawn in MSPaint. It has a unique charm that way. It was also made by the original maintainer of Serenity, so we'd like to retain for sentimental purposes.

Okeii 😄
Have a good one!

PS: I looked at the logo and its 7 YEARS OLD!
PSPS: Who is Zeyla Hellyer and why isnt the github profile clickable (you got me curious now)

> A lot of `Hellyer` surnames

**Comment by arqunis** [comment]
Zeyla Hellyer is the name of the original maintainer. I don't remember the story exactly, but I think her prior account got deleted by Github for some reason? Anyway, [she made a new account that she's been using](https://github.com/zeylahellyer).
