### ISSUE TITLE
set_presence from outside an event / command? How can I access serenity's Context from an outside event loop so i can change the presence?

### ISSUE THREAD

**Issue by Stay1444** [serenity-rs/serenity#2900]
I need to change the bot presence from an outside event loop, but it does not appear to be possible from the Http low level API (?).

**Comment by jamesbt365** [comment]
the bot presence is handled over the gateway, depending on how you are handling this task, you should have access to the Client, which has the `ShardManager`, which contains the `ShardRunnerInfo` for all the shards, which then contain the `ShardMessenger` which you can set the presence from.

**Comment by Stay1444** [comment]
That did it. Thanks.
