### ISSUE TITLE
Serenity won't accept Discord Token no matter what

### ISSUE THREAD

**Issue by kurimanju-dev** [serenity-rs/serenity#2912]
I might be stupid but I can't figure out why `cargo run` is always returning `Expected a token in the environment: NotPresent`.

## Cargo.toml
```
[package]
name = "e01_basic_ping_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[dependencies.serenity]
default-features = false
features = ["client", "gateway", "rustls_backend", "model"]
version = "0.12"
```
## main.rs
![Screenshot from 2024-07-01 18-32-22](https://github.com/serenity-rs/serenity/assets/73285163/1325c11d-c7db-40b1-b955-9510691642f9)

**Comment by jamesbt365** [comment]
You really should look in the documentation of `std::env::var` and read up on how environment variables work, you are looking for an environment variable with the *name* set to your token, not the actual value of the token.
