### ISSUE TITLE
Reaction Event Handlers Not Dispatching

### ISSUE THREAD

**Issue by zRyder** [serenity-rs/serenity#2923]
When trying to implement adding/removing reactions. The handler implementations are not dispatched. Tested with `ReactionAdd` and `ReactionRemove`. When debugging, I had a non admin user add a reaction to a message, when I debugged, the bot with admin permissions did not run the code.

**Comment by jamesbt365** [comment]
Show your intents.

**Comment by zRyder** [comment]
Could you remind me what that is again?

**Comment by jamesbt365** [comment]
They are the toggles that indicate to Discord what events to send you. You set these when you are creating the serenity client.

**Comment by zRyder** [comment]
I see, I’ll provide them in a bit

**Comment by jamesbt365** [comment]
This is either a duplicate of #2930 #2922, #2910, #2909, #2892 or user error.
