### ISSUE TITLE
Null error in audit logs.

### ISSUE THREAD

**Issue by ValgulNecron** [serenity-rs/serenity#2929]
if we try to get the audit log like this
```rs
guild_id
        .audit_logs(&ctx.http, None, None, None, Some(100))
 ```
and a webhook updated itself before with something like this
```rs
let attachment = CreateAttachment::bytes(decoded_bytes, "avatar");
let edit_webhook = EditWebhook::new().name(trimmed_name).avatar(&attachment);
webhook.edit(&ctx.http, edit_webhook)
```
we will get the error
```
invalid type: null, expected a non-zero string or integer snowflake at line 1 column 2363
```
because the user_id field is null
```json
{"id":"1253136095328337940","action_type":51,"user_id":null,"target_id":"1253136028441510109","changes":[{"key":"avatar_hash","new_value":"8120e9729eda8cfec8fcf84b7f69833f","old_value":"68787e5ed700348a5eb2a25f274d2dcb"},{"key":"name","new_value":"Jellyfish Can\\u2019t Swim in the Night / Yoru no Kura","old_value":"THE NEW GATE / THE NEW GATE"}]}
```

**Comment by arqunis** [comment]
This should be fixed on `next`, where the type of `user_id` has been changed to `Option<UserId>` and should handle the `null` value:

https://github.com/serenity-rs/serenity/blob/640fa8a518f04e49a7dc61281c6b13080dba2dc7/src/model/guild/audit_log/mod.rs#L386

Closing this as without a breaking change, it can't be fixed on `current`.
