### ISSUE TITLE
Can I resume and retrieve the message_create events that were missed during a period of disconnection?

### ISSUE THREAD

**Issue by nminhdangit** [serenity-rs/serenity#2932]
Because I work in an unstable network environment, I need some features to recover missed messages.
Thanks

**Comment by anden3** [comment]
To my knowledge Discord offers no such capability.

**Comment by jamesbt365** [comment]
If you wanted this you would have to store the id of the last stored message and if you DC, when you reconnect (if you didn't get the events missed back from the gateway), you will have to call `MessagesIter` on every single ChannelId you are interested in until you reach the Id's of the messages you already have.

Do note that its impossible to recover messages that have already been deleted or the contents of a message prior to an edit. 

If you absolutely need as much uptime as you can, relying on discord for sending everything you missed or manually catching it up yourself is not a good countermeasure to the issue, you are much better off getting a cheap VPS if you *absolutely* need this.
