### ISSUE TITLE
Unable to compile the serenity library

### ISSUE THREAD

**Issue by JacksonVirgo** [serenity-rs/serenity#2937]
I've been trying to figure out what I've done wrong in my setup to cause this considering I've seen so few people also have this issue but I'm unable to compile the lib at all. I'm getting 30 errors, all for mismatched types, conflicting trait implementations etc and I'm not sure what to do from here.

<img width="978" alt="Screenshot 2024-08-11 at 7 04 01 pm" src="https://github.com/user-attachments/assets/33b41a51-87b6-41b5-ab8b-aceec2c42916">

Any help would be appreciated, including redirecting me to a better place to ask about these problems if there is one

**Comment by arqunis** [comment]
This appears to be a conflict from multiple versions of Serenity. You should ideally only have one version being built. What is your `Cargo.toml` setup?

> Any help would be appreciated, including redirecting me to a better place to ask about these problems if there is one

That would be the Serenity Discord: https://discord.gg/serenity-rs

**Comment by JacksonVirgo** [comment]
```
[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
```

I just spun up a new project to check it out, that's all of what is in the toml outside of the basic package stuff that gets written on `cargo init`

**Comment by JacksonVirgo** [comment]
And to be as clear as possible, it's not my implementation as a blank program is giving the same issues when compiling

**Comment by jamesbt365** [comment]
Your cargo's registry could be messed up.

**Comment by JacksonVirgo** [comment]
Yeah, it seems like it was. Thank you!
