### ISSUE TITLE
New get_sticker_pack_by_id endpoint

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#2940]
The new endpoint is:
GET `/sticker-packs/{}/sticker-pack-object` where `{}` is a `StickerPackId` instance.

As well as the Http implementation, a helper method in the object type would be useful too.

[Discord API docs change commit](https://github.com/discord/discord-api-docs/commit/1a9e949f1be126a1b2e6797de4c0713dc868d438)

**Comment by ivinjabraham** [comment]
Resolved in #2960
