### ISSUE TITLE
Use `Activity` instead of `ActivityData` in `Context::set_activity()`

### ISSUE THREAD

**Issue by valentinegb** [serenity-rs/serenity#2949]
The [Update Presence](https://discord.com/developers/docs/topics/gateway-events#update-presence) Gateway send event currently accepts much more information about an activity than `serenity` allows you to give. For example, Update Presence allows you to specify image assets while `ActivityData`, which is what `Context::set_activity()` accepts, does not. I believe `Activity` matches the extent of what Update Presence accepts so I think it would be more suitable to be accepted by `Context::set_activity()`.

**Comment by jamesbt365** [comment]
Its the way it is because bots can't use anything else.
![image](https://github.com/user-attachments/assets/bf598140-9f7b-4e09-8510-245d03f2c16b)

**Comment by valentinegb** [comment]
Bah- if only I had scrolled a little further! Sorry ^^'
I'm curious if that's still true though, since recently Discord started displaying a missing image icon on bot activity, which lead me to think it was possible to set an image

<img width="299" alt="Screenshot 2024-08-19 at 6 05 27 PM" src="https://github.com/user-attachments/assets/9ff38f50-a43b-481a-b0e4-e3643d665a96">

**Comment by valentinegb** [comment]
Okay I've totally confirmed that, eh, I was wrong lol
Sorry again ^^'

<img width="469" alt="Screenshot 2024-08-19 at 6 19 40 PM" src="https://github.com/user-attachments/assets/695aee12-340c-40cd-8b1b-1e4ec5f50a7f">
