### ISSUE TITLE
Add an optional X-Audit-Log-Reason header to auditable actions

### ISSUE THREAD

**Issue by maddin77** [serenity-rs/serenity#296]

**Comment by xSke** [comment]
I can tackle this. Been meaning to contribute, and it seems like low-hanging fruit.

My plan is to add a `Option<&str>` parameter to every method in `http/raw.rs` executing an auditable action. This will create major breaking changes to users of that module. The same goes for the `models` module. Alternatively, I can make two variants of every method, one named `x_with_reason`, the other staying the same and defaulting to no reason. Which variant would be preferred?

**Comment by Erk-** [comment]
If you did the latter version it could be added to the current branch without breaking changes, then we can look at how we should structure it on the v0.6.x branch afterwards.

**Comment by LeSeulArtichaut** [comment]
Because it has been left for long, I'd like to work on this.
I'll be adding `with_reason` methods like suggested by @xSke to be compatible with the current version of Serenity. However, to support UTF-8 reasons, I'd need to do percent-encoding. Is it ok to have an additional dependency or should I write my own implementation for this?

**Comment by Erk-** [comment]
I would say that it is better to add a single dependency, https://crates.io/crates/percent-encoding, (which does not depend on any other crate) than to roll it ourselves.

**Comment by LeSeulArtichaut** [comment]
I think I'll give up the idea of having two variants of the same method. There already are a lot of them, and I think having two methods for 30 routes or so, just in the raw Http struct, is a lot, but there are much more methods from all the model structs.

**Comment by kangalio** [comment]
Does this issue still need to be open?
