### ISSUE TITLE
Futures Branch

### ISSUE THREAD

**Issue by zeyla** [serenity-rs/serenity#298]
There are a few tasks remaining until this is usable.

Including, but not limited to:

- [ ] Make a Client that spawns shards, ratelimits shard spawning, and merges their streams into a single stream
- [ ] Make a Shard Manager (maybe?)
- [ ] Make the Framework spawn on a handle instead of a threadpool
- [ ] Make voice use futures-cpupool

**Comment by xacrimon** [comment]
Might be a candidate for v0.7.x after v0.6.x is done. Async-await isnt far away at this point.
