### ISSUE TITLE
Add support for guild search members endpoint

### ISSUE THREAD

**Issue by NikSneMC** [serenity-rs/serenity#2981]
Discord have endpoint `guilds/{guild.id}/members-search` which is much more advanced than the `/guilds/{guild.id}/members/search` endpoint. It can be used to fetch invite code, inviter and much more

**Comment by GnomedDev** [comment]
I cannot see this documented on [Discord Developer Documentation](https://discord.com/developers/docs/resources/guild), can you link me to it?

If this isn't documented on ddev documentation, please open a PR there first to make sure it is officially supported, then when merged we will add it.

**Comment by jamesbt365** [comment]
discord/discord-api-docs#7068 states that this will remain undocumented at this time, additionally attempting to use this with a bot token returns an "internal network error".

**Comment by GnomedDev** [comment]
Okay, closing then.

**Comment by NikSneMC** [comment]
> [discord/discord-api-docs#7068](https://github.com/discord/discord-api-docs/pull/7068) states that this will remain undocumented at this time, additionally attempting to use this with a bot token returns an "internal network error".

Yes, it's undocumented, but I tested it today and it worked on the v10 api with bot token

**Comment by GnomedDev** [comment]
As I have said, we do not implement undocumented features as Discord may remove or change behavior at any time.

**Comment by jamesbt365** [comment]
Interesting, usually copying the request from the client and changing the token is enough, i had to remove the rest of the "bloat" from the request for it to go through. Though, we don't add support for undocumented endpoints.
