### ISSUE TITLE
Make wait time between boots configurable

### ISSUE THREAD

**Issue by cheesycod** [serenity-rs/serenity#2990]
When using serenity behind a gateway proxy or other such infrastructure, the wait time between boots is unnecessary and only slows down the bot startup. This should be made configurable

**Comment by ivinjabraham** [comment]
I'm not sure what delay this is referring to? I looked through `client.start()` and there doesn't seem to be any artificial delay.

**Comment by jamesbt365** [comment]
Fixed by #3031.

**Comment by jamesbt365** [comment]
> I'm not sure what delay this is referring to? I looked through `client.start()` and there doesn't seem to be any artificial delay.

There is a delay of 5 seconds between shard starts, this is for bots with multiple shards.
