### ISSUE TITLE
Bug: Bot fails on startup when an entry point is configured in the discord developer portal

### ISSUE THREAD

**Issue by flashgnash** [serenity-rs/serenity#2993]
Serenity 0.12.2
rustc 1.78.0 (9b00956e5 2024-04-29) (built from a source tarball)

When an activity entry point URL is configured via the discord portal:

![image](https://github.com/user-attachments/assets/ac298d45-89ba-4c68-a5e9-f7aeadd53fea)
![image](https://github.com/user-attachments/assets/bb6bfd04-84f3-4482-9ccc-345bcb9ee645)

Running my bot results in the following error:

Error in user data setup: You cannot remove this app's Entry Point command in a bulk update operation. Please include the Entry Point command in your update request or delete it separately.

I am assuming this is serenity attempting to set the bot's settings on startup, but failing because discord's API does not allow doing so via bulk request

**Comment by GnomedDev** [comment]
This occurs when calling the [Bulk Overwrite Application Commands](https://discord.com/developers/docs/interactions/application-commands#bulk-overwrite-global-application-commands) endpoint, aka [Command::set_global_commands](https://docs.rs/serenity/latest/serenity/model/application/struct.Command.html#method.set_global_commands) without the auto-generated "entrypoint command". This is not done by serenity at all, so your bot code must be calling it, maybe on the ready event (which is a bad idea). 

This is intentional behaviour by discord, although we do not support deserializing entrypoint commands yet. Please open a seperate issue for entrypoint command support, if it doesn't already exist, which will allow you to fetch the entrypoint command and include it in the `set_global_commands` request.

**Comment by flashgnash** [comment]
> This occurs when calling the [Bulk Overwrite Application Commands](https://discord.com/developers/docs/interactions/application-commands#bulk-overwrite-global-application-commands) endpoint, aka [Command::set_global_commands](https://docs.rs/serenity/latest/serenity/model/application/struct.Command.html#method.set_global_commands) without the auto-generated "entrypoint command". This is not done by serenity at all, so your bot code must be calling it, maybe on the ready event (which is a bad idea).
> 
> This is intentional behaviour by discord, although we do not support deserializing entrypoint commands yet. Please open a seperate issue for entrypoint command support, if it doesn't already exist, which will allow you to fetch the entrypoint command and include it in the `set_global_commands` request.

    let framework = poise::Framework::builder()
        .options(poise::FrameworkOptions {
            commands: vec![
                ping(),
                calc(), 

                ask(), draw(), translate(),translate_context(),

                pull_stat(), pull_stats(), pull_spellsheet(),
                get_mana(), set_mana(), mod_mana(), add_mana(), sub_mana(),
                status(),
                get_characters(), delete_character(),
                select_character(), create_character(), set_spells(),
                
                cast_spell(), level_up(), roll(), 

                join_vc(),
                play_music(),stop_music(),pause_music(),resume_music(),skip_song()
            ],

            ..Default::default()
        })
        .setup(|ctx, _ready, framework| {
            Box::pin(async move {
                poise::builtins::register_globally(ctx, &framework.options().commands).await?;
                Ok(Data {})
            })
        })
        .build();

**Comment by flashgnash** [comment]
As far as I'm aware I'm not doing that, using the following method to setup poise, could it be that poise is doing this somewhere? Had thought this would be a general serenity issue

```rust
    let framework = poise::Framework::builder()
        .options(poise::FrameworkOptions {
            commands: vec![
                ping(),
                calc(), 

                ask(), draw(), translate(),translate_context(),

                pull_stat(), pull_stats(), pull_spellsheet(),
                get_mana(), set_mana(), mod_mana(), add_mana(), sub_mana(),
                status(),
                get_characters(), delete_character(),
                select_character(), create_character(), set_spells(),
                
                cast_spell(), level_up(), roll(), 

                join_vc(),
                play_music(),stop_music(),pause_music(),resume_music(),skip_song()
            ],

            ..Default::default()
        })
        .setup(|ctx, _ready, framework| {
            Box::pin(async move {
                poise::builtins::register_globally(ctx, &framework.options().commands).await?;
                Ok(Data {})
            })
        })
        .build();
        
        ```

**Comment by GnomedDev** [comment]
Looking at your error message closer, you are calling a function which sets the commands in your "user data setup" function, aka the closure passed to `.setup()`. If you need more help, please keep it to the [serenity discord server](https://discord.gg/serenity-rs) which has a poise channel as-well.
