### ISSUE TITLE
Update `MessageReference` Struct

### ISSUE THREAD

**Issue by MarkusTheOrt** [serenity-rs/serenity#2994]
the [`MessageReference`](https://github.com/serenity-rs/serenity/blob/current/src/model/channel/message.rs#L1095) struct is missing the type field (see here: https://discord.com/developers/docs/resources/message#message-reference-object)

I am happy to implement this myself, the question is do you want this added as a struct field, or make a union enum from this?

**Comment by GnomedDev** [comment]
This looks to be part of fowarding, which should have it's issue opened to track, but you can add this as a field as part of the forwarding work if you want. Use our `enum_number!` macro to make `MessageReferenceType`/`Kind` (depending what everything else is) and add it as a field.
