### ISSUE TITLE
Outdated permissions deprecation messages

### ISSUE THREAD

**Issue by Earthcomputer** [serenity-rs/serenity#3057]
The following deprecated functions reference the `member_permissions_in` function as a replacement, but the replacement function doesn't exist.
- `Member::permissions`
- `Guild::member_permissions`
- `PartialGuild::member_permissions`

**Comment by jamesbt365** [comment]
I've gone ahead and corrected the warning in 4b9756c08367fed474d99854497d3c15ecfc66f8, the method will subsequently be renamed for 0.13. Thanks for reporting this!
