### ISSUE TITLE
guild_create not triggered

### ISSUE THREAD

**Issue by 0x4ndy** [serenity-rs/serenity#3073]
Hey there, I'm trying to capture the event of someone adding my bot to their Guild. I have the following function in my `EventHandler`:

```rust
async fn guild_create(&self, ctx: Context, guild: Guild, is_new: Option<bool>) {
    println!("Added to: {}", guild.name);
}
```

I've successfully added the bot to another server, but this method is never triggered. I doubt there's anything wrong with the serenity itself, so what am I missing?

**Comment by arqunis** [comment]
Have you configured your [gateway intents](https://serenity-rs.github.io/serenity/current/serenity/client/struct.ClientBuilder.html#method.intents)? You need at least the [`GUILDS`](https://serenity-rs.github.io/serenity/current/serenity/model/gateway/struct.GatewayIntents.html#associatedconstant.GUILDS) intent to receive `GUILD_CREATE` events.

**Comment by 0x4ndy** [comment]
Yes, that's exactly what I was missing. Thanks!
