### ISSUE TITLE
Letting it go after `client.start()`

### ISSUE THREAD

**Issue by 0x4ndy** [serenity-rs/serenity#3074]
I've been trying to start the client and letting the execution flow continue so that I can start a loop in which I want to interact with my application. Here's what I have in my `main`:
```rust
let mut client = Client::builder(token, intents)
    .event_handler(handler)
    .await
    .expect("Err creating client");

let bot = client.start();

loop {
    let mut input = String::new();

    std::io::stdin()
        .read_line(&mut input)
        .expect("Failed to read line.");
    println!("Input: {}", input);
    sleep(Duration::from_secs(2)).await;
}
```
After `.start()`, the execution flow continues, but the bot doesn't start with a warning that it has to `.await` for it to start. This looks like a `tokio` thing, which I don't know much about. I've seen `tokio` has its own `tokio::io`, but I really don't want to use it. So, I'm wondering whether there's any other way to deal with this? I was thinking that if there was a way for me to interact with serenity api in a blocking manner, I could spawn the client in a `std::thread` and continue to the loop. At least I'd know what I was doing. With tokio I'm walking blind ;) Can you guys give me an advice what's the best way to proceed with this?

EDIT: btw, is there a discord or some other groups where I can ask those questions, instead of creating a GitHub issue? Thanks in advance! :)

**Comment by 0x4ndy** [comment]
Ok, with some help from Rust community I manage to get this working like so:
```rust
// Spawn a new thread to run the bot
let bot_thread = thread::spawn(move || {
    // Create a new instance of the Client, logging in as a bot.
    let runtime = tokio::runtime::Runtime::new().expect("Failed to create runtime");
    runtime.block_on(async {
        let mut client = Client::builder(token, intents)
            .event_handler(handler)
            .await
            .expect("Err creating client");
        if let Err(why) = client.start().await {
            println!("Client error: {:?}", why);
        }
    });
});

// Main thread continues execution for user interaction
println!("Bot is running. Type 'exit' to shut down.");

// Read user input from the console
let mut input = String::new();
while input.trim() != "exit" {
    input.clear();
    std::io::stdin()
        .read_line(&mut input)
        .expect("Failed to read line");
}

// Clean up and shut down
println!("Shutting down bot...");
```
My question now is, how can I interact with the bot client from that `while` loop? I mean, technically I could do something like this in the `while` loop:
```rust
let channel_id = ChannelId::new(XYZ);
let http =
    Http::new("XYZ");
if let Err(why) = channel_id.say(http, "hey there!").await {
    println!("Error sending message: {why:?}");
}
```
But is that the way to go?

**Comment by jamesbt365** [comment]
> After `.start()`, the execution flow continues, but the bot doesn't start with a warning that it has to `.await` for it to start. 

Yes, futures do nothing if you don't await or poll them, serenity has no blocking way of connecting to the discord api and relies heavily on tokio.

and as for what you would do to interact with the bot in a while loop I don't know what your intentions are, so i'm unable to guide you.

Though... if you already have a client why are you manually creating `Http`?

**Comment by jamesbt365** [comment]
> btw, is there a discord or some other groups where I can ask those questions, instead of creating a GitHub issue? Thanks in advance! :)

https://discord.gg/serenity-rs

**Comment by 0x4ndy** [comment]
> Though... if you already have a client why are you manually creating `Http`?

I have it because I created one, but my hope was that I can just tell the bot client what I want to do (e.g. send a message to a specific channel). 
But, from what you're saying, getting `Http` outside of the bot client is the intended way.

**Comment by jamesbt365** [comment]
If you are just sending messages, you don't even need the client, the client is for receiving messages from the gateway via the event handler.

**Comment by 0x4ndy** [comment]
In my use case I do need a client because I want the users to communicate with the bot. But I also want to have ability to send messages and other things with the bot. Now I see now that `Http` just gives me the access to the API which I can use to do pretty much anything.
