### ISSUE TITLE
Make MessageBuilder use &mut self instead of self

### ISSUE THREAD

**Issue by PvdBerg1998** [serenity-rs/serenity#313]
`MessageBuilder` takes ownership of `self` in each function, which makes is unusable in for example an iterator. Replacing `self` with `&mut self` would fix this problem.

**Comment by PvdBerg1998** [comment]
I see this is fixed in the 0.6.x branch.

**Comment by PvdBerg1998** [comment]
Sorry I'm blind

**Comment by zeyla** [comment]
Closed by https://github.com/serenity-rs/serenity/commit/67155c71af37c6e4056b153ab63a11424cf78334 and #314.
