### ISSUE TITLE
.num_args check is broken

### ISSUE THREAD

**Issue by PvdBerg1998** [serenity-rs/serenity#334]
Adding a command with a `.num_args(n)` restriction and passing a wrong amount of arguments results in the command handler being called instead of an error being thrown.

**Comment by PvdBerg1998** [comment]
The command handler is still called but `args.single()` returns a result that should be `?`'d instead of `unwrapped`. Maybe this should be noted somewhere if it is not already? I expected the handler to not be called if the conditions are not met.

**Comment by PvdBerg1998** [comment]
```rust
if self.configuration.owners.contains(&message.author.id) {
    None
}
```
Bypasses the check and therefore causes the issue since I am registered as an owner.

**Comment by acdenisSK** [comment]
Fixed on latest master.
