### ISSUE TITLE
Add option to not require command prefix when direct messaging bots

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [serenity-rs/serenity#339]
Currently for a `StandardFramework` bot, the user must prefix commands to the bot with the bot's prefix. This is needed for public channels, but it's redundant and annoying when direct messaging the bot (of course you're sending commands to the bot when direct messaging it, what else are you doing?).

Is there an easy way using the `StandardFramework` to treat incoming direct messages as commands even if they lack a prefix? I didn't see anything in the documentation. If not, could it be added?

**Comment by Lakelezz** [comment]
Hello, there is no direct way to do it but you can do this:
set `prefix("")` on your framework-configuration.
Then use [dynamic_prefix](https://docs.rs/serenity/0.5.*/serenity/framework/standard/struct.Configuration.html#method.dynamic_prefix) and make it return `None` whenever [is_private](https://docs.rs/serenity/0.5.*/serenity/model/channel/struct.Message.html#method.is_private) returns `true` on your [https://docs.rs/serenity/0.5.*/serenity/model/channel/struct.Message.html](https://docs.rs/serenity/0.5.*/serenity/model/channel/struct.Message.html)-argument.

We should add a simple way to do this. Nonetheless, some people create smart bots, that actually respond to real messages. Thus it's of use to have a differentiation between command and text.

**Comment by acdenisSK** [comment]
Not a full fix (see @Lakelezz's comment about differentation), but for what you want, as of [10bbffe](https://github.com/serenity-rs/serenity/commit/10bbffe9332edf8b8835d98cfffb8ec411162145) you can simply turn this on by calling `no_prefix` on `Configuration`.
E.g:
```rust
StandardFramework::new().configure(|conf| conf.no_prefix(true))
```
