### ISSUE TITLE
No way to calculate offset between system time and Discord's system time.

### ISSUE THREAD

**Issue by LJNeon** [serenity-rs/serenity#346]
I came to serenity from eris, and eris has a feature [built into the lib](https://github.com/abalabahaha/eris/blob/master/lib/rest/RequestHandler.js#L174) where it makes sure the offset between your system clock and Discord's system clock is under a configurable value. It appears to use the date headers to calculate the offset. Since having a large offset usually means your system clock is behind or ahead, something that can cause other problems with a discord bot, ensuring that it's small is worth caring about imo.

**Comment by zeyla** [comment]
This already existed, and the value has been made public in 55555b8.
