### ISSUE TITLE
Json(Error("invalid length 0, expected struct PrivateChannel with 5 elements", line: 1, column: 2))

### ISSUE THREAD

**Issue by djmcgill** [serenity-rs/serenity#380]
Given a `Message`, calling `message.author.id.create_dm_channel()` results in:
```
Err(Json(Error("invalid length 0, expected struct PrivateChannel with 5 elements", line: 1, column: 2)))
```
This happens on version `0.5.8`.

Looking at the logs you can see a call made out to `Post "/api/v6/channels/12345/messages"` and then `13:21:06 [DEBUG] hyper::client::response: version=Http11, status=Ok`
Which seems to suggest that it's the response parsing that's failing? I'd love for `serenity` to use the `failure` crate or similar which will give stack traces.

**Comment by Erk-** [comment]
Does it also happen on master?

**Comment by Lakelezz** [comment]
Hello, this should be fixed on master: https://github.com/serenity-rs/serenity/commit/30a325ea840755cf74f376657d9a1e9ac363e92e

**Comment by djmcgill** [comment]
I can confirm it works all fine on master, I should have tried that too.
Thanks!
