### ISSUE TITLE
StandardFramework methods that take `Command`s do not hook aliases.

### ISSUE THREAD

**Issue by Celti** [serenity-rs/serenity#405]
The `cmd` methods on the `StandardFramework` and on `CreateGroup` take a prebuilt `Command`, while the `command` methods take a `CreateCommand`, but only the latter will insert any aliases in the resulting `Command`'s options into the framework/group.

Fixing it looks like it should be simple, just requiring duplication of the logic from `command` into `cmd`. Ideally the former could call the latter "under-the-hood", but that might not be practical.

**Comment by Mishio595** [comment]
The logic in `CreateGroup::command` isn't fully correct either, the aliases it iterates over are only those provided by the `CreateCommand`. The result is all aliases not included in `CreateCommand::known_as` or `CreateCommand::batch_known_as` are never registered with the framework as aliases.

**Comment by Mishio595** [comment]
Currently writing a fix
