### ISSUE TITLE
add .push_named_link(name, url) syntax

### ISSUE THREAD

**Issue by hyarsan** [serenity-rs/serenity#407]
And a _safe variant.
Just like .push_bold_safe(), .push_italics()...

**Comment by Chaosteil** [comment]
I want to take a stab at this, if that's ok!

**Comment by Chaosteil** [comment]
Ah, nevermind: Discord Markdown does not support links in this format, and the only way to display a link inline like this is in webhooks/embeds.

**Comment by zeyla** [comment]
A good way to go about this would probably be to have an `EmbedMessageBuilder` with embed content-only methods that `Deref`/`DerefMut`s to `MessageBuilder`.

**Comment by arqunis** [comment]
[Added](https://github.com/serenity-rs/serenity/commit/7c61f958b139159a6c4595f6c99d7812d69d339b).
