### ISSUE TITLE
Misinterpretted payload causes massive memory allocation

### ISSUE THREAD

**Issue by Roughsketch** [serenity-rs/serenity#421]
This is the first time I've ever seen this happen, but today my bot crashed due to a memory allocation bug. The logs I have hook onto the before/after methods on the framework and every command was closed, so I believe this isn't part of my bot.

In my logs I have this line:

```
memory allocation of 106716898359124560 bytes failedAborted (core dumped)
```

Angeline in the server interpreted that as characters and got  `{"t":"P` which certainly looks like a standard Discord JSON response.

Is this an issue with the library or one of its dependencies? I'm not sure how to debug further.

**Comment by ghost** [comment]
Closed because this is likely OpenSSL, if you see it on 0.6.x it can be re-opened.
