### ISSUE TITLE
Discriminator returns number instead of string

### ISSUE THREAD

**Issue by Bauke** [serenity-rs/serenity#460]
![image](https://user-images.githubusercontent.com/19501722/50724970-232e2b80-10ee-11e9-986e-0ccac019cff3.png)

An edge case but when your discriminator is "0001" or similar it will return it without the 0s because it's a number.

https://github.com/serenity-rs/serenity/blob/current/src/model/user.rs#L35

**Comment by dying** [comment]
You just have to do `user.id.0.to_string();` to return a string with the 000 number.

**Comment by Bauke** [comment]
Oh, lol. Thanks, I'll close this issue then. :P

**Comment by acdenisSK** [comment]
The `format!` family of macros also provides padding for situations like these:
```rust
let discrim = format!("{:04}", 1);
// discrim equals to `0001`
```
