### ISSUE TITLE
Serenity Discord invite link not working

### ISSUE THREAD

**Issue by youssefhabri** [serenity-rs/serenity#462]
As the title says, the discord link for the serenity server is not working. It says it's either expired or I don't have permissions to join.

**Comment by dying** [comment]
The invitation link works. It means you've been banished.

**Comment by youssefhabri** [comment]
I don't think I ever been to that server in the first place 🤔

**Comment by youssefhabri** [comment]
Ok, it seems to work from te client, but didn't from the browser.
It might something wrong on my end. Sorry taking your time, and thanks.
