### ISSUE TITLE
Non-existing feature in example 03

### ISSUE THREAD

**Issue by orion78fr** [serenity-rs/serenity#493]
The example 03 mentions the feature `methods` to have some utility methods on the model structs, but this feature doesn't seem to exist (at least in the master branch).
I think its new name is `utils`.

**Comment by Lakelezz** [comment]
This has been fixed on `current` via #560 and `v0.6.x` via https://github.com/serenity-rs/serenity/commit/c970f443e645121033b2b3605ba4f15d33b144f6.

Thanks for your issue!
