### ISSUE TITLE
Mutexes and RwLocks being used where concurrent datastructures will work better

### ISSUE THREAD

**Issue by xacrimon** [serenity-rs/serenity#502]
As it currently stands the Mutex/RwLock pattern is used a lot particularly with the cache. In large scale highly concurrent scenarios concurrent datastructures like chashmap and transactional memory rbtrees should do better.

**Comment by xacrimon** [comment]
After performing multiple benchmarks and integration tests it seems like the ccl crate https://docs.rs/ccl/1.2.2/ccl/ is the best option. It also outperforms all other options by a mile. Might something to work towards on v0.7.x.

**Comment by Lakelezz** [comment]
I'm really struggling to see the use for this. Can you give a concrete example where Serenity will greatly benefit from this?

Additionally, there is no link to said benchmarks.

**Comment by xacrimon** [comment]
The use case is having for example multiple mutable borrows athe same time and concurrent writes. Hold on. I'll be linking the benchmarks shortly. The most useful place for this is the cache.

**Comment by Lakelezz** [comment]
How would you use it on the cache?

**Comment by xacrimon** [comment]
Replacing hashmaps with concurrent hashmaps for example. This would prevent other threads from blocking while another thread is accessing the cache with a write.

**Comment by xacrimon** [comment]
I would gladly work on that for v0.7.x since ive got free time now.

**Comment by xacrimon** [comment]
@Lakelezz Here are some benchmarks. https://gitlab.nebulanet.cc/xacrimon/rs-hm-bench

**Comment by xacrimon** [comment]
The idea is to get rid of the global cache lock and either have multiple DHashMaps instead of hashmaps or one big DHashMap with enums to hold different stuff.

**Comment by xacrimon** [comment]
Already posted space benches in discord but here they are. Taken with u64 keys and values.

```
---
10k elems

mem heap usage rwlock_hashmap (KiB): 144
mem heap usage dhashmap (KiB): 148
---

---
75k elems

mem heap usage rwlock_hashmap (KiB): 1152
mem heap usage dhashmap (KiB): 1126
---
```

**Comment by xacrimon** [comment]
With some larger values

```
u64 keys and [u128; 16] values

10k elems
mem heap usage rwlock_hashmap (KiB): 4240
mem heap usage dhashmap (KiB): 4182

75k elems
mem heap usage rwlock_hashmap (KiB): 33920
mem heap usage dhashmap (KiB): 33937
```

**Comment by xacrimon** [comment]
Even larger values
```
10k elems u64 keys and [u128; 1024] values

mem heap usage rwlock_hashmap (KiB): 262288
mem heap usage dhashmap (KiB): 233105
```

DHashMap really gets ahead here.

**Comment by xacrimon** [comment]
Since you were concerned about the lib being tested enough. Take you time and check the implementation. Im not expecting this for 0.6.x. Ideally i'd like to take a look at the whole cache system/api. Maybe some subrelease of 0.6 or 0.7.

**Comment by xacrimon** [comment]
Closing this in favor of a cache redesign tracking issue.
