### ISSUE TITLE
Autosharded client random shutdown

### ISSUE THREAD

**Issue by JellyWX** [serenity-rs/serenity#521]
Experienced this with 2 bots. When autosharded, the bot will frequently but seemingly randomly miss a heartbeat and disconnect. The serenity process however does not close down following this and still holds its cache.

I'll add logs once I get somewhere where I can grab some

**Comment by ghost** [comment]
This may have been fixed since then and we don't have debug info, so if you get a chance to reproduce this please let us know.

**Comment by JellyWX** [comment]
This seems to have been resolved in latest 0.5 release
