### ISSUE TITLE
Serializing some objects outputs data that are not supported by the deserializer in 0.6

### ISSUE THREAD

**Issue by DarkKirb** [serenity-rs/serenity#528]
As an example, serializing a Ready event with `serde_json` results in the following json output:

```
{ "Ready": { "guilds": [ { "id": xxx, "unavailable": true } ], "presences": {}, "private_channels": {}, "session_id": "xxx", "shard": [ 0, 1 ], "_trace": [ "gateway-prd-main-", "discord-sessions-" ], "user": { "id": xxx, "avatar": null, "bot": true, "discriminator": 2877, "email": null, "mfa_enabled": true, "username": "Poyobot Dev", "verified": true }, "v": 6 } }
```

This output however is not supported when deserializing, namely `"presences"` and `"private_channels"` have a map type, even though the Deserializer wants a list type.

**Comment by Lakelezz** [comment]
Fixed since #529 is merged : )

Thanks for the issue!
