### ISSUE TITLE
`framework::standard::Configuration::on_mention` broken with removal of global Http in v0.6.x

### ISSUE THREAD

**Issue by Celti** [serenity-rs/serenity#530]
`Configuration::on_mention` previously used the global Http instance to get the bot's current user ID, and currently (as of cc81e47d) constructs a new independent Http instance, but this new instance has no access to the token for authorisation.

The easiest way forward I can see is for `on_mention` to take a UserId instead of a `bool`, in a similar fashion to `owners`.

**Comment by Lakelezz** [comment]
Please add what version/commit of Serenity you are using! : )

**Comment by Celti** [comment]
Derp, sorry. Branch and commit added.

**Comment by arqunis** [comment]
[Fixed](https://github.com/serenity-rs/serenity/commit/d995fa0e08c67e1a7f217b427d4d9b4dcedaa45b).
