### ISSUE TITLE
Attachment has a String id

### ISSUE THREAD

**Issue by shelvacu** [serenity-rs/serenity#536]
https://github.com/serenity-rs/serenity/blob/master/src/model/channel/attachment.rs#L14

According to discord's docs this is a snowflake like usual, so shouldn't it be an `AttachmentId` or at least a `u64`?

**Comment by Lakelezz** [comment]
I doubt there is any deep meaning to this, it's quite an old part of Serenity thus before most fields turned into u64-newtypes.

**Comment by Lakelezz** [comment]
This has been changed on `v0.6.x` via #559.

Thanks for your issue.
