### ISSUE TITLE
Add "time changed" event

### ISSUE THREAD

**Issue by Xaeroxe** [serenity-rs/serenity#541]
I have an action that I want my bot to perform at noon every day. I don't see a great way to do this with the library as is. The best I've got with it is to launch the bot executable at noon, then respond to the "ready" event. However, if you also wanted to have the bot responding to commands throughout the day this model falls apart.

So, the easiest change I can see to make this workable would be to launch a "TimeChanged" event every minute (or second, take your pick) that contains the current chrono timestamp.

**Comment by Xaeroxe** [comment]
@PixeLInc Can you elaborate on what confused you so that we can come to a better mutual understanding?

**Comment by Lakelezz** [comment]
Hello!

What do you want to do when this certain time is due? Send a message?

You can simply spawn a separate thread inside your main-thread and sleep/check until the desired time has passed. 
Alternatively, you can keep some time-trigger in your Context's data-field.

**Comment by Xaeroxe** [comment]
@Lakelezz Thanks for the response! and yes my task effectively summarizes to "Send a message if a series of other conditions are met"

I suppose I can just use the "guild" structures obtained from the "Ready" event in my separate thread. That hadn't occurred to me until now. I thought I would need access to the client.

> Alternatively, you can keep some time-trigger in your Context's data-field.

This seems like a learning opportunity for me. What would such a time trigger look like?

**Comment by PixeLInc** [comment]
@Xaeroxe I just rated confusing because a new event or something library related doesn't seem to be the way to go with this. It can easily be achieved via your own means rather than rolling out a whole new library feature  

Edit: unless I misread this and it's not a new feature request. In which case, woops hehe :)

**Comment by Xaeroxe** [comment]
Well I have a way forward on this, so I'm content closing this.

**Comment by allquixotic** [comment]
@Xaeroxe What was the solution you ended up using? I'm working on a bot that I want to have post a message once a minute (and delete a previous message). I could use the `Context` and `Ready` references passed into the `ready` event handler, like you suggested, but I'm not sure those will have permanent scope in the program. If the Discord shard chokes (as it often does...) and comes back, I would need new references to those, wouldn't I?

That is why I was thinking an event could be configured to fire periodically. Was thinking something with the semantics of [g_timeout_add](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add)() in GLib.

**Comment by Lakelezz** [comment]
I'm currently working on a new example for our example-folder that will provide a solution for timing-related issues, I hope I can publish it soon : )

**Comment by Lakelezz** [comment]
The example has been merged now, see following commit: https://github.com/serenity-rs/serenity/commit/10b9cc23bd22bc50732fc698c7af4c12c306f695

Example on the `v0.6.x`-branch: `12_timing_and_events`.
