### ISSUE TITLE
send_message creating 403 responses

### ISSUE THREAD

**Issue by thepixelmonk** [serenity-rs/serenity#542]
Using `message.channel_id.send_message()` creates a 403 forbidden response from discord, but making a direct http request to `https://discordapp.com/api/channels/123/messages` myself works fine. The bot connects and receives messages fine so it's not something obvious like providing the wrong token or something. Just when replying to messages I need to construct a manual http request.

The main difference I see right now is that I'm setting my Authorization header to `Authorization: Bot REDUCTED` and I think serenity is setting it to just `Authorization: REDUCTED`? In `request.rs` I see `headers.set(Authorization(TOKEN.lock().clone()));`

**Comment by arqunis** [comment]
I'm uncertain of the cause of the issue, but please try to be more careful in not revealing your token.
I'd advise you to go reset it now.

**Comment by thepixelmonk** [comment]
no worries, it's not my token, it's copy/pasted from discord's api examples.

**Comment by AregevDev** [comment]
I will try to reproduce this using one of my bots, is `channel_id.say` works for you?

**Comment by AregevDev** [comment]
Works fine for me, using my test bot, perhaps your token is wrong...

**Comment by Erk-** [comment]
@toovs Can you give an example of where it happens for you?

**Comment by thepixelmonk** [comment]
@AregevDev the token can't be wrong because it is receiving messages fine. I'll replace it with `say()` and see what happens.

@Erk- unfortunately the issue seems somewhat intermittent. when running the bot on my local computer, for example, it _usually_ works, but when running it on my server, it _usually_ doesn't. my manually created http request works fine all the time, though.

This is the codebase where it's happening: https://gitlab.com/toovs/babblebot/blob/master/src/types.rs#L19. As you can see `send_message()` is commented out right now.

**Comment by Mishio595** [comment]
Discord responds with a 403 when authorization passes (valid token), but a permission check fails. Please ensure that the bot has permissions to send messages in the channel you are attempting to send messages.

**Comment by thepixelmonk** [comment]
@Mishio595 my manually created http request works just fine for the same bot, so permissions should be fine.

**Comment by thepixelmonk** [comment]
Same thing happens with `say()`. Here's the response:

```
Err(Http(UnsuccessfulRequest(Response { status: Forbidden
, headers: Headers { Date: Tue, 23 Apr 2019 23:19:52 GMT
, Content-Type: application/json
, Content-Length: 44
, Connection: keep-alive
, Set-Cookie: __cfduid=d3cbc466412d203ddc713c8873119dc631
556061592; expires=Wed, 22-Apr-20 23:19:52 GMT; path=/; d
omain=.discordapp.com; HttpOnly
, Strict-Transport-Security: max-age=31536000; includeSub
Domains
, X-RateLimit-Limit: 5
, X-RateLimit-Remaining: 4
, X-RateLimit-Reset: 1556061598
, Via: 1.1 google
, Alt-Svc: clear
, Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
, Server: cloudflare
, CF-RAY: 4cc3909b3cb8732b-AMS
, }, version: Http11, url: "https://discordapp.com/api/v6/channels/564350210525102080/messages", status_raw: RawStatus(403, "FORBIDDEN"), message: Http11Message { is_proxied: false, method: None, stream: Wrapper { obj: Some(Reading(SizedReader(remaining=44))) } } })))
```

**Comment by Mishio595** [comment]
Can you please provide the following:
- version, branch, or commit of serenity you're using
- the debug output of the error returned by the failed request
- the manual request you've made, obviously with a redacted token

**Comment by thepixelmonk** [comment]
@Mishio595 version 0.5.13, output of the response is above, and manual request is here: https://gitlab.com/toovs/babblebot/blob/master/src/util.rs#L40

```rust
let body = format!("{{ \"content\": \"{}\" }}", &message);
let _ = discord_request_post(con.clone(), &self.channel, &format!("https://discordapp.com/api/channels/{}/messages", msg.channel_id.as_u64()), body);


pub fn discord_request_post(con: Arc<r2d2::PooledConnection<r2d2_redis::RedisConnectionManager>>, channel: &str, url: &str, body: String) -> reqwest::Result<reqwest::Response> {
    let token: String = con.hget(format!("channel:{}:settings", channel), "discord:token").unwrap_or("".to_owned());
    let mut headers = header::HeaderMap::new();
    headers.insert("Authorization", HeaderValue::from_str(&format!("Bot {}", token)).unwrap());
    headers.insert("User-Agent", HeaderValue::from_str("Babblebot (https://gitlab.com/toovs/babblebot, 0.1").unwrap());
    headers.insert("Content-Type", HeaderValue::from_str("application/json").unwrap());

    let req = reqwest::Client::builder().http1_title_case_headers().default_headers(headers).build().unwrap();
    let rsp = req.post(url).body(body).send();
    return rsp;
}
```

**Comment by Mishio595** [comment]
How are you setting the token in use by serenity?

**Comment by thepixelmonk** [comment]
That would be over here: https://gitlab.com/toovs/babblebot/blob/master/src/main.rs#L442

```rust
let res: Result<String,_> = con.hget(format!("channel:{}:settings", channel), "discord:token");
if let Ok(token) = res {
    let mut client = serenity::client::Client::new(&token, DiscordHandler { pool: pool.clone(), channel: channel.to_owned() }).unwrap();
}
```

**Comment by Mishio595** [comment]
I think I may understand now, but I feel like I'm still missing some pieces. Are you creating multiple clients? and at any point does the token in redis change?

**Comment by thepixelmonk** [comment]
Yeah there are multiple clients in different threads, token doesn't change.

**Comment by Mishio595** [comment]
Interesting. I'm not quite sure what your use case is for multiple clients but I'm thinking that may be at least in part what the issue is. I'll do some testing and see if I can repro this.

**Comment by thepixelmonk** [comment]
well the use case is just hosting different bots for different discord servers.

**Comment by thepixelmonk** [comment]
and the general connections seem fine and stable, all bots receive all messages just fine, I just have to make the http request when replying.

**Comment by Mishio595** [comment]
If you have multiple tokens in use, you're going to run into an issue with `0.5.x`. In this and all previous versions of serenity, we use a global HTTP client with a global token. If you create a new client, this overrides the token in use by the HTTP client, for *all* active serenity clients. That being said, if all clients are using the same token, there are no issues.

In `0.6.x` we're changing to a non-global HTTP client, which should make designs such as this easier to implement.

**Comment by Lakelezz** [comment]
This is what I assume is happening here too! When you login with a second bot, it overrides the token and invalidates the prior bot's connection.

> In `0.6.x` we're changing to a non-global HTTP client, which should make designs such as this easier to implement.

Well, it actually is pretty usable and done! : ) So it might solve your problem, simply try the `v0.6.x`-branch, examples are located here: https://github.com/serenity-rs/serenity/blob/v0.6.x/examples/05_command_framework/src/main.rs

**Comment by thepixelmonk** [comment]
thanks! I'll try the 0.6.x branch

**Comment by thepixelmonk** [comment]
and it sounds like we found the problem so I'll just go ahead and close this issue.
