### ISSUE TITLE
id.created_at() returns timestamp with second accuracy and not millisecond accuracy

### ISSUE THREAD

**Issue by DarkKirb** [serenity-rs/serenity#543]
According to the discord documentation, the top 42 bits of a snowflake contain the timestamp in millisecond accuracy.

Serenity however currently rounds down to the full second [in the `created_at()` method](https://github.com/serenity-rs/serenity/blob/9cc8816ec56295541230c87992500fee0aaa8696/src/model/id.rs#L15)

In other locations of the code (For example in `Message::timestamp`) millisecond accuracy is used already.

**Comment by arqunis** [comment]
[Fixed](https://github.com/serenity-rs/serenity/commit/965fa7bf088e5ee5a79efb0b7167478bb0fe719c).
