### ISSUE TITLE
Error when trying to use example 06

### ISSUE THREAD

**Issue by sasjafor** [serenity-rs/serenity#553]
When I try to use example 06, and then try to send a !play command with a youtube URL, I get this error: 

> Err starting source: Voice(YouTubeDLRun(Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "ERROR: dgha9S39Y6M: \"token\" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n" }))

Seems to me like it does parse the youtube video ID correctly but then doesn't pass it to ytdl in the correct way.

Using serenity version = "0.5.13" with this openssl compat patch:

> [patch.crates-io]
> openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }

**Comment by Lakelezz** [comment]
I assume you have tried the provided steps in your error-message?
When I got this error, doing as suggested fixed it for me.

**Comment by sasjafor** [comment]
I just have the most up to date ubuntu package for ytdl, but maybe that is not up to date enough. I'll try actually getting the newest youtube-dl and then check back.

**Comment by sasjafor** [comment]
My bad, yeah that was the problem. Thx for the the help!

**Comment by Lakelezz** [comment]
Glad it helped : ) Also, concerning your OpenSSL-patch, you might want to check out the latest released version, `0.6.0-rc.0`. It's a release candidate and available via crates.io, fixing the OpenSSL problem.
