### ISSUE TITLE
0.6.0-rc.0: delimiter not required between the command and the first argument

### ISSUE THREAD

**Issue by andreasots** [serenity-rs/serenity#554]
**Serenity version**: 0.6.0-rc.0
**Rust version**: rustc 1.34.1 (fc50f328b 2019-04-24)
**Minimal test case**:
```rust
use serenity::framework::standard::{Args, CommandResult, macros::{command, group}, StandardFramework};
use serenity::client::{Context, EventHandler};
use serenity::model::channel::Message;

group!({
    name: "a",
    commands: [
        a,
        ab,
    ],
});

#[command]
fn a(ctx: &mut Context, msg: &Message, _args: Args) -> CommandResult {
    msg.reply(ctx, "a")?;
    Ok(())
}

#[command]
fn ab(ctx: &mut Context, msg: &Message, _args: Args) -> CommandResult {
    msg.reply(ctx, "ab")?;
    Ok(())
}

struct Handler;

impl EventHandler for Handler {
}

fn main() {
    let mut client = serenity::Client::new("<TOKEN>", Handler).unwrap();
    client.with_framework(StandardFramework::new().configure(|c| c.prefix("!")).group(&A_GROUP));
    client.start().unwrap();
}
```
The bot should reply to `!ab` with `ab` but responds with `a` instead.

**Comment by arqunis** [comment]
You must switch the order so `ab` is first to achieve your desired behaviour.
The new framework has to check all command names **sequentially** — the order you defined them, to recognise that a piece of text belongs to a certain command. 

If `a` is defined first, it won't search further because there is a command named `a` and it hit that initially. The rest of the text is acknowledged as arguments to the command (available for access via the `Args` api).

**Comment by andreasots** [comment]
Interesting. The workaround doesn't help if an undefined command `!ac` is used because that still invokes `a` and not the unrecognised command handler. This is such a large change from the 0.5 behaviour that I can't use the standard framework anymore.

**Comment by arqunis** [comment]
I see, that is indeed problematic with the change in message parsing. I will attempt to push a fix as soon as possible then.

Sorry for ruining your day and opinion of the framework with this.

**Comment by arqunis** [comment]
[This should be resolved now](https://github.com/serenity-rs/serenity/commit/64e97c51367630f04d1d58ab917d584cd6e9c15a).
I decided to preserve this behaviour, but it will be turned off by default, as to not bring forth more surprises regarding this.

**Comment by andreasots** [comment]
Thanks!
