### ISSUE TITLE
The StandardFramework responds to bots to the help command while ignore_bots is set to true.

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#555]
While [Configuration::ignore_bots](https://docs.rs/serenity/0.5.13/serenity/framework/standard/struct.Configuration.html#method.ignore_bots) defaults to `true` the `StandardFramework` still responds to bots to help command.

[bot source @ serenity v0.5](https://github.com/nickelc/modio-bot/blob/e272f02d915eca085fd37a7bde144a5e9cd60cb2/src/main.rs#L79)

![image](https://user-images.githubusercontent.com/2128532/57654749-3b024880-75d5-11e9-93e5-105467758b69.png)

**Comment by Lakelezz** [comment]
Thanks for your issue : )

Fixed on `current` via https://github.com/serenity-rs/serenity/commit/e40758eefdbe5a2b62f252cde69e7dec04898a09.
Also fixed on `v0.6.x` via  https://github.com/serenity-rs/serenity/commit/b1559bc38f99a65cdf3231ddafa84c51b5829b1a.
