### ISSUE TITLE
Inconsistent naming of `owners_only` for group options in serenity and command_attr

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#562]
In serenity v0.6 it's named [framework::..::GroupOptions.owners_only](https://docs.rs/serenity/0.6.0-rc.1/serenity/framework/standard/struct.GroupOptions.html#structfield.owners_only).
In command_attr v0.1 macro [`group.options`](https://docs.rs/command_attr/0.1.0-rc/command_attr/macro.group.html#options) it's named `owner_only`.

**Comment by arqunis** [comment]
Fixed in [c:3cf673e](https://github.com/serenity-rs/serenity/commit/3cf673e670ecac615a1565ed4c96a513327f7e05).
