### ISSUE TITLE
Misleading error message when `options.prefix` is empty

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#563]
command_attr v0.1-rc
```rust
group!({
    name: "owner",
    options: {
        prefix: "",
        owner_only: true,
    },
    commands: [ping],
});
```
```
error: every group must have a set of `commands`
  --> src/main.rs:19:5
   |
19 |     options: {
   |     ^^^^^^^
```
while it probably should be 
https://github.com/serenity-rs/serenity/blob/03057f3dec3159776b1b9e3e728cda0c4ea0d4f3/command_attr/src/structures.rs#L544-L547

**Comment by nickelc** [comment]
Actually, all errors in `options` result into the misleading error message.

Based on 3cf673e 
```rust
group!({
    name: "owner",
    options: {
        prefix: "a",
        owner_only: true,
    },
    commands: [ping],
});
```

**Comment by arqunis** [comment]
Now should be informing the correct errors in [c:8e01ff6](https://github.com/serenity-rs/serenity/commit/8e01ff64fe5ed4e15a56dce2acd85574ae5a9d0c).
