### ISSUE TITLE
Inconsistency in help system when using `group.owners_only` and `#[owners_only]`

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#566]
if the ping command is annotated with `#[owners_only]` then help's respond is "No help available.".
if not then the ping command is listed as available.

```rust
group!({
    name: "owner",
    options: {
        owners_only: true,
    },
    commands: [ping],
});

#[command]
#[owners_only]
fn ping(ctx: &mut Context, msg: &Message) -> CommandResult {
    Ok(())
}
```

**Comment by Lakelezz** [comment]
Have you specified the owners? If not, `HelpOptions` is set to hide by default.

Ah, I just saw you are also have it set in the group. Yes, we will have an internal discussion on how we want to handle permissions/options in `0.6.x` as it is a bit trickier with sub-groups.

**Comment by nickelc** [comment]
i didn't set any owners for these test cases but thanks for the hint of the default help behaviors.
In both cases the command is rejected with `OnlyForOwners`.

**Comment by Lakelezz** [comment]
I applied some changes in #577, feel free to try it again.
