### ISSUE TITLE
Inconsistent parameter types of the builders

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#567]
```rust
CreateEmbed::title<D: Display>(&mut self, title: D) -> &mut Self
CreateEmbed::image<S: AsRef<str>>(&mut self, url: S) -> &mut Self
CreateEmbed::url<S: AsRef<str>>(&mut self, url: S) -> &mut Self

CreateEmbedAuthor::name(&mut self, name: &str) -> &mut Self
CreateEmbedAuthor::url(&mut self, url: &str) -> &mut Self
CreateEmbedAuthor::build(&mut self) /// ???

CreateEmbedFooter::text<D: Display>(&mut self, text: D) -> &mut Self
CreateEmbedFooter::icon_url(&mut self, icon_url: &str) -> &mut Self
CreateMessage::content<D: Display>(&mut self, content: D) -> &mut Self

EditChannel::name(&mut self, name: &str) -> &mut Self
EditGuild::name(&mut self, name: &str) -> &mut Self
EditMember::nickname(&mut self, nickname: &str) -> &mut Self
EditMessage::content<D: Display>(&mut self, content: D) -> &mut Self
EditProfile::email(&mut self, email: &str) -> &mut Self
EditProfile::username(&mut self, username: &str) -> &mut Self
EditRole::name(&mut self, name: &str) -> &mut Self
```

**Comment by Lakelezz** [comment]
Thanks, we got informed about this before too! 
Should be fixed now via #569.

**Comment by nickelc** [comment]
sorry, but the `build` method was actually not the point of this issue.

**Comment by Lakelezz** [comment]
@Erk- suggested that you might be referring to rest of the API too. We will fix the rest.

Nonetheless, a bit more text would be helpful.

**Comment by ghost** [comment]
All of these that take references shouldn't, since all of their parameters are turned into owned strings.

**Comment by nickelc** [comment]
The listing shows that for string parameters three different parameter types are used across all the builders `AsRef<&str>`, `std::fmt::Display` or `&str`.
That makes the builder api annoying to use when you have to handle them all different.

**Comment by arqunis** [comment]
[They all now take anything `ToString`-able](https://github.com/serenity-rs/serenity/commit/13fae29e053dda813448dca97c667d4b5a0519a4).
