### ISSUE TITLE
YouTube Videos are not fully played

### ISSUE THREAD

**Issue by Lakelezz** [serenity-rs/serenity#573]
Any Youtube-URL passed to `play` in the sixth example on `v0.6.x` will play but end before the video is over.

E.g. a video/song would play for one minute but is actually played for 30 seconds~.

**Comment by FelixMcFelix** [comment]
Attempted adding some flags for reconnection to ffmpeg, to no avail.
Replacing [these lines](https://github.com/serenity-rs/serenity/blob/v0.6.x/src/voice/streamer.rs#L136-L146) with:
```rust
    _ffmpeg_optioned(path, &[
        "-report",
        "-f",
        "s16le",
        "-ac",  
        stereo_val,
        "-ar",
        "48000",
        "-acodec",
        "pcm_s16le",
        "-reconnect", "1",
        "-reconnect_streamed", "1",
        "-reconnect_delay_max", "5",
        "-",
    ], Some(is_stereo))
```
still fails, producing [this output](https://github.com/serenity-rs/serenity/files/3212498/ffmpeg-20190522-195430.log).

**Comment by Lakelezz** [comment]
Has been fixed with https://github.com/serenity-rs/serenity/commit/4793a8482915b6a4438b5e209144d0fa5f0948ca.
