### ISSUE TITLE
Confusing documentation on EventHandler::cached

### ISSUE THREAD

**Issue by shelvacu** [serenity-rs/serenity#590]
Currently the documentation says:

```text
Dispatched when the cache gets full.

Provides the cached guilds' ids.
```

When I first read this (and every subsequent time until I happened to look at the code that calls it), I thought this meant that the function will be called when the cache exceeds some pre-set limit for number of channels it's willing to store.

**Comment by Lakelezz** [comment]
Thanks for this issue, the documentation has been improved, see: #594
