### ISSUE TITLE
Not working command in `group` macro doc & meaningless error message

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#619]
The example in [group macro](https://docs.rs/command_attr/0.1.0/command_attr/macro.group.html) shows a not working `bar` command and will result in a meaningless error message. It should hint `CommandResult` as return type.
```rust
#[command]
fn bar() {
    println!("baz");
}
```
```text
error: expected a return type
  --> src/commands.rs:15:10
   |
15 |   fn bar() {
   |  __________^
16 | |     println!("baz");
17 | | }
   | |_^
```

**Comment by arqunis** [comment]
Taken care of in [c:c8a8d4f](https://github.com/serenity-rs/serenity/commit/c8a8d4f2f5b351def970b344045a16d0504d9d8f).
