### ISSUE TITLE
#[bucket] attribute is not listing on #[command] doc

### ISSUE THREAD

**Issue by nickelc** [serenity-rs/serenity#620]
The attribute appears only once in the `StandardFramework::bucket` example.

[#[command] doc](https://docs.rs/command_attr/0.1.0/command_attr/attr.command.html)

**Comment by arqunis** [comment]
Addressed in [c:0daaac1](https://github.com/serenity-rs/serenity/commit/0daaac1519e7b583c9d1ea9e31779d7e6d00e5a0).
