### ISSUE TITLE
http::get_guild panics on guilds without Nitro boosters

### ISSUE THREAD

**Issue by xSke** [serenity-rs/serenity#623]
I have a guild without any Nitro boosters, and trying to http::get_guild it panics the JSON decoder. This is because the JSON object contains `"premium_subscription_count": null`, while the field in the Rust struct is defined as `pub premium_subscription_count: u64`.

The error itself is `Json(Error("invalid type: null, expected u64", line: 1, column: 239))`, and sure enough if I `curl` the endpoint myself, column 239 corresponds to `"premium_subscription_count": null`.

I'm working on a PR for this myself, but I thought I'd log the issue beforehand in case I forget/am not able to fix it.

EDIT: This is on Serenity version `0.6.0-rc.2.1`, rustc version `rustc 1.35.0 (3c235d560 2019-05-20)`

**Comment by Lakelezz** [comment]
Thank you! As it can be seen, fixed with #624.
