### ISSUE TITLE
Add `secretbox` as alternative for the `sodiumoxide`-backend

### ISSUE THREAD

**Issue by DarkKirb** [serenity-rs/serenity#644]
The `sodiumoxide` crate is currently used to encrypt data for discord voice support. As a wrapper around a C-library it might not work on some platforms.

Additionally the upstream library used by `sodiumoxide` (`libsodium`) sometimes replaces some release tarballs, causing build failures for example on windows. (see  jedisct1/libsodium#813, sodiumoxide/sodiumoxide#326)

As a replacement i have recently written a crate called `secretbox`. It supports everything serenity uses `sodiumoxide` for currently and does so without a C-Library dependency.

**Comment by kangalio** [comment]
What's the state of this? secretbox seems to be deprecated
![Screenshot_20221026_010719](https://user-images.githubusercontent.com/21220820/197898604-71a75391-1f1b-45a1-903e-b660b8bb0bf6.png)

Should serenity get crypto_box as an additional backend instead?

**Comment by nathaniel-daniel** [comment]
Pretty sure this was only used for voice support, which got separated out into `songbird`. `songbird` seems to use `xsalsa20poly1305` now from RustCrypto, which is pure Rust.
