### ISSUE TITLE
Client keeps trying to auto-reconnect with invalid token

### ISSUE THREAD

**Issue by Aely0** [serenity-rs/serenity#647]
Expected behavior would be to return an `Err` when using one of the client's start methods.
Logs: https://gist.github.com/Andris0/ff247482075a19fb8c99e667537ac4a4

Serenity: `0.6.2`
Rust: `1.35.0 (3c235d560 2019-05-20)`

**Comment by Lakelezz** [comment]
How are we supposed to check if the entered token is valid?
We can check for the format, that is about it. Maybe check what Discord returns.

**Comment by Aely0** [comment]
My current knowledge of serenity's internals are negligible, so I'm sure there is a better way to incorporate something like this.

The simplest solution that comes to mind would be to make a simple `GET` at `/users/@me` with the given token at the very start to see if all the actual setup is necessary at all or we can just return early with an error. A quick check on `200`/`401` for an invalidated or malformed token. 

With how things are now, I had a situation of copying an incomplete token that was missing a character at the end, did not notice it when I was moving it around. Since the client actually ran, some time was spent poking at the cache, trying to capture different events and trying to figure out why was I not seeing anything come in.

**Comment by anyputer** [comment]
Another thing worth mentioning is that the token passed can change at any time. Say you're reading from a text file, or something.

**Comment by Mishio595** [comment]
I've already discussed this in the Discord, so I'll go ahead and explain it here.

The proper solution to this comes in 2 parts.
1) If http is enabled, make a GET request to `/gateway/bot` prior to establishing the gateway connection.
2) Properly handle the 4004 websocket close code

Explanation:
Making a GET request to `/gateway/bot` is the proper method of retrieving important information regarding the gateway connection, prior to connecting. This includes the URL to use, the number of shards Discord recommends, and session start limit information. This endpoint is not only necessary, but requires authentication. If the call to this endpoint fails for any reason, the bot should not start.

The 4004 websocket close code is the only unrecoverable close code. Valid authentication doesn't magically change between IDENTIFY payloads and we should not attempt to automatically reconnect if we receive this close code.

**Comment by Lakelezz** [comment]
This has been addressed Serenity.await's pull request: #803.
