### ISSUE TITLE
reqwest sync client makes it impossible to use own tokio executor

### ISSUE THREAD

**Issue by DoumanAsh** [serenity-rs/serenity#648]
More JFYI, but attempting to send any API request from within context of another tokio executor will fail with error: `Err(Http(Request(Error(Executor(EnterError { reason: "attempted to run an executor while another executor is already running" })`

Doubt that it can be fixed because sync reqwest sucks

**Comment by nickelc** [comment]
You can workaround this problem with channels.
https://github.com/nickelc/modio-bot/blob/1360d9eb8f699218853178f2dd4c168b5476cfee/src/commands/game.rs#L15-L39

**Comment by DoumanAsh** [comment]
Yes, I know I'll be fine as long as I send requests outside of tokio's executor context
I only stated the issue as JFYI, in case someone will bump into it

**Comment by nickelc** [comment]
And i mentioned the workaround in case someone will bump into it.

**Comment by Lakelezz** [comment]
Yes, this has been reported internally before. It will likely be resolved once Serenity becomes async.
Either way, this is out of interest for sync Serenity.
