### ISSUE TITLE
Crash when delete received for mystery channel category

### ISSUE THREAD

**Issue by mqp** [serenity-rs/serenity#654]
I'm a user of [weechat-discord](https://github.com/terminal-discord/weechat-discord), which uses Serenity (specifically, I was running [this recent commit](https://github.com/serenity-rs/serenity/commit/6f8e8f826468d25e115c3f979d4a06b5dad6811b)), and I encountered a crash with the following message:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /...serenity.../src/model/event.rs:157:43
```

It seems the relevant code is trying to handle channel delete events: https://github.com/serenity-rs/serenity/blob/current/src/model/event.rs#L157

If it happens again, I'll have a stack trace, and I'll see if I can reproduce the issue on my test Discord server.

**Comment by Flat** [comment]
1. Custom clients are against the Discord ToS
2. They use a custom fork of serenity https://github.com/terminal-discord/serenity I would suggest you raise the issue with them.

The commit you specifically mention is not part of the Serenity code base.

**Comment by mqp** [comment]
Oh, sorry, I didn't realize it was a fork. I just reproduced the issue, though, and I think it's relevant to the Serenity main line as well -- if I click "x" in the first-party Discord client to close a DM, it sends a channel delete on a channel of type "DM" and the crash occurs.

**Comment by Flat** [comment]
Can't replicate any issues or crashes on my bot using Serenity proper by closing a DM channel with my bot. I believe channel closing is a userbot endpoint only. If you can provide simple steps to replicate the issue using the main Serenity repository and a Bot token feel free to open another issue.

**Comment by mqp** [comment]
That makes sense, I can see why this is not a problem for bots. I will double-check to see if there is any obvious way to make this happen with a bot token, or work around it with the weechat-discord folks.
