### ISSUE TITLE
`Message::reply` shouldn't mention users in private DMs

### ISSUE THREAD

**Issue by anyputer** [serenity-rs/serenity#663]
When you use it in a guild, it mentions the user. But I'm not sure why you would want it to ping in a DM channel? It should just have the content when `Message::reply` is used in private DMs.

**Comment by F4stZ4p** [comment]
Works as intended

**Comment by anyputer** [comment]
It isn't a question

**Comment by anyputer** [comment]
nvm i'll do a pr later
