### ISSUE TITLE
What's the most straightforward way to get the current `GuildId` in an EventHandler?

### ISSUE THREAD

**Issue by mkaito** [serenity-rs/serenity#665]
I'm trying to get the current guild from within a `reaction_add` handler. Here's what I came up with:

```rust
        let channel = reaction.channel(&ctx).unwrap();
        let gchannel = channel.guild().unwrap();
        let read_lock = gchannel.read();
        let guild_id = read_lock.guild_id;
        debug!("Found guild {:?}", guild_id);
```
Is there a shorter way to go about this?

**Comment by Lakelezz** [comment]
Do you want a `GuildId` or a `Guild`?
Your code suggests the first.

As you did not specify what version of Serenity you are using, here a link to v0.6.2 (not that this changed recently anyway), the `GuildId` sits optionally on the `Message`-struct.
https://docs.rs/serenity/0.6.2/serenity/model/channel/struct.Message.html#structfield.guild_id

**Comment by mkaito** [comment]
Actually, I only need the `GuildId` to go from `Reaction::user` to a `Member`. I'm using 0.6.2 indeed.

**Comment by mkaito** [comment]
Tangentially, is there a better way to ask such questions than an issue on github?

**Comment by Erk-** [comment]
The official Discord server:  https://discord.gg/WBdGJCc is a good place to ask them.

**Comment by Lakelezz** [comment]
Yes, on our Discord, check headline on https://github.com/serenity-rs/serenity for the link.

**Comment by PixeLInc** [comment]
If you have discord you can join either the serenity server (https://discordapp.com/invite/WBdGJCc) or the Discord API server and head over to the serenity channel :)

**Comment by mkaito** [comment]
I'm already on the Discord API server, and joined the Serenity server. Thanks!
