### ISSUE TITLE
Support for getting multiple activities from a user

### ISSUE THREAD

**Issue by LeSplooch** [serenity-rs/serenity#673]
Discord shows only one activity per user in its GUI, but it can handle multiple activities and it would be nice to be able to get multiple activities from a user. 

I'm currently rewriting my bots from Python 3.7.3 & discord.py 1.2.2 to Rust 1.36 & Serenity 0.6.3 to discover the magic of Rust, but one of my functions can't be rewritten because it needs to get multiple activities from a user to get the game he's playing even when Spotify shows instead, or to get all of the games a user is playing, stuff like that.

I have some other ideas for Serenity, such as getting an activity directly from a `User`/`Member`/`UserId` (if there already is a way to do it, please tell me how), but I don't know if I should make other Github issues, I don't mean to spam. Sorry btw if it's the wrong place to ask that.

Thank you for reading me and for making this awesome crate.

**Comment by AregevDev** [comment]
Can you send a python example of getting multiple activities?
I am not sure how it is done.

**Comment by LeSplooch** [comment]
As I'm not really sure what can help you, I'll send you everything I think can be useful for you.

- An example of how I use discord.py to get multiple activities in my code : https://pastebin.com/yz7cZaVu (couldn't get the code block to display it properly, sorry)

- The doc leading to the `activities` attribute of the class `Member` : https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.activities

And finally :
- This is how it's handled in the library's code : https://github.com/Rapptz/discord.py/blob/master/discord/member.py

Hope all of these can help you, tell me if you need something more or if I'm missing something.

**Comment by Zaitara** [comment]
Support was added in #1043
