### ISSUE TITLE
Add an example for user moderation

### ISSUE THREAD

**Issue by GrayJack** [serenity-rs/serenity#709]
I wondered how to do it, but there is no example of it

**Comment by Lakelezz** [comment]
Hello, thank you for your issue!

Could you elaborate what you would expect from or in such an example?

**Comment by GrayJack** [comment]
My end goal with my bot is to set/remove roles to people that call it and also kick people out in centain circumstances

**Comment by Lakelezz** [comment]
You can find all what you need on the `Member` struct's methods: https://docs.rs/serenity/0.7.0/serenity/model/guild/struct.Member.html#methods

See `add_role`, `remove_role`, and `kick`. The members are located on the `Cache`, you can grab them via [`Cache::member`](https://docs.rs/serenity/0.7.0/serenity/cache/struct.Cache.html#method.member).

If you have any further questions, feel free to ask. We also have a Discord for quick help :)

I'm not sure if this worth an example on its own, we will have to consider it.

**Comment by boehs** [comment]
I think given the detailed nature of the examples already moderation commands are within scope, if not fairly easy for anyone somewhat proficient in rust to implement

**Comment by kangalio** [comment]
Can we close this issue or is there objection?

**Comment by jamesbt365** [comment]
While this is a very common reason people make discord bots, the documentation exists and a lot of features typically tie into each other.

The examples more or less should show how to get started and how parts like builders work (considering the fact that they are mostly universal), so we don't realistically need an example for moderation actions.

Though, they wouldn't be much to maintain if anybody wants to submit one. But providing examples for everything neglects the documentation, and makes users rely too much on getting examples on absolutely everything the library can provide.

**Comment by ivinjabraham** [comment]
Is there a reason why this issue is still up?
