### ISSUE TITLE
[Help Command] Usage and Example are not distinctly named in the output.

### ISSUE THREAD

**Issue by HeapUnderfl0w** [serenity-rs/serenity#722]
In the output of the plain help command (`help_commands::plain` from the standard framework), usage and example are both named "usage":  
```
__**add**__ 
**Description**: Add a new birthday to the list 
**Usage**: birthday add [mention or id] [month]/[day] 
**Usage**: birthday add 102379663615094784 03/10 
**Group**: birthday 
**Available**: Only in guilds
```
the expected output is
```
__**add**__ 
**Description**: Add a new birthday to the list 
**Usage**: birthday add [mention or id] [month]/[day] 
**Example**: birthday add 102379663615094784 03/10 
**Group**: birthday 
**Available**: Only in guilds
```
the `help_commands::with_embeds` option does not have this problem (Example is named `Sample usage` there)

**Comment by arqunis** [comment]
Fixed in [`c:d427da4`](https://github.com/serenity-rs/serenity/commit/d427da4a17dd78fe5f4f681855e028abb3fbccee).
