### ISSUE TITLE
Bring #[description] in line with rust's #[doc] 

### ISSUE THREAD

**Issue by HeapUnderfl0w** [serenity-rs/serenity#723]
Rust's doc attribute can be used multiple times to add newlines without awkwardly splitting the strings over newlines:
```rust
#[doc = "This is"]
#[doc = " a "]
#[doc = "doc comment"]
```
is equivalent to
```rust
#[doc = "This is\n a \ndoc comment"]
```
[Offical Docs](https://doc.rust-lang.org/rustdoc/the-doc-attribute.html)  
I would like that  the `#[description]` macro would support the same (or at least a similar) behavior.

**Comment by arqunis** [comment]
Fixed in #724.
