### ISSUE TITLE
Generic instead of `ShareMap` as `data`

### ISSUE THREAD

**Issue by MOZGIII** [serenity-rs/serenity#728]
How about we generalize the `Client` over the `data` value:

```rust
pub struct Client<TData: Send + Sync> {
    // ...
    data: TData,
}
```

This looks much more flexible than just using `ShareMap`. We can also provide the following type:

```rust
struct StandardData<T: Send + Sync> {
    custom: T,
    shard_manager: serenity::client::bridge::gateway::ShardManager,
    #[cfg(feature = "voice")]
    voice_manager: serenity::client::bridge:: voice::ClientVoiceManager,
}
```

...and let people use it instead of `data: TData`.

Why do all this? Simple: current API relies on `ShareMap`, and commands aren't aware of the actual shape of the `data` at compile time, and have to do runtime assumptions and assertions.

It would be much more pleasant to work with the code that simply guarantees presence of a data field at compile time, rather than to handle it's possible absence at runtime.

In addition to the advantages above, this would clarify that the `data` filed is for the *user's use only*. Right now, I'm not sure what serenity stores at the `ShareMap` besides my data items. There's nothing preventing it from using the `data` in it's own ways. But that's bad, I'd rather prefer a more explicit API so that I know what to expect.

With this paradigm, commands would have to specify the data they're using at the `Context`.

```rust
pub struct Context<TData: Send + Sync> {
    pub data: TData,
    // ...
}
```

```rust
struct MyData;

#[command]
fn ping(ctx: &mut Context<MyData>, msg: &Message) -> CommandResult {
    let _ = msg.reply(&ctx, "Pong!");
    Ok(())
}
```

I have to say that this would be 10 times less annoying to me than `unwrap`-ing the `data.get::<...>()` all the time.

**Comment by MOZGIII** [comment]
I’m working on a PR for that to provide an actual implementation. It will be a breaking change, however the upgrade path can be made easy.

**Comment by Lakelezz** [comment]
The [new framework](https://github.com/serenity-rs/framework) will use a generic data type instead of the type map.
