### ISSUE TITLE
Existence of a v5.10 tag

### ISSUE THREAD

**Issue by Juici** [serenity-rs/serenity#732]
The existence of the [v5.10](https://github.com/serenity-rs/serenity/tree/v5.10) tag causes the most recent version on Github to be reported incorrectly.

The [v5.10](https://github.com/serenity-rs/serenity/tree/v5.10) tag is a duplicate of the [v0.5.10](https://github.com/serenity-rs/serenity/tree/v0.5.10) and the creation of it appears to have been a mistake.

**Comment by arqunis** [comment]
The tag has been deleted.
I also apologise for overlooking this accidental tag, I don't remember how I caused a duplicate to occur, but I hope its removal should make further trouble no more.
