### ISSUE TITLE
Nightly-only?

### ISSUE THREAD

**Issue by nic-hartley** [serenity-rs/serenity#735]
While trying to run the Ping example, on stable, I get an error while compiling tokio-rustls: `error: enum variants on type aliases are experimental`

If serenity is _meant_ to be nightly-only, can the documentation please be updated to indicate that? If not, can the dependency on a nightly-only crate be removed? If this is the result of a specific feature, can the documentation include a list of which features require nightly and which don't?

**Comment by Erk-** [comment]
It was stabilized in [1.37](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language-1)  but that means that we have to update your minimum required version.

**Comment by nic-hartley** [comment]
Just to confirm: After updating to 1.38.0 this does now work on stable. Thanks!

That said, I'm not sure how to handle this in the broader case. A required version bump is a big change, but at the same time, requiring nightly (on older versions) is _also_ annoying. As an interim fix, maybe a note in the documentation that <1.37.0, serenity is nightly-only? It'd at least be a hint to update.

**Comment by Erk-** [comment]
It appears that we actually set the minimum to 1.37 a few months ago (https://github.com/serenity-rs/serenity/commit/de9e8a673f906311957bb2f6e31026cc57fd86b1), together with the release of the breaking release 0.7 but forgot to update it everywhere in the readme, @acdenisSK did that yesterday to make it up to date (https://github.com/serenity-rs/serenity/commit/bcf96af9cafffdea9c891618eb56dc95c385628c).
