### ISSUE TITLE
Argument parsing for commands

### ISSUE THREAD

**Issue by LeSeulArtichaut** [serenity-rs/serenity#750]
This feature’s goal is to make it easier and shorter for programmers to parse command arguments.

Currently, one has to write quite a lot of boilerplate code to parse arguments in every command. This can be quite redundant for commands that take similar parameters (for example, a ban and a kick command might take a `target` Member and an optional `reason`).
However, we can make use of procedural macros to generate the parsing code for the user, and reject bad command invocations in the process.

Here is a TODO list of what I think should be done for this feature:
- [ ] Create a `CommandArgument` trait, which represent a type that can be created from command argument(s)
- [ ] Write the macro itself
- [ ] Provide a blanket implementation of this trait for `FromStr`
- [ ] Provide implementation of the trait for every model object that could be created from a command arg (such as `Member`, `Channel`...)
- [ ] Handle `Option`al arguments
- [ ] Handle Greedy arguments and pass it as a Vec
- [ ] Provide rest of arguments somehow

**Comment by Lakelezz** [comment]
As there is an on-going [rework of the framework ](https://github.com/serenity-rs/framework)and this issue is stalled with no progress on it, I will close it.
