### ISSUE TITLE
Expose reqwest::blocking::multipart::Part::reader in AttachmentType

### ISSUE THREAD

**Issue by leo60228** [serenity-rs/serenity#768]
Currently, serenity supports AttachmentType::File (corresponding to Part::reader, but limited to std::fs::File), AttachmentType::Bytes (corresponding to Part::bytes), and AttachmentType::Path (corresponding to Part::file). An AttachmentType::Reader could be added (unclear how this would affect existing code unless a trait object is used).

**Comment by Lakelezz** [comment]
Thanks for the issue.

Nonetheless, as we moved away from `reqwest::blocking`, please check if this issue pertains, otherwise, feel free to update the issue and/or pull request! 

I will close this issue as this seems outdated/stalled.

**Comment by leo60228** [comment]
I'd still consider this to be an issue, since https://docs.rs/serenity/0.10.2/serenity/http/enum.AttachmentType.html provides no way to stream from anything that isn't a file. However, the implementation is less clear with async reqwest. Perhaps something like a `Box<dyn Stream<Item = Result<Vec<u8>, Box<dyn Error + Send + Sync>>> + Send + Sync + 'static>`?

**Comment by vicky5124** [comment]
The issue with that is that AttachmentType is not only used for message attachments, but it's also being used for adding files to webhooks (https://serenity-rs.github.io/serenity/current/serenity/builder/struct.ExecuteWebhook.html#method.add_file)
While normal message attachments allow for multipart form streams, adding a file to a webhook requires the file data to be encoded as base64 and sent as a json field in text.
This means that if you provide a stream, the library internally would have to collect the entire stream to generate that data, which would defeat the point of a stream in the first place, but it would also be something unexpected, as it would be loading the entire thing in memory, causing a higher than expected memory usage.

**Comment by leo60228** [comment]
>  While normal message attachments allow for multipart form streams, adding a file to a webhook requires the file data to be encoded as base64 and sent as a json field in text.

Are you sure? I don't believe that's the case.

**Comment by leo60228** [comment]
Files uploaded in webhooks are sent as multipart attachments: https://github.com/serenity-rs/serenity/blob/dcc1ac4d0a12f24e998af3949e33ec352153a6af/src/http/client.rs#L1328-L1409

I'm not sure why you're reading to a buffer.
