### ISSUE TITLE
Support for User Connections

### ISSUE THREAD

**Issue by alcjzk** [serenity-rs/serenity#774]
https://discordapp.com/developers/docs/resources/user#get-user-connections

**Comment by AhiVT** [comment]
@alcjzk @acdenisSK I have a code snippet for this that might be adapted for Serenity. I'll post a gist when I have free time

**Comment by AhiVT** [comment]
@acdenisSK https://gist.github.com/Dunklheit/9f975029dcd72721d32e4786cbaf9677
