### ISSUE TITLE
Add model::user::User::OnlineStatus

### ISSUE THREAD

**Issue by halbGefressen** [serenity-rs/serenity#782]
I'd love to have an opportunity to see if a user is online without asking the API if all users are online. Is that possible?

**Comment by arqunis** [comment]
This is already available in the [`Presence`](https://docs.rs/serenity/0.8.0/serenity/model/gateway/struct.Presence.html) struct, which describes the status and other similar information of a `User`.
<https://docs.rs/serenity/0.8.0/serenity/model/guild/struct.Guild.html#structfield.presences>
<https://docs.rs/serenity/0.8.0/serenity/cache/struct.Cache.html#structfield.presences>
