### ISSUE TITLE
Fire hyperlink leads nowhere

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#784]
https://docs.rs/serenity/0.8.0/serenity/http/client/struct.Http.html#method.request

The "fire" hyperlink found on the second line of this entry on the documentation leads to a "The requested resource does not exist" page.

Steps to reproduce: 
1: Click the hyperlink
2: Contemplate the error page.

**Comment by arqunis** [comment]
This is already fixed on [master](https://github.com/serenity-rs/serenity/commit/1361b3377ebf00fb31375f5010863f59b66c3f3a). The documentation hasn't been regenerated yet, as it only gets build on new crates.io releases.
