### ISSUE TITLE
Future Development of Serenity

### ISSUE THREAD

**Issue by Lakelezz** [serenity-rs/serenity#786]
This issue tries to look into what's highly requested and where the limited development power should go to.
I would like to know what you want to have in Serenity! Please reason why :)
As async Serenity is already in development, I will leave that out of this issue.

Here are some plans in no particular order:

- New Voice
Serenity has bare minimum support for voice activities. A playlist support could be one of the many things we could have. See issue #633 

- New Help System
Improving customisability, improving code, and maybe looking into paged help. Note, paged help is already possible if you make your own help function.

- New Cache 
There are some tricky deadlock cases that could hugely benefit from a redesign. See issue #584 

- New Bucket System
The current bucketing is very simple. Fine-grained buckets, that can be manually invalidated, serialised, could be useful.

- Framework Rework
Maybe a dynamic framework could be interesting. 

This list are thoughts I came up with, if there is anything else, feel free to mention and explain it!
Looking forward for your thoughts and wishes, thanks for your time.

**Comment by moxian** [comment]
The most requested feature I see is "i want to create a poll, and have my bot do something, when people react to this specific message in a specific way" (e.g. "assign role A when reacting with emoji A, and kick from the server when reacting with emoji B").

Maybe in more generic terms - the ability to dynamically create long-lived(?) callbacks tied(??) to specific messages.

**Comment by evieluvsrainbows** [comment]
A feature I'm interested in seeing in the future is a collector system, like Discord.js has. Collectors would allow bot developers to write, for example, commands that listen for user input after an  initial command has been sent, and respond with extra information. One example would maybe be network-based search commands, like a command that uses an API to e.g. search for songs from Spotify, and if there are multiple search results matching their query, allow users to pick which result they want, and then respond with the appropriate result. Could also be useful for e.g. reactions.
