### ISSUE TITLE
Mention_channels vec from Message is not returned when there is text in the message.

### ISSUE THREAD

**Issue by Nukiloco** [serenity-rs/serenity#792]
For some odd reason when trying to get the vec of mention_channels from Message, it will return None if there is other text in the message. If there is no text in the message and only a channel mention, then it will return.

**Comment by evieluvsrainbows** [comment]
This seems to be an even greater bug for me on serenity `current`: The function returns None regardless as to if there's a standalone channel mention, or a channel mention with text. Really strange...

**Comment by tmokenc** [comment]
From [Discord documentation](https://discordapp.com/developers/docs/resources/channel#message-object)
>Not all channel mentions in a message will appear in mention_channels. Only textual channels that are visible to everyone in a lurkable guild will ever be included. Only crossposted messages (via Channel Following) currently include mention_channels at all. If no mentions in the message meet these requirements, this field will not be sent.

**Comment by Lakelezz** [comment]
This issue would be solved after adding the criteria in the docs with a link to the API's explanation.

**Comment by zacck-zz** [comment]
Hey @Lakelezz  I would like to try and complete this, which documentation would I need to update?

**Comment by Lakelezz** [comment]
> 
> 
> Hey @Lakelezz I would like to try and complete this, which documentation would I need to update?

You would need to update the documentation for `Message::mention_channels`.

**Comment by zacck-zz** [comment]
@Lakelezz  I tried something, wondering if that achieves what we are aiming for?
