### ISSUE TITLE
Configuration.dynamic_prefixes() expects impossible type

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#793]
[Message Jump](https://discordapp.com/channels/381880193251409931/381912587505500160/679452185842679808 ) | [ScreenShot](https://5124.16-b.it/ss/23:35:27_18-02-2020.png)
Discord message explaining the issues way better than i will ever do any time soon.

`dynamic_prefixes()` is currently unuseable as it's impossible to satisfy the required type for the iter argument.

Tested code with errors:
```
error[E0631]: type mismatch in closure arguments
   --> src/main.rs:356:31
    |
356 |             .dynamic_prefixes(vec![|_,_| {Some("test".to_string())}])
    |                               ^^^^^-----^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                               |    |
    |                               |    found signature of `fn(_, _) -> _`
    |                               expected signature of `for<'r, 's> fn(&'r mut serenity::client::context::Context, &'s serenity::model::channel::message::Message) -> _`
    |


error[E0271]: type mismatch resolving `for<'r, 's> <[closure@src/main.rs:356:36: 356:68] as std::ops::FnOnce<(&'r mut serenity::client::context::Context, &'s serenity::model::channel::message::Message)>>::Output == std::option::Option<std::string::String>`
   --> src/main.rs:356:14
    |
356 |             .dynamic_prefixes(vec![|_,_| {Some("test".to_string())}])
    |              ^^^^^^^^^^^^^^^^ expected bound lifetime parameter, found concrete lifetime



error[E0277]: `[closure@src/main.rs:382:31: 388:14]` is not an iterator
   --> src/main.rs:382:14
    |
382 |             .dynamic_prefixes(|_, _| {}
    |              ^^^^^^^^^^^^^^^^ `[closure@src/main.rs:382:31: 388:14]` is not an iterator
    |
    = help: the trait `std::iter::Iterator` is not implemented for `[closure@src/main.rs:382:31: 388:14]`
    = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `[closure@src/main.rs:382:31: 388:14]`
```
```rust
.dynamic_prefixes({
    let x = |_ctx: &mut context, msg: &message| {
    if msg.is_private() {
        return vec!["."];
    } else {
        let guild_id = msg.guild_id.unwrap_or(guildid(0));
        if guild_id.0 % 2 == 0 {
            return vec!["."];
        }
    } 
    return vec!["."];
    };
    vec![x]
})

/*
error[E0271]: type mismatch resolving `for<'r, 's> <[closure@src/main.rs:359:25: 369:18] as std::ops::FnOnce<(&'r mut serenity::client::context::Context, &'s serenity::model::channel::message::Message)>>::Output == std::option::Option<std::string::String>`
   --> src/main.rs:358:14
    |
358 |             .dynamic_prefixes({
    |              ^^^^^^^^^^^^^^^^ expected struct `std::vec::Vec`, found enum `std::option::Option`
    |
    = note: expected struct `std::vec::Vec<&str>`
                 found enum `std::option::Option<std::string::String>`
*/
```

**Comment by tmokenc** [comment]
Try to declare `fn`s instead of `closure`
Here is a snipet of my bot
```rust
.dynamic_prefixes(&[normal_prefix, master_prefix])

fn normal_prefix(_ctx: &mut Context, msg: &Message) -> Option<String> {
    let config = crate::read_config();

    msg.guild_id
        .and_then(|guild| config.guilds.get(&guild))
        .and_then(|guild| guild.prefix.to_owned())
        .or_else(|| Some(config.prefix.to_owned()))
}

fn master_prefix(ctx: &mut Context, msg: &Message) -> Option<String> {
    get_data::<MasterList>(ctx)
        .filter(|v| v.read().iter().any(|&v| v == msg.author.id))
        .map(|_| "%".to_string())
}
```

**Comment by vicky5124** [comment]
Iris on the discord server got it to work with a closure. [Message Jump](https://discordapp.com/channels/381880193251409931/381912587505500160/679485856570277898)
Now the problem is that it's probably impossible to get multiple, variable, guild dependent prefixes, with the current version of dynamic_prefixes. The suggested fix is to instead of having an iterator of Fn(ctx, msg) as the type, to have an iterator of String, but keeping the access to ctx and msg. This will allow to return iterators of different lengths and different prefixes.

```rust
.dynamic_prefixes({
let x = |_ctx: &mut Context, msg: &Message| {
    if msg.is_private() {
        return Some(".".to_owned());
    } else {
        let guild_id = msg.guild_id.unwrap_or(GuildId(0));
        if guild_id.0 % 2 == 0 {
            return Some(".".to_owned());
        }
    } 
        Some(".".to_owned())
    };
    vec![x, x]
})
```

**Comment by tmokenc** [comment]
> Now the problem is that it's probably impossible to get multiple, variable, guild dependent prefixes,

If I understand this correctly (my English is bad), then there are 2 options for this (in my knowledge)
- Store these data inside the `Context.data`, then fetch and use them inside the closure
- Declare it globally with `static` keyword (or `lazy_static` if that value cannot be used with `static`)

*[This example](https://github.com/serenity-rs/serenity/tree/current/examples/05_command_framework) shows how to add data to the `Context.data` in case you haven't know about it yet*

*From my previous comment*
Here I stored all the configuration stuff (including guild's prefix) globally with `lazy_static` then use them inside the function
*this one will check for guild custom prefix, use default prefix if that guild doesn't have it* 
```rust
fn normal_prefix(_ctx: &mut Context, msg: &Message) -> Option<String> {
    // `crate::read_config()` just simply return the reference to that `static` value
    let config = crate::read_config();

    msg.guild_id
        .and_then(|guild| config.guilds.get(&guild))
        .and_then(|guild| guild.prefix.to_owned())
        .or_else(|| Some(config.prefix.to_owned()))
}
```
---
This one I stored the MasterList (just a Vec of UserId) inside the `Context.data` then fetch it from that `&mut Context`
*This one will check for owners exclusive prefix that can be used anywhere by anyone who is in the MasterList*
```rust
fn master_prefix(ctx: &mut Context, msg: &Message) -> Option<String> {
    // `get_data<T>` is just a shortcut for `ctx.data.read().get::<T>()
    get_data::<MasterList>(ctx)
        .filter(|v| v.read().iter().any(|&v| v == msg.author.id))
        .map(|_| "%".to_string())
}
```

**Comment by vicky5124** [comment]
Yes, i understood your code, but i don't think you understanded what i meant.
My goal is for guilds to be able to have multiple prefixes by themselfs.
Example: 
- Guild x: ["n!", "?", "]"]
- Guild y: ["!", ","]
- Guild z: ["?", "]", "pls", "/", "+"]

Your code can only assign a single prefix for each guild rather than multiple, This is what i find to be impossible or very stupid to make with the current method.

**Comment by tmokenc** [comment]
Oh, that makes sense!
Since we have the reference to `Message`, you can manually check the prefix that matches with the content and return it (e.g. ``prefixes.iter().find(|&prefix| msg.content.starts_with(prefix))``). But, as you said, it sounds stupid.

I would like to have the `dynamic_prefixes` that takes `Fn`s which return `impl IntoIterator<Item=String>` rather than `Option<String>`, since the Option<T> [also implemented IntoIterator<Item=T>](https://doc.rust-lang.org/std/option/enum.Option.html#impl-IntoIterator), it won't be a breaking change or something (maybe, idk)

Btw, I am sorry for the late
I will *(maybe)* work on a PR for that when I'm home (about 11PM GMT+01)

**Comment by tmokenc** [comment]
I just realized that there is *(currently)* no way to `impl Trait` in a trait object...

**Comment by Lakelezz** [comment]
There is currently (v0.10) no `dynamic_prefixes` anymore. It would have to be added again. I will close this pull request, please open a new one if you want to add this functionality again.
