### ISSUE TITLE
Remove Discord Group Support

### ISSUE THREAD

**Issue by Lakelezz** [serenity-rs/serenity#799]
A discord bot cannot be part of a group, as a group inviter must be friend with the invited user.

There are a bunch of references in Serenity to groups, here a few examples:
https://docs.rs/serenity/0.8.0/serenity/model/channel/struct.Group.html
https://docs.rs/serenity/0.8.0/serenity/cache/struct.Cache.html#method.group
https://docs.rs/serenity/0.8.0/serenity/http/client/struct.Http.html#method.leave_group

The task of this would be to assemble all code that references these groups (this list above is not exhaustive) and remove the code.

**Comment by Lakelezz** [comment]
Some users in our community Discord discussed, that older bots might still be in groups, removing this API may be a breaking change for them.
It's not clear whether these bots receive group events still. If somebody knows, please inform.

Edit: As it seems, bots are no longer allowed to use this endpoint.

**Comment by arqunis** [comment]
Resolved in #812.
