### ISSUE TITLE
Add Stream permission

### ISSUE THREAD

**Issue by dthul** [serenity-rs/serenity#807]
Discord has a new `STREAM` permission for voice channels (0x00000200 - Allows the user to go live).
I could prepare a PR for this. Is it only necessary to add it to `permissions.rs` or does some other code need to know about it as well?

**Comment by arqunis** [comment]
We would appreciate a pull request. :heart: 

Adding this should only require modifying `permissions.rs` and the [`Guild::user_permissions_in`](https://github.com/serenity-rs/serenity/blob/current/src/model/guild/mod.rs#L1346) method.

**Comment by dthul** [comment]
Just got around to doing it but I see that it has already been done!
