### ISSUE TITLE
Add support for the "Delete All Reactions for Emoji" endpoint

### ISSUE THREAD

**Issue by arqunis** [serenity-rs/serenity#813]
https://discordapp.com/developers/docs/resources/channel#delete-all-reactions-for-emoji

**Comment by Th3-M4jor** [comment]
I volunteer to take this one on if nobody else has yet.

But should I wait until `next` is async ready before tackling this one?

**Comment by Lakelezz** [comment]
Hello, thank you for your interest :)
You can use `next` or pull request on the repository for _Serenity.await_.

**Comment by arqunis** [comment]
This has been resolved by https://github.com/serenity-rs/serenity/pull/844.
