### ISSUE TITLE
Member.ban(), Message.react() and possibly others do not work with the native_tls_backend feature.

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#818]
When using the native_tls_backend instead of the default rustls_backend, the ban() and react() methods provide an incorrect json format to the api.

The status code obtained is 411, which is not documented on the [discord api documentation](https://discordapp.com/developers/docs/topics/opcodes-and-status-codes).
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(UnsuccessfulRequest(ErrorResponse { status_code: 411, url: "https://discordapp.com/api/v6/channels/544938131347210283/messages/696467511872454716/reactions/%E2%AC%85%EF%B8%8F/@me", error: "[Serenity] No correct json was received!" }))', src/main.rs:19:9
```

[This](https://discordapp.com/channels/381880193251409931/673965002805477386/696467741321723904) is the code it was tested on, just example 1 with react inside the message event

**Comment by vicky5124** [comment]
UPDATE: it also happens on the branch "next" of the  official repo.
[Tested project](https://cdn.discordapp.com/attachments/381912587505500160/696709492716339210/discord_bot_test_next.zip)

**Comment by vicky5124** [comment]
UPDATE of UPDATE: It happens on release 0.8.1, but not on 0.8.0

**Comment by Lakelezz** [comment]
Thanks for your issue :)
