### ISSUE TITLE
Allow passing a reference to Message::react?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [serenity-rs/serenity#820]
Message::react currently takes an `Into<ReactionType>`. As far as I can tell, this means that the ReactionType would end up being constructed/cloned every time this method is called.

I see that the internal function `_react` takes a reference, could this be exposed to users?

**Comment by Th3-M4jor** [comment]
If you have access to a context, you could use https://docs.rs/serenity/0.8.1/serenity/http/client/struct.Http.html#method.create_reaction from context.http

Since this is a public function that you can call
