### ISSUE TITLE
Dynamic prefixes with a capital letter don't work with case_insensitivity(true)

### ISSUE THREAD

**Issue by vicky5124** [serenity-rs/serenity#825]
While using case_insensitivity(true), a dynamic prefix that contains a capital letter, will not be able to invoke any command with that prefix, no matter the capitalization.

Simple test code:

```rust
#[hook]
async fn dynamic_prefix(ctx: &mut Context, msg: &Message) -> Option<String> {
    Some("tesT")
}
...
    let framework = StandardFramework::new() // Create a new framework
        .configure(|c| c
            .dynamic_prefix(dynamic_prefix)
            .case_insensitivity(true)
        );
```
running  any command with the prefix tesT will not work, removing the case_insensitivity option or making the dynamic prefix return `"prefix".to_lowercase()` fixes the issue, but the prefix would no  longer be accurate if the second option is chosen.

**Comment by arqunis** [comment]
This is fixed by https://github.com/serenity-rs/serenity/pull/826.
