### ISSUE TITLE
It's possible to create role with empty name

### ISSUE THREAD

**Issue by oOBoomberOo** [serenity-rs/serenity#835]
You can create a role with empty name via [this method](https://docs.rs/serenity/0.8.3/serenity/model/guild/struct.Guild.html#method.create_role)

This look harmless at first but discord actually wouldn't be able to make sense of it.
Mention of other roles will be changed to `<@123456789>` (The number is an example) where only the `@` is highlighted. You wouldn't be able to modify the role at all. You can only choose to delete the role from the server.

So yeah, it's not healthy for discord to have a role with an empty name.

**Comment by Lakelezz** [comment]
I see this as a bug on Discord's end, it's their job to reject invalid requests, not necessarily as Serenity's.
