### ISSUE TITLE
Wrong field name (kind -> type) in ChannelMention

### ISSUE THREAD

**Issue by xSke** [serenity-rs/serenity#838]
Deserializing a message containing a cross-server channel mention fails with `error decoding response body: missing field `kind` at line 1 column 21409`

Here's a real-world example of the structure, pulled from an announcement channel (type 5) cross-post:

```json
"mention_channels": [
    {
        "id": "563938089177972748",
        "name": "borderlands-news",
        "type": 5,
        "guild_id": "132671445376565248"
    }
]
```

However, the struct specifies the "type" field as being named "kind", which it, well, isn't: https://github.com/serenity-rs/serenity/blob/current/src/model/channel/message.rs#L844

Sauce in Discord API docs: https://discordapp.com/developers/docs/resources/channel#channel-mention-object

Should be a quick fix, I just don't have a proper dev setup at the moment, hoping someone else has the project open :)

**Comment by arqunis** [comment]
Should be fixed by https://github.com/serenity-rs/serenity/commit/4730038351f0e5c9d5615ba4a4c55ca426d83e99.
