### ISSUE TITLE
Embed character limit errors

### ISSUE THREAD

**Issue by zacps** [serenity-rs/serenity#843]
Attempting to create an embed with a description longer than 2048 characters (discord limit) fails with:

```
[Serenity] No correct json was received
```

After editing and recompilling serenity I found that discord returns the following json:

```json
{"embed": ["description"]}
```

It would be good to improve this error message (and presumably those for the other character limits).

**Comment by Erk-** [comment]
How the error messages works for embeds is 1. Unducumented, making it hard to implement properly. and 2. Not fully working on api/v6 iirc. such if you for example send an embed with a empty title you will get back so json that does not say much about the error.

**Comment by zacps** [comment]
In the worst case you could always return the raw json response, it'd give more information about the error than you get currently.

**Comment by Lakelezz** [comment]
As latest Serenity is no longer using v6, I will close this.
If this error still persists on the latest release, please inform us!
On another note, the model/HTTP rework will fix this problem before sending the request.
