### ISSUE TITLE
Message::content_safe not replacing <@!...> user mentions

### ISSUE THREAD

**Issue by MaxOhn** [serenity-rs/serenity#850]
https://github.com/serenity-rs/serenity/blob/620faa2c5dc371ece8d38a4cd571f96084e89b5a/src/model/channel/message.rs#L303

`Message::content_safe` currently replaces whatever `UserId::mention` returns in
https://github.com/serenity-rs/serenity/blob/620faa2c5dc371ece8d38a4cd571f96084e89b5a/src/model/misc.rs#L81
However, `<@!...>` user mentions will not be replaced.

**Comment by ks129** [comment]
I will make PR for this.
