### ISSUE TITLE
GuildId missing "name"

### ISSUE THREAD

**Issue by codecat** [serenity-rs/serenity#851]
It looks like there is a [`name()` method on `ChannelId`](https://docs.rs/serenity/0.8.6/serenity/model/id/struct.ChannelId.html#method.name) but there's no such method on [`GuildId`](https://docs.rs/serenity/0.8.6/serenity/model/id/struct.GuildId.html).

Perhaps it's a missing function from the API, or I'm totally overlooking some other way to get guild info.

Serenity version: 0.8.6

Rust version (`rustc -V`): rustc 1.43.0 (4fb7144ed 2020-04-20)

**Comment by Arzte** [comment]
For the meantime, you can get this info out of [`GuildId`](https://docs.rs/serenity/0.8.6/serenity/model/id/struct.GuildId.html) using the [`.to_guild_cached()`](https://docs.rs/serenity/0.8.6/serenity/model/id/struct.GuildId.html#method.to_guild_cached) method, and then use the [`.name`](https://docs.rs/serenity/0.8.6/serenity/model/guild/struct.Guild.html#structfield.name) field on the struct that returns.

(Note that it requires the cache feature, and also needs you to first unwrap the option, and then the RwLock surrounding the [`Guild`](https://docs.rs/serenity/0.8.6/serenity/model/guild/struct.Guild.html) struct it returns)

**Comment by arqunis** [comment]
Resolved by https://github.com/serenity-rs/serenity/pull/863.
