### ISSUE TITLE
GuildId::create_role fails because of missing field `guild_id`

### ISSUE THREAD

**Issue by NilsIrl** [serenity-rs/serenity#856]
`GuildId::create_role` returns a `Role` which contains a `guild_id`. However, [discord doesn't return a `guild_id` on role creation](https://discord.com/developers/docs/topics/permissions#role-object) as the role object doesn't contain a `guild_id`.

3 fixes that I can see:

* Remove `guild_id` from `Role` to match the Role object of the discord API
* Add a `Role` type that doesn't contain `guild_id` (a `PartialRole`) which `create_role` will return
* Add a private intermediate type which we create a `Role` out of using the `guild_id` that `create_role` is passed to as argument

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(Request(reqwest::Error { kind: Decode, source: Error("missing field `guild_id`", line: 1, column: 185) }))', src/main.rs:48:24
stack backtrace:
```

Note: this happened on the async/await branch.

**Comment by arqunis** [comment]
The fix is already done in https://github.com/serenity-rs/serenity/pull/855; it's waiting for review from @Lakelezz. After it is merged into the `next` branch, it's just a matter of her porting my fix in her async/await PR.

**Comment by arqunis** [comment]
This issue is fixed in both the `next` and `await` branches.
