### ISSUE TITLE
Pulseaudio socket -> discord

### ISSUE THREAD

**Issue by MagicRB** [serenity-rs/serenity#859]
I think it should be possible to create a pulseaudio socket, by starting a pulseaudio daemon and using a virtual sink to route all the audio from client applications which connect to it, through discord. It could be used to play audio from a desktop based audio player and also on Linux when you stream your desktop, no audio gets through, it would also help with that.

**Comment by Erk-** [comment]
I think you should be able to do this with ffmpeg, At least it does work in some way with ffmpeg according to their documentation. Maybe try it out, and then you can use ffmpeg_optioned to run it in the bot.

**Comment by MagicRB** [comment]
yeah, though I need to create a custom boxed audio source, but that should be possible too, we'll try it today and then maybe we could make a specific function for it in serenity. I'll open a PR later

**Comment by Lakelezz** [comment]
Little hint: Use the `next`-branch for the pull request, as we do not accept any new features for the `current` (branch name) release series (v0.8.0).

**Comment by MagicRB** [comment]
After poking around a bit, I found out that pulseaudio requires D-Bus, which in turn requires an X session, which is useless for me. You can run pulseaudio in system mode, but that requires it to be running as root. Therefore I am no longer interested in this feature until I can force pulse to run in system mode as a non-root user.

**Comment by Lakelezz** [comment]
Okay, I will close this then.

**Comment by Erk-** [comment]
@MagicRB I think you should be able to do the same with ALSA which may be easier. Else you could always do stuff like streaming it over icecast and then replaying it.
