### ISSUE TITLE
How to call help command on group prefix with no arguments?

### ISSUE THREAD

**Issue by jacobbridges** [serenity-rs/serenity#875]
Serenity version: 0.8.6
Rust version (`rustc -V`): rustc 1.43.1

I have a command group, and when a user passes in the group prefix with no parameters, I would like the help information for the group to print.

So, if I have a group like this:

```rust
#[group]
#[prefixes("color", "cl")]
#[description = "Manage the color of your Discord username."]
#[commands(add, list, delete, set)]
struct Color;
```

I would like the output of `!color` to be the same output as doing `!help color`. 

Any suggestions? (btw this is an awesome lib thus far :D)

**Comment by arqunis** [comment]
We have deprecated the standard framework and are moving towards [poise](https://github.com/serenity-rs/poise/) being the go-to framework instead.
