### ISSUE TITLE
Add command_name to the dispatch error hook

### ISSUE THREAD

**Issue by kingbri1** [serenity-rs/serenity#876]
`Serenity version: await@a2e8cde`

On a dispatch error, I would like to let the user know what command errored and why. However, this would require parsing the message and filtering the first word without the command prefix. Other included hooks such as `after` and `unrecognized_command` both use command_name to help me know exactly what command is being used.

Example: When someone provides not enough args on my mock command, the dispatch error should fire and be handled by letting the user know that the mock command errored because 0 args were provided and the minimum threshold is 1.

Doing this can also be useful for sending out different error messages based on command name, therefore reducing extra code.

**Comment by kangalio** [comment]
Can this issue be closed now?

**Comment by kingbri1** [comment]
Has someone tested if it works? If so, I'll close the issue.

**Comment by kangalio** [comment]
Yeah, quoting the PR text:

> I tested this by creating a little test bot that triggers almost all possible dispatch error conditions: https://pastebin.com/KNNRM1K1

**Comment by kingbri1** [comment]
Awesome! Thanks for implementing this. Closing issue.
