### ISSUE TITLE
Send a message from outside an event handler

### ISSUE THREAD

**Issue by zacps** [serenity-rs/serenity#879]
Is there a way to send a message from outside an event handler, as a response to an external action?

I wasn't able to find anything in the documentation.

**Comment by vicky5124** [comment]
You are able to do this anywhere where you have access to either Client.http or Context.http, as it's required for say() or send_message()

This can `Arc`ed  from likely the main function or a event, and cloned to where you need it.
Then you will be able to use `ChannelId(id as u64).say(&http, "message")?`

Any other similar issues would be preferred to be asked on the [discord server](https://discord.gg/WBdGJCc).

**Comment by zacps** [comment]
Thanks, I missed that.

It might be worth adding a note under the `cache_and_http` field in the `Client` that this is possible?

**Comment by kivikakk** [comment]
Thanks for asking this question — finally found what I was looking for! This is likely a common use case and deserves an example; would a PR be accepted for this?

**Comment by arqunis** [comment]
> would a PR be accepted for this?

Sure. It should be easy to add. [Here's where to place the example](https://github.com/serenity-rs/serenity/blob/current/src/model/id.rs#L94). It has to be written in the pattern as all other documentation-based examples in the library are. One such example of the pattern is [`ChannelId::broadcast_typing`](https://github.com/serenity-rs/serenity/blob/current/src/model/channel/channel_id.rs#L44-L53).

**Comment by kivikakk** [comment]
Right, thanks!

I was thinking a top-level example (under the `examples/`) directory might be more discoverable. I looked through all those before searching through the codebase, then eventually fell back to Googling until I found this issue. Something like `e14_message_outside_loop` and do it on a timer or different external event.
