### ISSUE TITLE
Start and stop typing

### ISSUE THREAD

**Issue by nate-blum** [serenity-rs/serenity#900]
Hey everyone,
I just wanted to see if there was some way you could implement a start and stop typing functionality instead of having broadcast_typing. 
Essentially, I want to call start_typing when my command starts thinking, and then have sending the message make it stop typing or call stop_typing myself.
Thank you!

**Comment by asherkin** [comment]
There doesn't appear to be a Discord-API-level "Stop Typing" - only "Trigger Typing Indicator", which is what `broadcast_typing` uses.

The Discord client appears to automatically clear the local typing indicator when a message is received.

**Comment by arqunis** [comment]
Resolved with #978.
