### ISSUE TITLE
Misleading sentence in docs

### ISSUE THREAD

**Issue by kangalio** [serenity-rs/serenity#914]
In [`serenity::builder::CreateEmbed`](https://docs.rs/serenity/0.8.6/serenity/builder/struct.CreateEmbed.html#examples) it says
```
Refer to the documentation for ChannelId::send_message for a very in-depth example on how to use this.
```

However, the documentation for `ChannelId::send_message` doesn't have the promised example:
![Screenshot_20200714_111158](https://user-images.githubusercontent.com/21220820/87407732-d8368380-c5c2-11ea-9466-54de07ea6698.png)

**Comment by MauledByLove** [comment]
I'm new to the project, but I'd like to take this on as a way to get familiar with the API.

**Comment by ddjerqq** [comment]
how can this be fixed?
