### ISSUE TITLE
Get User/Member info from MESSAGE_REACTION_ADD

### ISSUE THREAD

**Issue by asherkin** [serenity-rs/serenity#922]
Opening an issue for this one rather than a PR adding it, as it looks like a few possible approaches and I'm not sure which is best.

Discord includes a `member` entry in the `MESSAGE_REACTION_ADD` event for the user adding the reaction that isn't currently exposed, but would be quite useful to have. It's a little special as unlike the one in `MESSAGE_CREATE` it includes the `user` object, however `member` does not have a `guild_id` key, so it doesn't deserialise to the existing full model struct. The existing `MESSAGE_REACTION_ADD` test samples don't appear to include it, but I can't see in the Discord changelog where it was added.

https://discord.com/developers/docs/topics/gateway#message-reaction-add

https://discord.com/developers/docs/resources/guild#guild-member-object

```json
{
  "t": "MESSAGE_REACTION_ADD",
  "s": 3,
  "op": 0,
  "d": {
    "user_id": "298220148647526402",
    "message_id": "736353186369241138",
    "member": {
      "user": {
        "username": "asherkin",
        "id": "298220148647526402",
        "discriminator": "4741",
        "avatar": "8e72c065fc8944d50a8df3cd081490a6"
      },
      "roles": [
        "335517500685156352",
        "336262157157269525",
        "338570353779539978",
        "688211615560106034"
      ],
      "mute": false,
      "joined_at": "2017-07-16T20:14:07.964000+00:00",
      "hoisted_role": "336262157157269525",
      "deaf": false
    },
    "emoji": {
      "name": "FeelsHugMan",
      "id": "520712163162193921"
    },
    "channel_id": "735953391687303260",
    "guild_id": "335290997317697536"
  }
}
```

After a bit of poking around I think there are 3 likely options:
* Add `Option<PartialMember>` to `Reaction`, and `Option<User>` to `PartialMember` (making it essentially `Member` without a `guild_id`) - this is the easy, safe route for sure, but doesn't feel right.
* Make `guild_id` optional in `Member` - it isn't actually documented as existing in the Discord docs - but this has quite a bit of fallout, and it is useful to have.
* Somehow inject `guild_id` into `member` when handling `MESSAGE_REACTION_ADD`, something like #855?

**Comment by asherkin** [comment]
There's another related case here that might be worth considering at the same time: the user objects in the `mentions` list in `MESSAGE_CREATE` include a `member` key with the partial member info. This isn't documented as a valid part of the [user object](https://discord.com/developers/docs/resources/user#user-object), but is documented as part of the [message object](https://discord.com/developers/docs/resources/channel#message-object) docs instead.

**Comment by duckyyylol** [comment]
pog idea
