### ISSUE TITLE
client.start() hangs with invalid token

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#927]
pretty much the title: when client.start() is run it just sits there and does nothing, and the bot does not appear as online in discord. I have tried both the example from the readme and example 0 from the examples directory. the token is correctly set.

windows 10 2004, rustc 1.44.1.

edit: fixed it, i was using the wrong token, however this is still unintended behaviour

**Comment by AlexanderHurst** [comment]
Ensure that you are using the right token, and that if you are loading it from a .env file with kankyo it isn't surrounded in quotes and doesn't have any spaces (including around the equals sign).
For example you want `DISCORD_TOKEN=your-discord-token-here` not `DISCORD_TOKEN="your-discord-token-here"`
I was having the same problem until I removed the quotes

**Comment by ghost** [comment]
yep! i've also tried to hardcode it and same issue

**Comment by ghost** [comment]
I was using the client secret instead of the bot token! I still think it should error though...

**Comment by vicky5124** [comment]
Reopen the issue, and specify that start() only hangs when an invalid token is provided.

**Comment by occanowey** [comment]
This was fixed in #905 (specifically [this](https://github.com/Lakelezz/serenity/commit/0fad30bdf491b5cdc003ebb12bf33d3ea4233df5#diff-97e5709662573f7dfb6481ddc4fffb96R103) commit)
