### ISSUE TITLE
on `ready` the `private_channels` field is empty

### ISSUE THREAD

**Issue by Geobert** [serenity-rs/serenity#929]
Hi,

I have a DM channel with my bot, but on the event `ready` the `Ready` struct doesn't have the channel in the `private_channels` field. Am I missing something?

**Comment by vicky5124** [comment]
Discord does not send previous DM channels on the Ready event to bot users.

**Comment by Geobert** [comment]
Oh :( Thank you for your answer, closing this then :)

**Comment by Geobert** [comment]
For the sake of completeness, I found this on Discord API issue tracker: https://github.com/discord/discord-api-docs/issues/184
TL;DR: it is intentionnal and the only workaround it to use `private_channel_create`
