### ISSUE TITLE
Token with Mobile Auth not working with Serenity

### ISSUE THREAD

**Issue by Jev1337** [serenity-rs/serenity#938]
Hey! I wanted you all to know that everytime I work with a token that starts with a token that looks like this:

"mfa.9Gt3xDUjLmFQjXXxqBcn1oSyDNIq6cdDK0aS7pPDS44m_uX3DX1VayaFz5VVEb1owN3rm5_YAO4iPZI6q_ii"

It gives an error whenever connecting to discord with it...

**Comment by vicky5124** [comment]
You can't userbot with serenity.
and you should not be doing that with ANY library, userbotting is against tos and will lead to a ban if discovered.

**Comment by Jev1337** [comment]
> You can't userbot with serenity.
> and you should not be doing that with ANY library, userbotting is against tos and will lead to a ban if discovered.

It's for testing purposes though, I am fully aware of that..

**Comment by vicky5124** [comment]
> > You can't userbot with serenity.
> > and you should not be doing that with ANY library, userbotting is against tos and will lead to a ban if discovered.
> 
> It's for testing purposes though, I am fully aware of that..

Just don't userbot in any circumstances. Serenity will not support any features that will go against TOS or are undocumented.

**Comment by Jev1337** [comment]
> > > You can't userbot with serenity.
> > > and you should not be doing that with ANY library, userbotting is against tos and will lead to a ban if discovered.
> > 
> > 
> > It's for testing purposes though, I am fully aware of that..
> 
> Just don't userbot in any circumstances. Serenity will not support any features that will go against TOS or are undocumented.

But all others support user tokens! It's a risk US users take not Serenity! 

Whoever knows whats hes doing, will understand that it is against TOS and will understand that it is just for his/her "whatever" purposes...

**Comment by Erk-** [comment]
Refer to #257
