### ISSUE TITLE
ReactionCollector and await_reaction won't work on direct messages initiated by the bot.

### ISSUE THREAD

**Issue by deadshot465** [serenity-rs/serenity#940]
Supposed when a user joins a guild or a user sends out a command in a guild channel, the bot will DM the user and provide some help, then wait for reactions from the user inside the DM channel, the current version's `ReactionCollector` and `await_reaction` don't seem to work properly; that is, they can't successfully listen for reactions to a DM message sent out by bot from the user.

The following code doesn't seem to work properly:
```rust
let _msg: Message = msg.author.dm(&context.http, |m| m.content("Hello World.")).await?;
if let Some(r) = &_msg.await_reaction(&context)
    .author_id(msg.author.id.0)
    .timeout(tokio::time::Duration::from_secs(30)).await {
    _msg.channel_id.say(&context.http, "Hello.").await?;
}
```
However, if I change it to listen for message replies from the user instead, it will work; therefore, I'm opening this issue to see if it's actually a bug. Thanks.

**Comment by Lakelezz** [comment]
I tried to reproduce this on latest [`current`](https://github.com/serenity-rs/serenity/commit/f1204a8b7bae333fae4cbff2553882e6f2ab9f0d) by copying your code inside the collector example's message event on the event handler, it works fine for me.

What features are you using? Where are you doing this? Is there more code to this? Does the `current`-branch work for you?

**Comment by rasm47** [comment]
![pic](https://user-images.githubusercontent.com/16821766/124020924-95e49d00-d9f3-11eb-8862-bdd274895585.png)
I failed to replicate the issue on 0.10.8.

`Cargo.toml`
```
[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serenity = { version = "0.10", features = ["framework", "standard_framework", "rustls_backend", "collector"] }
```


`main.rs`
```rust
use serenity::{
    framework::standard::{
        macros::{command, group},
        CommandResult, StandardFramework,
    },
    model::prelude::*,
    prelude::*,
};

#[group("collector")]
#[commands(dm)]
struct Collector;

#[tokio::main]
async fn main() {
    let token = "REDACTED";

    let framework = StandardFramework::new()
        .configure(|c| c.prefix("."))
        .group(&COLLECTOR_GROUP);

    let mut client = Client::builder(&token)
        .framework(framework)
        .await
        .expect("Err creating client");

    if let Err(why) = client.start().await {
        println!("Client error: {:?}", why);
    }
}

#[command]
async fn dm(ctx: &Context, msg: &Message) -> CommandResult {
    let bot_dm = msg
        .author
        .dm(&ctx.http, |m| m.content("Please react to this in 3 mins."))
        .await?;

    if let Some(_reaction) = &bot_dm
        .await_reaction(&ctx)
        .author_id(msg.author.id.0)
        .timeout(tokio::time::Duration::from_secs(3 * 60))
        .await
    {
        bot_dm
            .channel_id
            .say(&ctx.http, "You reacted in time.")
            .await?;
    }

    Ok(())
}
```

The above code worked without any issues.
