### ISSUE TITLE
How to pass additional Struct to Serenity commands ? Rust Beginner

### ISSUE THREAD

**Issue by steelx** [serenity-rs/serenity#945]
hi.
Im trying to make nextwork request to external API's which needs authentications.
Currently Im using reqwest to make Basic auth for which I have this struct `Auth` 
```
pub struct Auth {
    email: String,
    password: String,
    pub ubi_config: UbiConfig,
    expiration: String,
    authorization: String,
    client: reqwest::Client,
}
```

The `Auth` struct has methods which makes external network calls
- `login` gets sessions from API
- `findProfile` which finds a username from a game server

How do I link Auth and serenity commands together.

```rust

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // -> Result<(), reqwest::Error> 
    dotenv().ok();
    let config = Config::from_env().unwrap();

    // Auth content calls to external API using reqwest
    let mut auth = Auth::new(&config.auth.email, &config.auth.password, config.ubi);

    // let session = auth.login().await.expect("Authentication failed!");
    

    let framework = StandardFramework::new()
        .configure(|c| c.prefix("?rs ")) // set the bot's prefix to "?rs " eg. ?rs rank steelx
        .help(&HELP)
        .group(&GENERAL_GROUP);


    let mut client = serenity::client::Client::new(&config.auth.discord_token)
        .framework(framework)
        .await
        .expect("Err creating client");

    if let Err(why) = client.start().await {
        println!("Client error: {:?}", why);
    }

    Ok(())
}


```

**Comment by arqunis** [comment]
Hello.

The [`Client::data`](https://docs.rs/serenity/0.9.0-rc.0/serenity/client/struct.Client.html#structfield.data) and `Context::data` (copy of the former) fields serve this purpose to share data across event handlers and commands.

**Comment by steelx** [comment]
> Hello.
> 
> The [`Client::data`](https://docs.rs/serenity/0.9.0-rc.0/serenity/client/struct.Client.html#structfield.data) and `Context::data` (copy of the former) fields serve this purpose to share data across event handlers and commands.

thanks. I did the following
```rust

let mut data = client.data.write().await;
    data.insert::<Auth>(auth);
```
But I get the error `the trait `typemap_rev::TypeMapKey` is not implemented for `auth::Auth``

```
impl TypeMapKey for Auth {
    type Value = Auth;
}
```
then inside commands folder..

I did this

```rust
#[command]
pub async fn rank(ctx: &Context, msg: &Message, mut args: Args) -> CommandResult {
    let mut data = ctx.data.write().await;
    let auth = data.get_mut::<Auth>().unwrap();

...
```

is this correct ? Thank you

**Comment by arqunis** [comment]
In order to insert your data into `Client::data`, you must first define a key that you will use to reference specific data.

```rust
pub struct AuthData;

impl serenity::prelude::TypeMapKey for AuthData {
     type Value = Auth;
}
```
You then use the key to insert data:
```rust
let mut data = client.data.write().await:
data.insert::<AuthData>(auth);
```

The same way goes for reading data:
```rust
// assuming `ctx` is `&Context`
let mut data = ctx.data.read().await;
let auth = data.get::<AuthData>().unwrap();
```

If you define `AuthData` in your `main.rs`, you can import it in `commands/rank.rs` using:
```rust
use crate::AuthData;
```

**Comment by steelx** [comment]
thanks for guidance :)
