### ISSUE TITLE
Build timeout due to tungstenite ERROR: context deadline exceeded

### ISSUE THREAD

**Issue by steelx** [serenity-rs/serenity#947]
Build's ok on local machine. But when doing same on GCP, build timeout.
I increased the timeout to 900seconds (15mins) GCP allows this as maximum.
Also increased RAM to 1GB.

Still I'm having same issue. (complete log [here](https://pastebin.run/cwBsSQKKqq))

**tungstenite**

> TIMEOUT
> ERROR: context deadline exceeded
```
Step #0 - "Build": [0m[91m [0m[91m [0m[91m [0m[91mCompiling[0m[91m [0m[91mtokio[0m[91m v[0m[91m0.2.22[0m[91m
Step #0 - "Build": [0m[91m [0m[91m [0m[91m [0m[91mCompiling[0m[91m [0m[91mtungstenite[0m[91m v[0m[91m0.10.1[0m[91m
TIMEOUT
ERROR: context deadline exceeded
Step #0 - "Build": [0m[91m [0m[91m [0m[91m [0m[91mCompiling[0m[91m [0m[91mfutures-util[0m[91m v[0m[91m0.3.5[0m[91m
```

**Comment by AriusX7** [comment]
Building serenity-based bots can take well over 15 minutes depending on the available cores and RAM. It takes me over that when building on my Linux VM.

If the architecture and operating system GCP uses is the same as your local computer, then you can simply build the bot on your local computer and copy that to GCP. If the architecture or OS are different, you may wanna look at cross compiling using [cross](https://github.com/rust-embedded/cross).

**Comment by Lakelezz** [comment]
Yes, building Rust and Serenity can take a while. I will close this issue as it seems answered.
