### ISSUE TITLE
Bot goes offline after a while

### ISSUE THREAD

**Issue by saanuregh** [serenity-rs/serenity#955]
Here is the logs
`2020-09-08T23:58:45.320190215Z [2mSep 08 23:58:45.319[0m [32m INFO[0m serenity::gateway::shard: [Shard [0, 1]] Resumed    
2020-09-09T01:18:23.064070175Z [2mSep 09 01:18:23.063[0m [33m WARN[0m serenity::gateway::shard: [Shard [0, 1]] Unknown unclean close 1001: Some("")    
2020-09-09T01:18:23.276298913Z [2mSep 09 01:18:23.276[0m [32m INFO[0m serenity::gateway::shard: [Shard [0, 1]] Resumed    
2020-09-09T04:46:22.434717835Z [2mSep 09 04:46:22.434[0m [32m INFO[0m serenity::gateway::shard: [Shard [0, 1]] Resumed `

**Comment by memchk** [comment]
For reference, I have seen this behavior with https://github.com/memchk/robotdevil as well on rc1.

**Comment by AhiVT** [comment]
@acdenisSK Is this a shard panicking by chance? I am experiencing shard panics on RC1 and don't want to open an issue if this is related at all.

**Comment by arqunis** [comment]
@Dunklheit Probably. We have also been under suspicion that panics in the shard may be causing OOMs on Linux, but we are not entirely sure. Could you post logs of your panics perchance?

**Comment by AhiVT** [comment]
@acdenisSK I've made adjustments to my code over at https://github.com/MOONMOONOSS/pit-tracker to capture any errors causing the client to panic out. 

Specifically my repo was at commit [e391bce](https://github.com/MOONMOONOSS/pit-tracker/tree/e391bce7c1ed3d954ed225bfb1d2e689d83bb143) which wasn't sharded and closed the process. Latest commit is sharded and I write to file if the serenity loop terminates.

I'll upload a gist when I error out again.

**Comment by AhiVT** [comment]
Update: Bot crashed out but did not output an error to file. I need to make a shell script that pipes my bot's output to file

**Comment by AhiVT** [comment]
Update: all I get on program crashing is the single word `Killed`. No further information is given.

**Comment by ikkerens** [comment]
That's usually a reference to your system running out of memory and the linux kernel killing applications hoping to save itself.
Which does further solidify the suspicion that you too are affected by the OOM issue people are already investigating.

**Comment by saanuregh** [comment]
Sorry, I completely forgot about this issue, my crash was caused by a memory leak in my code, which is now fixed.

**Comment by AhiVT** [comment]
@ikkerens is last known working build rc0 or do should I try downgrading to 0.8?

**Comment by ikkerens** [comment]
@Dunklheit Last working build is 0.8, the issue has been present since async was a thing.

**Comment by arqunis** [comment]
Resolved by #975.
