### ISSUE TITLE
Search for subcommands in the help commands

### ISSUE THREAD

**Issue by arqunis** [serenity-rs/serenity#970]
Currently, the help commands only search through a group's commands, and any commands of its subgroups. They should also search subcommands if a command they received is valid.

**Comment by iddm** [comment]
+1 
Perhaps I'll take a look.

**Comment by Lakelezz** [comment]
It should be fixed now, feel free to try if you want :)

**Comment by iddm** [comment]
Started but haven't had enough free time to continue. Thanks for solving this!
