### ISSUE TITLE
[Question] What is the purpose of serenity's Request vs reqwest::Request

### ISSUE THREAD

**Issue by TheButlah** [serenity-rs/serenity#988]
It appears as though serenity uses reqwest under the hood in its Request api. What are the benefits of Serenity's api as opposed to directly using an HTTP client library like reqwest?

Is it worth the duplicated functionality, maintenance effort, and larger executable sizes (I'm making assumptions here, correct me if I'm wrong)? Why not type alias `reqwest`'s types, like is done with typemap?

**Comment by ikkerens** [comment]
You are indeed wrong.

Serenity's request is merely a wrapper for Reqwest, it adds all the required headers for Discord API interactions and translates the specifics of the API (response codes, body formatting etc) to rust code.

Furthermore, and rather important, it also deals with the handling of Discord ratelimits so we don't spam their API and avoid 429 responses as a whole.

That way the more abstract layer of serenity (outside of the Http impl) can focus on convenience without constantly having to write the http specifics.

**Comment by TheButlah** [comment]
Gotcha, thanks!
