### ISSUE TITLE
Remaining examples needing documentation

### ISSUE THREAD

**Issue by zeyla** [serenity-rs/serenity#99]
Examples are fundamental to good documentation, and so far most methods don't have proper examples.

Examples should at least compile and `no_run` where necessary (for example, where the example would normally hit the REST API or instantiate a client). Examples that assert should run as part of our doctests.

Here's an example of a simple doctest:

```rust
/// ```rust
/// use serenity::utils;
///
/// let url = "discord.gg/0cDvIgU2voY8RSYL";
///
/// assert_eq!(utils::parse_invite(url), "0cDvIgU2voY8RSYL");
/// ```
```

It's not good to unwrap options or results in examples, as users can copy the code directly and end up with problems. An example of a more complex doctest surrounded in a try_main to entice usage of the `?` operator looks like:

```rust
/// ```rust,no_run
/// # use serenity::model::GuildId;
/// # use std::error::Error;
/// #
/// # fn try_main() -> Result<(), Box<Error>> {
/// #     let mut guild = GuildId(0).get()?;
/// use serenity::utils;
///
/// // assuming a `guild` has already been bound
///
/// let base64_icon = utils::read_image("./guild_icon.png")?;
///
/// guild.edit(|g| g.icon(Some(&base64_icon)))?;
/// #     Ok(())
/// # }
/// #
/// # fn main() {
/// #     try_main().unwrap();
/// # }
/// ```
```

In this example, we surround the code visible to the user in `try_main`, so that we can make use of `?`. Documentation example lines starting with `#` hides that line from the generated documentation. See the [Rust API Guidelines](https://github.com/brson/rust-api-guidelines#c-question-mark) for more info.

If you'd like to claim one or more sections leave a comment with what ones or mention it in the [serenity channel in Discord API](https://discord.gg/PgQYQcc).

The following is a list that still needs examples:

- [ ] `cache` (the cache module docs need an example as well)
  - [x] `Cache` (#103)
    - `guild`
    - `group`
    - `private_channel`
    - `role`
    - `user`
- [x] `framework` (#101)
  - [x] `help_commands::{plain, with_embeds}`
  - [x] `Configuration` (others optional)
    - `blocked_guilds`
    - `blocked_users`
    - `disabled_commands`
    - `owners`
    - `prefix`
    - `prefixes`
  - [x] `Framework`
    - `bucket`
    - `simple_bucket`
    - `on`
    - `group`
    - `on_dispatch_error`
    - `before`
    - `after`
- [ ] `model`
  - [ ] `permissions`
    - `Permissions` can use a struct-level example
    - `PRESET_GENERAL`
    - `PRESET_TEXT`
  - [ ] `Attachment`
    - `dimensions`
  - [ ] `Ban` can use a struct-level example of when you'd use it
  - [ ] `ChannelId`
    - `broadcast_typing` can use a more thorough example
    - `create_permission`
    - `create_reaction`
    - `delete`
    - `delete_message`
    - `delete_messages`
    - `delete_permission`
    - `delete_reaction`
    - `edit` can use a more thorough example
    - `edit_message`
    - `message`
    - `messages`
    - `pin`
    - `reaction_users`
    - `say`
    - `send_message`
    - `unpin`
  - [x] `CurrentUser` (#104)
    - `avatar_url`
    - `distinct`
    - `static_avatar_url`
    - `invite_url`
  - [x] `Embed` (#105)
    - `fake`
  - [x] `Emoji` (#105)
    - `delete`
    - `edit`
    - `find_guild_id`
    - `url` can use a doctest with an assertion
  - [x] `Game` (method examples preferably show interacting with Shard methods) (#105)
    - `playing`
    - `streaming`
  - [ ] `Group` (others optional)
    - `add_recipient`
    - `broadcast_typing` shows an example when say, sending a file, to indicate work is being done
    - `create_reaction`
    - `delete_messages`
    - `delete_permission`
    - `delete_reaction`
    - `edit_message`
    - `icon_url`
    - `message`
    - `reaction_users`
    - `remove_recipient`
    - `say`
    - `send_files`
    - `send_message`
    - `unpin`
  - [ ] `Guild` (others optional)
    - `bans`
    - `channels`
    - `create_channel` could use a better example in a framework command
    - `create_emoji`
    - `create_integration`
    - `create_role` could use a second, complex example
    - `delete_emoji`
    - `delete_integration`
    - `delete_role`
    - `edit_emoji`
    - `edit_nickname`
    - `edit_emoji`
    - `is_large` example on when to use it, such as requesting member chunks on guild create
    - `kick`
    - `member`
    - `member_named`
    - `move_member`
    - `start_prune` showing a framework command example
    - `unban`
  - i got tired of typing here
- [ ] `utils`
  - [ ] `builder` (see `CreateInvite` or `ExecuteWebhook` for examples)
    - `CreateEmbed`
    - `CreateEmbedAuthor`
    - `CreateEmbedField`
    - `CreateEmbedFooter`
    - `CreateMessage`
    - `EditChannel`
    - `EditGuild`
    - `EditMember`
    - `EditProfile`
    - `EditRole`
    - `GetMessages`

**Comment by Roughsketch** [comment]
I'm working on Framework stuff now. I currently have `help_commands` done and might make a PR to gradually push the others soon.
