### ISSUE TITLE
Missing voice manager in project/dependencies?

### ISSUE THREAD

**Issue by rsmitsuda** [serenity-rs/serenity#993]
I've been trying to implement the first example just as a starting point (https://github.com/serenity-rs/serenity/tree/current/examples/e01_basic_ping_bot). As far as I can tell, everything is the same as the example; however, I am seeing this error multiple times. I am using serenity 0.9.0-rc.2 so could I be missing some other dependency (I have the tokio dependency in the .toml file as well)?

```
error[E0425]: cannot find value `voice_manager` in this scope

error[E0560]: struct `client::bridge::gateway::shard_manager::ShardManagerOptions<'_>` has no field named `voice_manager`
  |
  = note: available fields are: `data`, `event_handler`, `raw_event_handler`, `framework`, `shard_index` ... and 6 others
```

**Comment by arqunis** [comment]
The voice manager is only compiled when the `voice` feature is enabled. [The ping bot example does not have the feature on](https://github.com/serenity-rs/serenity/blob/current/examples/e01_basic_ping_bot/Cargo.toml#L8). Your error should go away when you enter `"voice"` into the `features` list.

**Comment by rsmitsuda** [comment]
Thanks, that solved that issue but I am now seeing a build error.  Previously I had copied only the example into my own project but I decided to just pull the whole project instead and run it from there so I should have all necessary files.  Is there an environment variable that I need to set?  I didn't see anything in the documentation.

```
error: failed to run custom build command for `audiopus_sys v0.1.7`

Caused by:
  process didn't exit successfully: `/root/Documents/serenity/examples/target/debug/build/audiopus_sys-ad1008aefea28c5b/build-script-build` (exit code: 101)
--- stdout
cargo:info=No feature or environment variable found, linking by default.
```

**Comment by Lakelezz** [comment]
As the main question is solved, I will close this issue.
If your other problem persists still, please open a new issue! Thank you :)
